// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AuthLinkResponseResult.
const (
	ProviderLinkSuccess AuthLinkResponseResult = "provider_link_success"
)

// Defines values for AuthLoginResponseResult.
const (
	LoginSuccess AuthLoginResponseResult = "login_success"
)

// Defines values for AuthLogoutResponseResult.
const (
	LogoutSuccess AuthLogoutResponseResult = "logout_success"
)

// Defines values for AuthProvider.
const (
	Apple AuthProvider = "apple"
	Kakao AuthProvider = "kakao"
)

// Defines values for AuthRefreshResponseResult.
const (
	RefreshSuccess AuthRefreshResponseResult = "refresh_success"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusOk HealthResponseStatus = "ok"
)

// Defines values for MetadataReadinessCheckSchema.
const (
	Initialized MetadataReadinessCheckSchema = "initialized"
)

// Defines values for MetadataReadinessCheckStatus.
const (
	MetadataReadinessCheckStatusOk MetadataReadinessCheckStatus = "ok"
)

// Defines values for ReadinessCheckStatus.
const (
	ReadinessCheckStatusOk ReadinessCheckStatus = "ok"
)

// Defines values for ReadinessResponseStatus.
const (
	ReadinessResponseStatusOk ReadinessResponseStatus = "ok"
)

// Defines values for SupportedCurrency.
const (
	EUR SupportedCurrency = "EUR"
	JPY SupportedCurrency = "JPY"
	KRW SupportedCurrency = "KRW"
	USD SupportedCurrency = "USD"
)

// Defines values for TripParticipantRole.
const (
	Member TripParticipantRole = "member"
	Owner  TripParticipantRole = "owner"
)

// AuthLinkResponse defines model for AuthLinkResponse.
type AuthLinkResponse struct {
	LinkedIdentity LinkedIdentity         `json:"linkedIdentity"`
	Result         AuthLinkResponseResult `json:"result"`
}

// AuthLinkResponseResult defines model for AuthLinkResponse.Result.
type AuthLinkResponseResult string

// AuthLoginResponse defines model for AuthLoginResponse.
type AuthLoginResponse struct {
	Result AuthLoginResponseResult `json:"result"`
	Tokens AuthTokens              `json:"tokens"`
	User   AuthUser                `json:"user"`
}

// AuthLoginResponseResult defines model for AuthLoginResponse.Result.
type AuthLoginResponseResult string

// AuthLogoutResponse defines model for AuthLogoutResponse.
type AuthLogoutResponse struct {
	Result AuthLogoutResponseResult `json:"result"`
}

// AuthLogoutResponseResult defines model for AuthLogoutResponse.Result.
type AuthLogoutResponseResult string

// AuthMeResponse defines model for AuthMeResponse.
type AuthMeResponse struct {
	LinkedProviders []AuthProvider `json:"linkedProviders"`
	User            AuthUser       `json:"user"`
}

// AuthProvider defines model for AuthProvider.
type AuthProvider string

// AuthRefreshResponse defines model for AuthRefreshResponse.
type AuthRefreshResponse struct {
	Result AuthRefreshResponseResult `json:"result"`
	Tokens AuthTokens                `json:"tokens"`
}

// AuthRefreshResponseResult defines model for AuthRefreshResponse.Result.
type AuthRefreshResponseResult string

// AuthTokens defines model for AuthTokens.
type AuthTokens struct {
	AccessToken           string    `json:"accessToken"`
	AccessTokenExpiresAt  time.Time `json:"accessTokenExpiresAt"`
	RefreshToken          string    `json:"refreshToken"`
	RefreshTokenExpiresAt time.Time `json:"refreshTokenExpiresAt"`
}

// AuthUser defines model for AuthUser.
type AuthUser struct {
	AvatarUrl   *string `json:"avatarUrl"`
	DisplayName string  `json:"displayName"`
	Email       *string `json:"email"`
	Id          string  `json:"id"`
}

// CreateTripRequest defines model for CreateTripRequest.
type CreateTripRequest struct {
	DefaultCurrency SupportedCurrency `json:"defaultCurrency"`

	// EndDate End date in YYYY-MM-DD format. Must be today or later and not before startDate.
	EndDate openapi_types.Date `json:"endDate"`
	Name    string             `json:"name"`

	// StartDate Start date in YYYY-MM-DD format. Must be today or later.
	StartDate openapi_types.Date `json:"startDate"`
}

// CreateTripResponse defines model for CreateTripResponse.
type CreateTripResponse struct {
	OwnerParticipant TripParticipant `json:"ownerParticipant"`
	Trip             Trip            `json:"trip"`
}

// DeviceInfo defines model for DeviceInfo.
type DeviceInfo struct {
	DeviceName *string `json:"deviceName"`
	Platform   *string `json:"platform"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string                   `json:"code"`
		Details []map[string]interface{} `json:"details"`
		Message string                   `json:"message"`
	} `json:"error"`
}

// GetTripDetailResponse defines model for GetTripDetailResponse.
type GetTripDetailResponse struct {
	Days               []TripDay              `json:"days"`
	ParticipantSummary TripParticipantSummary `json:"participantSummary"`
	Trip               Trip                   `json:"trip"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LinkedIdentity defines model for LinkedIdentity.
type LinkedIdentity struct {
	Email         *string      `json:"email"`
	EmailVerified bool         `json:"emailVerified"`
	Provider      AuthProvider `json:"provider"`
}

// ListTripsResponse defines model for ListTripsResponse.
type ListTripsResponse struct {
	Trips []TripListItem `json:"trips"`
}

// MetadataReadinessCheck defines model for MetadataReadinessCheck.
type MetadataReadinessCheck struct {
	Schema MetadataReadinessCheckSchema `json:"schema"`
	Status MetadataReadinessCheckStatus `json:"status"`
}

// MetadataReadinessCheckSchema defines model for MetadataReadinessCheck.Schema.
type MetadataReadinessCheckSchema string

// MetadataReadinessCheckStatus defines model for MetadataReadinessCheck.Status.
type MetadataReadinessCheckStatus string

// OAuthCredential Provider credential. Apple uses identityToken/authorizationCode/nonce. Kakao uses accessToken. dev* fields are accepted only when server dev OAuth is enabled.
type OAuthCredential struct {
	AccessToken       *string `json:"accessToken,omitempty"`
	AuthorizationCode *string `json:"authorizationCode,omitempty"`
	AvatarUrl         *string `json:"avatarUrl"`
	DevSubject        *string `json:"devSubject,omitempty"`
	DisplayName       *string `json:"displayName"`
	Email             *string `json:"email"`
	EmailVerified     *bool   `json:"emailVerified,omitempty"`
	IdentityToken     *string `json:"identityToken,omitempty"`
	Nonce             *string `json:"nonce,omitempty"`
}

// OAuthLinkRequest defines model for OAuthLinkRequest.
type OAuthLinkRequest struct {
	// Credential Provider credential. Apple uses identityToken/authorizationCode/nonce. Kakao uses accessToken. dev* fields are accepted only when server dev OAuth is enabled.
	Credential OAuthCredential `json:"credential"`
	Provider   AuthProvider    `json:"provider"`
}

// OAuthLoginRequest defines model for OAuthLoginRequest.
type OAuthLoginRequest struct {
	// Credential Provider credential. Apple uses identityToken/authorizationCode/nonce. Kakao uses accessToken. dev* fields are accepted only when server dev OAuth is enabled.
	Credential OAuthCredential `json:"credential"`
	Device     *DeviceInfo     `json:"device,omitempty"`
	Provider   AuthProvider    `json:"provider"`
}

// ReadinessCheck defines model for ReadinessCheck.
type ReadinessCheck struct {
	Status ReadinessCheckStatus `json:"status"`
}

// ReadinessCheckStatus defines model for ReadinessCheck.Status.
type ReadinessCheckStatus string

// ReadinessChecks defines model for ReadinessChecks.
type ReadinessChecks struct {
	Database ReadinessCheck         `json:"database"`
	Metadata MetadataReadinessCheck `json:"metadata"`
}

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Checks ReadinessChecks         `json:"checks"`
	Status ReadinessResponseStatus `json:"status"`
}

// ReadinessResponseStatus defines model for ReadinessResponse.Status.
type ReadinessResponseStatus string

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// SupportedCurrency defines model for SupportedCurrency.
type SupportedCurrency string

// Trip defines model for Trip.
type Trip struct {
	CreatedAt       time.Time          `json:"createdAt"`
	CreatedBy       string             `json:"createdBy"`
	DefaultCurrency SupportedCurrency  `json:"defaultCurrency"`
	EndDate         openapi_types.Date `json:"endDate"`
	Id              string             `json:"id"`
	Name            string             `json:"name"`
	StartDate       openapi_types.Date `json:"startDate"`
	UpdatedAt       time.Time          `json:"updatedAt"`
}

// TripDay defines model for TripDay.
type TripDay struct {
	Date     openapi_types.Date `json:"date"`
	DayOrder int                `json:"dayOrder"`
}

// TripListItem defines model for TripListItem.
type TripListItem struct {
	CreatedAt        time.Time           `json:"createdAt"`
	DefaultCurrency  SupportedCurrency   `json:"defaultCurrency"`
	EndDate          openapi_types.Date  `json:"endDate"`
	Id               string              `json:"id"`
	JoinedAt         time.Time           `json:"joinedAt"`
	MyRole           TripParticipantRole `json:"myRole"`
	Name             string              `json:"name"`
	ParticipantCount int                 `json:"participantCount"`
	StartDate        openapi_types.Date  `json:"startDate"`
}

// TripParticipant defines model for TripParticipant.
type TripParticipant struct {
	DisplayName string              `json:"displayName"`
	Id          string              `json:"id"`
	JoinedAt    time.Time           `json:"joinedAt"`
	Role        TripParticipantRole `json:"role"`
	TripId      string              `json:"tripId"`
	UserId      string              `json:"userId"`
}

// TripParticipantRole defines model for TripParticipantRole.
type TripParticipantRole string

// TripParticipantSummary defines model for TripParticipantSummary.
type TripParticipantSummary struct {
	OverflowCount int      `json:"overflowCount"`
	PreviewNames  []string `json:"previewNames"`
	TotalCount    int      `json:"totalCount"`
}

// UpdateTripRequest defines model for UpdateTripRequest.
type UpdateTripRequest struct {
	DefaultCurrency *SupportedCurrency `json:"defaultCurrency,omitempty"`

	// EndDate End date in YYYY-MM-DD format. Must not be before the merged startDate.
	EndDate *openapi_types.Date `json:"endDate,omitempty"`
	Name    *string             `json:"name,omitempty"`

	// StartDate Start date in YYYY-MM-DD format. May be past, current, or future.
	StartDate *openapi_types.Date `json:"startDate,omitempty"`
}

// UpdateTripResponse defines model for UpdateTripResponse.
type UpdateTripResponse struct {
	Trip Trip `json:"trip"`
}

// LinkOAuthProviderJSONRequestBody defines body for LinkOAuthProvider for application/json ContentType.
type LinkOAuthProviderJSONRequestBody = OAuthLinkRequest

// LoginWithOAuthJSONRequestBody defines body for LoginWithOAuth for application/json ContentType.
type LoginWithOAuthJSONRequestBody = OAuthLoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenRequest

// CreateTripJSONRequestBody defines body for CreateTrip for application/json ContentType.
type CreateTripJSONRequestBody = CreateTripRequest

// UpdateTripJSONRequestBody defines body for UpdateTrip for application/json ContentType.
type UpdateTripJSONRequestBody = UpdateTripRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Revoke the current session
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Return the current user and linked providers
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Link an Apple or Kakao OAuth identity to the current user
	// (POST /auth/oauth/link)
	LinkOAuthProvider(w http.ResponseWriter, r *http.Request)
	// Login or sign up with Apple or Kakao OAuth
	// (POST /auth/oauth/login)
	LoginWithOAuth(w http.ResponseWriter, r *http.Request)
	// Rotate a refresh token and issue a new token pair
	// (POST /auth/token/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Check API health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Check API readiness
	// (GET /ready)
	GetReady(w http.ResponseWriter, r *http.Request)
	// List my trips
	// (GET /trips)
	ListTrips(w http.ResponseWriter, r *http.Request)
	// Create a trip
	// (POST /trips)
	CreateTrip(w http.ResponseWriter, r *http.Request)
	// Delete a trip
	// (DELETE /trips/{tripId})
	DeleteTrip(w http.ResponseWriter, r *http.Request, tripId string)
	// Get trip detail
	// (GET /trips/{tripId})
	GetTripDetail(w http.ResponseWriter, r *http.Request, tripId string)
	// Update trip basic information
	// (PATCH /trips/{tripId})
	UpdateTrip(w http.ResponseWriter, r *http.Request, tripId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Revoke the current session
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the current user and linked providers
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Link an Apple or Kakao OAuth identity to the current user
// (POST /auth/oauth/link)
func (_ Unimplemented) LinkOAuthProvider(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login or sign up with Apple or Kakao OAuth
// (POST /auth/oauth/login)
func (_ Unimplemented) LoginWithOAuth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rotate a refresh token and issue a new token pair
// (POST /auth/token/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check API health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check API readiness
// (GET /ready)
func (_ Unimplemented) GetReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List my trips
// (GET /trips)
func (_ Unimplemented) ListTrips(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a trip
// (POST /trips)
func (_ Unimplemented) CreateTrip(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a trip
// (DELETE /trips/{tripId})
func (_ Unimplemented) DeleteTrip(w http.ResponseWriter, r *http.Request, tripId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get trip detail
// (GET /trips/{tripId})
func (_ Unimplemented) GetTripDetail(w http.ResponseWriter, r *http.Request, tripId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update trip basic information
// (PATCH /trips/{tripId})
func (_ Unimplemented) UpdateTrip(w http.ResponseWriter, r *http.Request, tripId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LinkOAuthProvider operation middleware
func (siw *ServerInterfaceWrapper) LinkOAuthProvider(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LinkOAuthProvider(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoginWithOAuth operation middleware
func (siw *ServerInterfaceWrapper) LoginWithOAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginWithOAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTrips operation middleware
func (siw *ServerInterfaceWrapper) ListTrips(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrips(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTrip operation middleware
func (siw *ServerInterfaceWrapper) CreateTrip(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrip(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrip operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId string

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTripDetail operation middleware
func (siw *ServerInterfaceWrapper) GetTripDetail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId string

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTripDetail(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTrip operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrip(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tripId" -------------
	var tripId string

	err = runtime.BindStyledParameterWithOptions("simple", "tripId", chi.URLParam(r, "tripId"), &tripId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tripId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTrip(w, r, tripId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/oauth/link", wrapper.LinkOAuthProvider)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/oauth/login", wrapper.LoginWithOAuth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/token/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ready", wrapper.GetReady)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips", wrapper.ListTrips)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/trips", wrapper.CreateTrip)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/trips/{tripId}", wrapper.DeleteTrip)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trips/{tripId}", wrapper.GetTripDetail)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/trips/{tripId}", wrapper.UpdateTrip)
	})

	return r
}
