import { theme } from '../design/theme';

export const DAY_ITINERARY_EDIT_MEMO_INPUT_MIN_HEIGHT = theme.layout.controlHLg + theme.space[8];
export const DAY_ITINERARY_EDIT_SHEET_KEYBOARD_BOTTOM_PADDING = theme.space[5];
export const DAY_ITINERARY_EDIT_SHEET_KEYBOARD_MIN_CLEARANCE =
  DAY_ITINERARY_EDIT_MEMO_INPUT_MIN_HEIGHT + DAY_ITINERARY_EDIT_SHEET_KEYBOARD_BOTTOM_PADDING;
