// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: app_metadata.sql

package db

import (
	"context"
)

const getAppMetadataValue = `-- name: GetAppMetadataValue :one
SELECT value
FROM app_metadata
WHERE key = $1
`

func (q *Queries) GetAppMetadataValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getAppMetadataValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}
