// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeEventParticipantsByUserID = `-- name: AnonymizeEventParticipantsByUserID :exec
UPDATE event_participants participant
SET
  display_name = '탈퇴한 사용자',
  role = CASE WHEN participant.role = 'owner' THEN 'member' ELSE participant.role END
WHERE participant.user_id = $1::uuid
  AND EXISTS (
    SELECT 1
    FROM event_participants other_participant
    JOIN users other_user
      ON other_user.id = other_participant.user_id
     AND other_user.deleted_at IS NULL
    WHERE other_participant.event_id = participant.event_id
      AND other_participant.user_id <> $1::uuid
  )
`

func (q *Queries) AnonymizeEventParticipantsByUserID(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, anonymizeEventParticipantsByUserID, dollar_1)
	return err
}

const anonymizeMeetingMembersByUserID = `-- name: AnonymizeMeetingMembersByUserID :exec
UPDATE meeting_members member
SET
  display_name = '탈퇴한 사용자',
  role = CASE WHEN member.role = 'owner' THEN 'member' ELSE member.role END
WHERE member.user_id = $1::uuid
  AND EXISTS (
    SELECT 1
    FROM meeting_members other_member
    JOIN users other_user
      ON other_user.id = other_member.user_id
     AND other_user.deleted_at IS NULL
    WHERE other_member.meeting_id = member.meeting_id
      AND other_member.user_id <> $1::uuid
  )
`

func (q *Queries) AnonymizeMeetingMembersByUserID(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, anonymizeMeetingMembersByUserID, dollar_1)
	return err
}

const anonymizeTripParticipantsByUserID = `-- name: AnonymizeTripParticipantsByUserID :exec
UPDATE trip_participants participant
SET
  display_name = '탈퇴한 사용자',
  role = CASE WHEN participant.role = 'owner' THEN 'member' ELSE participant.role END
WHERE participant.user_id = $1::uuid
  AND EXISTS (
    SELECT 1
    FROM trip_participants other_participant
    JOIN users other_user
      ON other_user.id = other_participant.user_id
     AND other_user.deleted_at IS NULL
    WHERE other_participant.trip_id = participant.trip_id
      AND other_participant.user_id <> $1::uuid
  )
`

func (q *Queries) AnonymizeTripParticipantsByUserID(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, anonymizeTripParticipantsByUserID, dollar_1)
	return err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO auth_identities (
  user_id,
  provider,
  provider_subject,
  email,
  email_normalized,
  email_verified,
  display_name,
  avatar_url
) VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING
  id::text,
  user_id::text,
  provider,
  provider_subject,
  email,
  email_normalized,
  email_verified,
  display_name,
  avatar_url,
  created_at,
  updated_at
`

type CreateIdentityParams struct {
	Column1         pgtype.UUID
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	DisplayName     pgtype.Text
	AvatarUrl       pgtype.Text
}

type CreateIdentityRow struct {
	ID              string
	UserID          string
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	DisplayName     pgtype.Text
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (CreateIdentityRow, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.Column1,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.EmailNormalized,
		arg.EmailVerified,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i CreateIdentityRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions (
  user_id,
  refresh_token_hash,
  refresh_token_expires_at,
  last_used_at,
  device_name,
  platform,
  user_agent
) VALUES (
  $1::uuid,
  $2,
  $3,
  now(),
  $4,
  $5,
  $6
)
RETURNING
  id::text,
  user_id::text,
  refresh_token_hash,
  refresh_token_expires_at,
  revoked_at,
  last_used_at,
  rotated_at,
  device_name,
  platform,
  user_agent,
  created_at,
  updated_at
`

type CreateSessionParams struct {
	Column1               pgtype.UUID
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
}

type CreateSessionRow struct {
	ID                    string
	UserID                string
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	LastUsedAt            pgtype.Timestamptz
	RotatedAt             pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Column1,
		arg.RefreshTokenHash,
		arg.RefreshTokenExpiresAt,
		arg.DeviceName,
		arg.Platform,
		arg.UserAgent,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Platform,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  display_name,
  email,
  email_normalized,
  email_verified,
  avatar_url
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id::text,
  display_name,
  email,
  email_normalized,
  email_verified,
  avatar_url,
  created_at,
  updated_at
`

type CreateUserParams struct {
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
}

type CreateUserRow struct {
	ID              string
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DisplayName,
		arg.Email,
		arg.EmailNormalized,
		arg.EmailVerified,
		arg.AvatarUrl,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateActiveInvitesCreatedByUserID = `-- name: DeactivateActiveInvitesCreatedByUserID :exec
UPDATE trip_invites invite
SET deactivated_at = $2
WHERE invite.created_by = $1::uuid
  AND invite.deactivated_at IS NULL
  AND EXISTS (
    SELECT 1
    FROM trip_participants deleting_participant
    WHERE deleting_participant.trip_id = invite.trip_id
      AND deleting_participant.user_id = $1::uuid
  )
  AND EXISTS (
    SELECT 1
    FROM trip_participants other_participant
    JOIN users other_user
      ON other_user.id = other_participant.user_id
     AND other_user.deleted_at IS NULL
    WHERE other_participant.trip_id = invite.trip_id
      AND other_participant.user_id <> $1::uuid
  )
`

type DeactivateActiveInvitesCreatedByUserIDParams struct {
	Column1       pgtype.UUID
	DeactivatedAt pgtype.Timestamptz
}

func (q *Queries) DeactivateActiveInvitesCreatedByUserID(ctx context.Context, arg DeactivateActiveInvitesCreatedByUserIDParams) error {
	_, err := q.db.Exec(ctx, deactivateActiveInvitesCreatedByUserID, arg.Column1, arg.DeactivatedAt)
	return err
}

const deleteAuthIdentitiesByUserID = `-- name: DeleteAuthIdentitiesByUserID :exec
DELETE FROM auth_identities
WHERE user_id = $1::uuid
`

func (q *Queries) DeleteAuthIdentitiesByUserID(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthIdentitiesByUserID, dollar_1)
	return err
}

const deleteAuthSessionsByUserID = `-- name: DeleteAuthSessionsByUserID :exec
DELETE FROM auth_sessions
WHERE user_id = $1::uuid
`

func (q *Queries) DeleteAuthSessionsByUserID(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthSessionsByUserID, dollar_1)
	return err
}

const deleteSoloMeetingsByUserID = `-- name: DeleteSoloMeetingsByUserID :exec
DELETE FROM meetings meeting
WHERE meeting.id IN (
  SELECT deleting_member.meeting_id
  FROM meeting_members deleting_member
  WHERE deleting_member.user_id = $1::uuid
    AND NOT EXISTS (
      SELECT 1
      FROM meeting_members other_member
      JOIN users other_user
        ON other_user.id = other_member.user_id
       AND other_user.deleted_at IS NULL
      WHERE other_member.meeting_id = deleting_member.meeting_id
        AND other_member.user_id <> $1::uuid
    )
)
`

func (q *Queries) DeleteSoloMeetingsByUserID(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSoloMeetingsByUserID, dollar_1)
	return err
}

const deleteSoloTripsByUserID = `-- name: DeleteSoloTripsByUserID :exec
DELETE FROM trips trip
WHERE trip.id IN (
  SELECT deleting_participant.trip_id
  FROM trip_participants deleting_participant
  WHERE deleting_participant.user_id = $1::uuid
    AND NOT EXISTS (
      SELECT 1
      FROM trip_participants other_participant
      JOIN users other_user
        ON other_user.id = other_participant.user_id
       AND other_user.deleted_at IS NULL
      WHERE other_participant.trip_id = deleting_participant.trip_id
        AND other_participant.user_id <> $1::uuid
    )
)
`

func (q *Queries) DeleteSoloTripsByUserID(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSoloTripsByUserID, dollar_1)
	return err
}

const findIdentityByProviderSubject = `-- name: FindIdentityByProviderSubject :one
SELECT
  u.id::text AS user_id,
  u.display_name,
  u.email,
  u.email_normalized,
  u.email_verified,
  u.avatar_url,
  i.provider,
  i.provider_subject
FROM auth_identities i
JOIN users u ON u.id = i.user_id AND u.deleted_at IS NULL
WHERE i.provider = $1 AND i.provider_subject = $2
`

type FindIdentityByProviderSubjectParams struct {
	Provider        string
	ProviderSubject string
}

type FindIdentityByProviderSubjectRow struct {
	UserID          string
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	Provider        string
	ProviderSubject string
}

func (q *Queries) FindIdentityByProviderSubject(ctx context.Context, arg FindIdentityByProviderSubjectParams) (FindIdentityByProviderSubjectRow, error) {
	row := q.db.QueryRow(ctx, findIdentityByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i FindIdentityByProviderSubjectRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderSubject,
	)
	return i, err
}

const findSessionByRefreshTokenHash = `-- name: FindSessionByRefreshTokenHash :one
SELECT
  s.id::text AS id,
  s.user_id::text AS user_id,
  s.refresh_token_hash,
  s.refresh_token_expires_at,
  s.revoked_at,
  s.last_used_at,
  s.rotated_at,
  s.device_name,
  s.platform,
  s.user_agent,
  s.created_at,
  s.updated_at
FROM auth_sessions s
JOIN users u ON u.id = s.user_id AND u.deleted_at IS NULL
WHERE s.refresh_token_hash = $1
`

type FindSessionByRefreshTokenHashRow struct {
	ID                    string
	UserID                string
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	LastUsedAt            pgtype.Timestamptz
	RotatedAt             pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) FindSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (FindSessionByRefreshTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findSessionByRefreshTokenHash, refreshTokenHash)
	var i FindSessionByRefreshTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Platform,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByVerifiedIdentityEmail = `-- name: FindUserByVerifiedIdentityEmail :one
SELECT DISTINCT
  u.id::text,
  u.display_name,
  u.email,
  u.email_normalized,
  u.email_verified,
  u.avatar_url,
  u.created_at,
  u.updated_at
FROM auth_identities i
JOIN users u ON u.id = i.user_id AND u.deleted_at IS NULL
WHERE i.email_verified = true
  AND i.email_normalized = $1
LIMIT 1
`

type FindUserByVerifiedIdentityEmailRow struct {
	UID             string
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) FindUserByVerifiedIdentityEmail(ctx context.Context, emailNormalized pgtype.Text) (FindUserByVerifiedIdentityEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByVerifiedIdentityEmail, emailNormalized)
	var i FindUserByVerifiedIdentityEmailRow
	err := row.Scan(
		&i.UID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveUserForUpdate = `-- name: GetActiveUserForUpdate :one
SELECT id::text
FROM users
WHERE id = $1::uuid
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetActiveUserForUpdate(ctx context.Context, dollar_1 pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getActiveUserForUpdate, dollar_1)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
  s.id::text AS id,
  s.user_id::text AS user_id,
  s.refresh_token_hash,
  s.refresh_token_expires_at,
  s.revoked_at,
  s.last_used_at,
  s.rotated_at,
  s.device_name,
  s.platform,
  s.user_agent,
  s.created_at,
  s.updated_at
FROM auth_sessions s
JOIN users u ON u.id = s.user_id AND u.deleted_at IS NULL
WHERE s.id = $1::uuid
`

type GetSessionByIDRow struct {
	ID                    string
	UserID                string
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	LastUsedAt            pgtype.Timestamptz
	RotatedAt             pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) GetSessionByID(ctx context.Context, dollar_1 pgtype.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, dollar_1)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Platform,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  id::text,
  display_name,
  email,
  email_normalized,
  email_verified,
  avatar_url,
  created_at,
  updated_at
FROM users
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID              string
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, dollar_1 pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, dollar_1)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProvidersByUserID = `-- name: ListProvidersByUserID :many
SELECT provider
FROM auth_identities
WHERE user_id = $1::uuid
ORDER BY provider
`

func (q *Queries) ListProvidersByUserID(ctx context.Context, dollar_1 pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listProvidersByUserID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserDeleted = `-- name: MarkUserDeleted :exec
UPDATE users
SET
  display_name = '탈퇴한 사용자',
  email = NULL,
  email_normalized = NULL,
  email_verified = false,
  avatar_url = NULL,
  deleted_at = $2,
  updated_at = $2
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

type MarkUserDeletedParams struct {
	Column1   pgtype.UUID
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) MarkUserDeleted(ctx context.Context, arg MarkUserDeletedParams) error {
	_, err := q.db.Exec(ctx, markUserDeleted, arg.Column1, arg.DeletedAt)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions
SET
  revoked_at = COALESCE(revoked_at, now()),
  updated_at = now()
WHERE id = $1::uuid
`

func (q *Queries) RevokeSession(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, dollar_1)
	return err
}

const rotateSessionRefreshToken = `-- name: RotateSessionRefreshToken :one
UPDATE auth_sessions
SET
  refresh_token_hash = $2,
  refresh_token_expires_at = $3,
  last_used_at = now(),
  rotated_at = now(),
  updated_at = now()
WHERE id = $1::uuid
  AND revoked_at IS NULL
RETURNING
  id::text,
  user_id::text,
  refresh_token_hash,
  refresh_token_expires_at,
  revoked_at,
  last_used_at,
  rotated_at,
  device_name,
  platform,
  user_agent,
  created_at,
  updated_at
`

type RotateSessionRefreshTokenParams struct {
	Column1               pgtype.UUID
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
}

type RotateSessionRefreshTokenRow struct {
	ID                    string
	UserID                string
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	LastUsedAt            pgtype.Timestamptz
	RotatedAt             pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) RotateSessionRefreshToken(ctx context.Context, arg RotateSessionRefreshTokenParams) (RotateSessionRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, rotateSessionRefreshToken, arg.Column1, arg.RefreshTokenHash, arg.RefreshTokenExpiresAt)
	var i RotateSessionRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Platform,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transferOwnedSharedEventsForAccountDeletion = `-- name: TransferOwnedSharedEventsForAccountDeletion :exec
WITH retained_owned_events AS (
  SELECT e.id AS event_id
  FROM events e
  JOIN event_participants deleting_participant
    ON deleting_participant.event_id = e.id
   AND deleting_participant.user_id = $1::uuid
   AND deleting_participant.role = 'owner'
  WHERE EXISTS (
    SELECT 1
    FROM event_participants other_participant
    JOIN users other_user
      ON other_user.id = other_participant.user_id
     AND other_user.deleted_at IS NULL
    WHERE other_participant.event_id = e.id
      AND other_participant.user_id <> $1::uuid
  )
), successor_participants AS (
  SELECT DISTINCT ON (participant.event_id)
    participant.event_id,
    participant.user_id
  FROM event_participants participant
  JOIN retained_owned_events retained
    ON retained.event_id = participant.event_id
  JOIN users successor_user
    ON successor_user.id = participant.user_id
   AND successor_user.deleted_at IS NULL
  WHERE participant.user_id <> $1::uuid
  ORDER BY participant.event_id, participant.joined_at ASC, participant.id ASC
), updated_participants AS (
  UPDATE event_participants participant
  SET role = 'owner'
  FROM successor_participants successor
  WHERE participant.event_id = successor.event_id
    AND participant.user_id = successor.user_id
  RETURNING participant.event_id, participant.user_id
)
UPDATE events event
SET
  created_by = updated_participant.user_id,
  updated_at = $2
FROM updated_participants updated_participant
WHERE event.id = updated_participant.event_id
`

type TransferOwnedSharedEventsForAccountDeletionParams struct {
	Column1   pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) TransferOwnedSharedEventsForAccountDeletion(ctx context.Context, arg TransferOwnedSharedEventsForAccountDeletionParams) error {
	_, err := q.db.Exec(ctx, transferOwnedSharedEventsForAccountDeletion, arg.Column1, arg.UpdatedAt)
	return err
}

const transferOwnedSharedMeetingsForAccountDeletion = `-- name: TransferOwnedSharedMeetingsForAccountDeletion :exec
WITH retained_owned_meetings AS (
  SELECT m.id AS meeting_id
  FROM meetings m
  JOIN meeting_members deleting_member
    ON deleting_member.meeting_id = m.id
   AND deleting_member.user_id = $1::uuid
   AND deleting_member.role = 'owner'
  WHERE EXISTS (
    SELECT 1
    FROM meeting_members other_member
    JOIN users other_user
      ON other_user.id = other_member.user_id
     AND other_user.deleted_at IS NULL
    WHERE other_member.meeting_id = m.id
      AND other_member.user_id <> $1::uuid
  )
), successor_members AS (
  SELECT DISTINCT ON (member.meeting_id)
    member.meeting_id,
    member.user_id
  FROM meeting_members member
  JOIN retained_owned_meetings retained
    ON retained.meeting_id = member.meeting_id
  JOIN users successor_user
    ON successor_user.id = member.user_id
   AND successor_user.deleted_at IS NULL
  WHERE member.user_id <> $1::uuid
  ORDER BY member.meeting_id, member.joined_at ASC, member.id ASC
), updated_members AS (
  UPDATE meeting_members member
  SET role = 'owner'
  FROM successor_members successor
  WHERE member.meeting_id = successor.meeting_id
    AND member.user_id = successor.user_id
  RETURNING member.meeting_id, member.user_id
)
UPDATE meetings meeting
SET
  created_by = updated_member.user_id,
  updated_at = $2
FROM updated_members updated_member
WHERE meeting.id = updated_member.meeting_id
`

type TransferOwnedSharedMeetingsForAccountDeletionParams struct {
	Column1   pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) TransferOwnedSharedMeetingsForAccountDeletion(ctx context.Context, arg TransferOwnedSharedMeetingsForAccountDeletionParams) error {
	_, err := q.db.Exec(ctx, transferOwnedSharedMeetingsForAccountDeletion, arg.Column1, arg.UpdatedAt)
	return err
}

const transferOwnedSharedTripsForAccountDeletion = `-- name: TransferOwnedSharedTripsForAccountDeletion :exec
WITH retained_owned_trips AS (
  SELECT t.id AS trip_id
  FROM trips t
  JOIN trip_participants deleting_participant
    ON deleting_participant.trip_id = t.id
   AND deleting_participant.user_id = $1::uuid
   AND deleting_participant.role = 'owner'
  WHERE EXISTS (
    SELECT 1
    FROM trip_participants other_participant
    JOIN users other_user
      ON other_user.id = other_participant.user_id
     AND other_user.deleted_at IS NULL
    WHERE other_participant.trip_id = t.id
      AND other_participant.user_id <> $1::uuid
  )
), successor_participants AS (
  SELECT DISTINCT ON (participant.trip_id)
    participant.trip_id,
    participant.user_id
  FROM trip_participants participant
  JOIN retained_owned_trips retained
    ON retained.trip_id = participant.trip_id
  JOIN users successor_user
    ON successor_user.id = participant.user_id
   AND successor_user.deleted_at IS NULL
  WHERE participant.user_id <> $1::uuid
  ORDER BY participant.trip_id, participant.joined_at ASC, participant.id ASC
), updated_participants AS (
  UPDATE trip_participants participant
  SET role = 'owner'
  FROM successor_participants successor
  WHERE participant.trip_id = successor.trip_id
    AND participant.user_id = successor.user_id
  RETURNING participant.trip_id, participant.user_id
)
UPDATE trips trip
SET
  created_by = updated_participant.user_id,
  updated_at = $2
FROM updated_participants updated_participant
WHERE trip.id = updated_participant.trip_id
`

type TransferOwnedSharedTripsForAccountDeletionParams struct {
	Column1   pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) TransferOwnedSharedTripsForAccountDeletion(ctx context.Context, arg TransferOwnedSharedTripsForAccountDeletionParams) error {
	_, err := q.db.Exec(ctx, transferOwnedSharedTripsForAccountDeletion, arg.Column1, arg.UpdatedAt)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET
  display_name = $2,
  updated_at = now()
WHERE id = $1::uuid
  AND deleted_at IS NULL
RETURNING
  id::text,
  display_name,
  email,
  email_normalized,
  email_verified,
  avatar_url,
  created_at,
  updated_at
`

type UpdateUserDisplayNameParams struct {
	Column1     pgtype.UUID
	DisplayName string
}

type UpdateUserDisplayNameRow struct {
	ID              string
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (UpdateUserDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.Column1, arg.DisplayName)
	var i UpdateUserDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
