// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO auth_identities (
  user_id,
  provider,
  provider_subject,
  email,
  email_normalized,
  email_verified,
  display_name,
  avatar_url
) VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING
  id::text,
  user_id::text,
  provider,
  provider_subject,
  email,
  email_normalized,
  email_verified,
  display_name,
  avatar_url,
  created_at,
  updated_at
`

type CreateIdentityParams struct {
	Column1         pgtype.UUID
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	DisplayName     pgtype.Text
	AvatarUrl       pgtype.Text
}

type CreateIdentityRow struct {
	ID              string
	UserID          string
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	DisplayName     pgtype.Text
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (CreateIdentityRow, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.Column1,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.EmailNormalized,
		arg.EmailVerified,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i CreateIdentityRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions (
  user_id,
  refresh_token_hash,
  refresh_token_expires_at,
  last_used_at,
  device_name,
  platform,
  user_agent
) VALUES (
  $1::uuid,
  $2,
  $3,
  now(),
  $4,
  $5,
  $6
)
RETURNING
  id::text,
  user_id::text,
  refresh_token_hash,
  refresh_token_expires_at,
  revoked_at,
  last_used_at,
  rotated_at,
  device_name,
  platform,
  user_agent,
  created_at,
  updated_at
`

type CreateSessionParams struct {
	Column1               pgtype.UUID
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
}

type CreateSessionRow struct {
	ID                    string
	UserID                string
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	LastUsedAt            pgtype.Timestamptz
	RotatedAt             pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Column1,
		arg.RefreshTokenHash,
		arg.RefreshTokenExpiresAt,
		arg.DeviceName,
		arg.Platform,
		arg.UserAgent,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Platform,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  display_name,
  email,
  email_normalized,
  email_verified,
  avatar_url
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id::text,
  display_name,
  email,
  email_normalized,
  email_verified,
  avatar_url,
  created_at,
  updated_at
`

type CreateUserParams struct {
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
}

type CreateUserRow struct {
	ID              string
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DisplayName,
		arg.Email,
		arg.EmailNormalized,
		arg.EmailVerified,
		arg.AvatarUrl,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findIdentityByProviderSubject = `-- name: FindIdentityByProviderSubject :one
SELECT
  u.id::text AS user_id,
  u.display_name,
  u.email,
  u.email_normalized,
  u.email_verified,
  u.avatar_url,
  i.provider,
  i.provider_subject
FROM auth_identities i
JOIN users u ON u.id = i.user_id
WHERE i.provider = $1 AND i.provider_subject = $2
`

type FindIdentityByProviderSubjectParams struct {
	Provider        string
	ProviderSubject string
}

type FindIdentityByProviderSubjectRow struct {
	UserID          string
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	Provider        string
	ProviderSubject string
}

func (q *Queries) FindIdentityByProviderSubject(ctx context.Context, arg FindIdentityByProviderSubjectParams) (FindIdentityByProviderSubjectRow, error) {
	row := q.db.QueryRow(ctx, findIdentityByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i FindIdentityByProviderSubjectRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderSubject,
	)
	return i, err
}

const findSessionByRefreshTokenHash = `-- name: FindSessionByRefreshTokenHash :one
SELECT
  id::text,
  user_id::text,
  refresh_token_hash,
  refresh_token_expires_at,
  revoked_at,
  last_used_at,
  rotated_at,
  device_name,
  platform,
  user_agent,
  created_at,
  updated_at
FROM auth_sessions
WHERE refresh_token_hash = $1
`

type FindSessionByRefreshTokenHashRow struct {
	ID                    string
	UserID                string
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	LastUsedAt            pgtype.Timestamptz
	RotatedAt             pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) FindSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (FindSessionByRefreshTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findSessionByRefreshTokenHash, refreshTokenHash)
	var i FindSessionByRefreshTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Platform,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByVerifiedIdentityEmail = `-- name: FindUserByVerifiedIdentityEmail :one
SELECT DISTINCT
  u.id::text,
  u.display_name,
  u.email,
  u.email_normalized,
  u.email_verified,
  u.avatar_url,
  u.created_at,
  u.updated_at
FROM auth_identities i
JOIN users u ON u.id = i.user_id
WHERE i.email_verified = true
  AND i.email_normalized = $1
LIMIT 1
`

type FindUserByVerifiedIdentityEmailRow struct {
	UID             string
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) FindUserByVerifiedIdentityEmail(ctx context.Context, emailNormalized pgtype.Text) (FindUserByVerifiedIdentityEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByVerifiedIdentityEmail, emailNormalized)
	var i FindUserByVerifiedIdentityEmailRow
	err := row.Scan(
		&i.UID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
  id::text,
  user_id::text,
  refresh_token_hash,
  refresh_token_expires_at,
  revoked_at,
  last_used_at,
  rotated_at,
  device_name,
  platform,
  user_agent,
  created_at,
  updated_at
FROM auth_sessions
WHERE id = $1::uuid
`

type GetSessionByIDRow struct {
	ID                    string
	UserID                string
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	LastUsedAt            pgtype.Timestamptz
	RotatedAt             pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) GetSessionByID(ctx context.Context, dollar_1 pgtype.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, dollar_1)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Platform,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  id::text,
  display_name,
  email,
  email_normalized,
  email_verified,
  avatar_url,
  created_at,
  updated_at
FROM users
WHERE id = $1::uuid
`

type GetUserByIDRow struct {
	ID              string
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, dollar_1 pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, dollar_1)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProvidersByUserID = `-- name: ListProvidersByUserID :many
SELECT provider
FROM auth_identities
WHERE user_id = $1::uuid
ORDER BY provider
`

func (q *Queries) ListProvidersByUserID(ctx context.Context, dollar_1 pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listProvidersByUserID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider string
		if err := rows.Scan(&provider); err != nil {
			return nil, err
		}
		items = append(items, provider)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions
SET
  revoked_at = COALESCE(revoked_at, now()),
  updated_at = now()
WHERE id = $1::uuid
`

func (q *Queries) RevokeSession(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, dollar_1)
	return err
}

const rotateSessionRefreshToken = `-- name: RotateSessionRefreshToken :one
UPDATE auth_sessions
SET
  refresh_token_hash = $2,
  refresh_token_expires_at = $3,
  last_used_at = now(),
  rotated_at = now(),
  updated_at = now()
WHERE id = $1::uuid
  AND revoked_at IS NULL
RETURNING
  id::text,
  user_id::text,
  refresh_token_hash,
  refresh_token_expires_at,
  revoked_at,
  last_used_at,
  rotated_at,
  device_name,
  platform,
  user_agent,
  created_at,
  updated_at
`

type RotateSessionRefreshTokenParams struct {
	Column1               pgtype.UUID
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
}

type RotateSessionRefreshTokenRow struct {
	ID                    string
	UserID                string
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	LastUsedAt            pgtype.Timestamptz
	RotatedAt             pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) RotateSessionRefreshToken(ctx context.Context, arg RotateSessionRefreshTokenParams) (RotateSessionRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, rotateSessionRefreshToken, arg.Column1, arg.RefreshTokenHash, arg.RefreshTokenExpiresAt)
	var i RotateSessionRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.RefreshTokenExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Platform,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET
  display_name = $2,
  updated_at = now()
WHERE id = $1::uuid
RETURNING
  id::text,
  display_name,
  email,
  email_normalized,
  email_verified,
  avatar_url,
  created_at,
  updated_at
`

type UpdateUserDisplayNameParams struct {
	Column1     pgtype.UUID
	DisplayName string
}

type UpdateUserDisplayNameRow struct {
	ID              string
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (UpdateUserDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.Column1, arg.DisplayName)
	var i UpdateUserDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
