// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuickExpensePayerParticipant = `-- name: GetQuickExpensePayerParticipant :one
SELECT
  id::text,
  display_name,
  joined_at
FROM trip_participants
WHERE trip_id = $1::uuid
  AND id = $2::uuid
`

type GetQuickExpensePayerParticipantParams struct {
	TripID             pgtype.UUID
	PayerParticipantID pgtype.UUID
}

type GetQuickExpensePayerParticipantRow struct {
	ID          string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) GetQuickExpensePayerParticipant(ctx context.Context, arg GetQuickExpensePayerParticipantParams) (GetQuickExpensePayerParticipantRow, error) {
	row := q.db.QueryRow(ctx, getQuickExpensePayerParticipant, arg.TripID, arg.PayerParticipantID)
	var i GetQuickExpensePayerParticipantRow
	err := row.Scan(&i.ID, &i.DisplayName, &i.JoinedAt)
	return i, err
}

const getQuickExpenseScheduleItem = `-- name: GetQuickExpenseScheduleItem :one
SELECT
  si.id::text AS schedule_item_id,
  si.trip_day_id::text AS trip_day_id,
  td.date AS trip_day_date,
  tp.id::text AS trip_place_id,
  tp.name AS place_name,
  tp.place_type,
  tp.address AS place_address
FROM schedule_items si
JOIN trip_days td
  ON td.id = si.trip_day_id
 AND td.trip_id = si.trip_id
 AND td.deleted_at IS NULL
JOIN trip_places tp
  ON tp.id = si.trip_place_id
 AND tp.trip_id = si.trip_id
WHERE si.trip_id = $1::uuid
  AND si.trip_day_id = $2::uuid
  AND si.id = $3::uuid
  AND si.deleted_at IS NULL
`

type GetQuickExpenseScheduleItemParams struct {
	TripID         pgtype.UUID
	TripDayID      pgtype.UUID
	ScheduleItemID pgtype.UUID
}

type GetQuickExpenseScheduleItemRow struct {
	ScheduleItemID string
	TripDayID      string
	TripDayDate    pgtype.Date
	TripPlaceID    string
	PlaceName      string
	PlaceType      string
	PlaceAddress   string
}

func (q *Queries) GetQuickExpenseScheduleItem(ctx context.Context, arg GetQuickExpenseScheduleItemParams) (GetQuickExpenseScheduleItemRow, error) {
	row := q.db.QueryRow(ctx, getQuickExpenseScheduleItem, arg.TripID, arg.TripDayID, arg.ScheduleItemID)
	var i GetQuickExpenseScheduleItemRow
	err := row.Scan(
		&i.ScheduleItemID,
		&i.TripDayID,
		&i.TripDayDate,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceType,
		&i.PlaceAddress,
	)
	return i, err
}

const getTripDefaultCurrencyForQuickExpense = `-- name: GetTripDefaultCurrencyForQuickExpense :one
SELECT
  id::text,
  default_currency
FROM trips
WHERE id = $1::uuid
`

type GetTripDefaultCurrencyForQuickExpenseRow struct {
	ID              string
	DefaultCurrency string
}

func (q *Queries) GetTripDefaultCurrencyForQuickExpense(ctx context.Context, tripID pgtype.UUID) (GetTripDefaultCurrencyForQuickExpenseRow, error) {
	row := q.db.QueryRow(ctx, getTripDefaultCurrencyForQuickExpense, tripID)
	var i GetTripDefaultCurrencyForQuickExpenseRow
	err := row.Scan(&i.ID, &i.DefaultCurrency)
	return i, err
}

const insertExpense = `-- name: InsertExpense :one
INSERT INTO expenses (
  trip_id,
  anchor_type,
  trip_day_id,
  schedule_item_id,
  expense_date,
  trip_place_id,
  place_name,
  place_address,
  place_type,
  amount_minor,
  currency,
  payer_participant_id,
  payer_display_name,
  created_by
) VALUES (
  $1::uuid,
  $2,
  $3::uuid,
  $4::uuid,
  $5,
  $6::uuid,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12::uuid,
  $13,
  $14::uuid
)
RETURNING
  id::text,
  trip_id::text,
  anchor_type,
  trip_day_id::text,
  schedule_item_id::text,
  expense_date,
  trip_place_id::text,
  place_name,
  place_address,
  place_type,
  amount_minor,
  currency,
  payer_participant_id::text,
  payer_display_name,
  created_at
`

type InsertExpenseParams struct {
	TripID             pgtype.UUID
	AnchorType         string
	TripDayID          pgtype.UUID
	ScheduleItemID     pgtype.UUID
	ExpenseDate        pgtype.Date
	TripPlaceID        pgtype.UUID
	PlaceName          string
	PlaceAddress       string
	PlaceType          string
	AmountMinor        int64
	Currency           string
	PayerParticipantID pgtype.UUID
	PayerDisplayName   string
	CreatedBy          pgtype.UUID
}

type InsertExpenseRow struct {
	ID                 string
	TripID             string
	AnchorType         string
	TripDayID          string
	ScheduleItemID     string
	ExpenseDate        pgtype.Date
	TripPlaceID        string
	PlaceName          string
	PlaceAddress       string
	PlaceType          string
	AmountMinor        int64
	Currency           string
	PayerParticipantID string
	PayerDisplayName   string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) InsertExpense(ctx context.Context, arg InsertExpenseParams) (InsertExpenseRow, error) {
	row := q.db.QueryRow(ctx, insertExpense,
		arg.TripID,
		arg.AnchorType,
		arg.TripDayID,
		arg.ScheduleItemID,
		arg.ExpenseDate,
		arg.TripPlaceID,
		arg.PlaceName,
		arg.PlaceAddress,
		arg.PlaceType,
		arg.AmountMinor,
		arg.Currency,
		arg.PayerParticipantID,
		arg.PayerDisplayName,
		arg.CreatedBy,
	)
	var i InsertExpenseRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.AnchorType,
		&i.TripDayID,
		&i.ScheduleItemID,
		&i.ExpenseDate,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceAddress,
		&i.PlaceType,
		&i.AmountMinor,
		&i.Currency,
		&i.PayerParticipantID,
		&i.PayerDisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const insertExpenseSplit = `-- name: InsertExpenseSplit :one
INSERT INTO expense_splits (
  expense_id,
  participant_id,
  participant_display_name,
  amount_minor,
  split_order
) VALUES (
  $1::uuid,
  $2::uuid,
  $3,
  $4,
  $5
)
RETURNING
  id::text,
  expense_id::text,
  participant_id::text,
  participant_display_name,
  amount_minor,
  split_order
`

type InsertExpenseSplitParams struct {
	ExpenseID              pgtype.UUID
	ParticipantID          pgtype.UUID
	ParticipantDisplayName string
	AmountMinor            int64
	SplitOrder             int32
}

type InsertExpenseSplitRow struct {
	ID                     string
	ExpenseID              string
	ParticipantID          string
	ParticipantDisplayName string
	AmountMinor            int64
	SplitOrder             int32
}

func (q *Queries) InsertExpenseSplit(ctx context.Context, arg InsertExpenseSplitParams) (InsertExpenseSplitRow, error) {
	row := q.db.QueryRow(ctx, insertExpenseSplit,
		arg.ExpenseID,
		arg.ParticipantID,
		arg.ParticipantDisplayName,
		arg.AmountMinor,
		arg.SplitOrder,
	)
	var i InsertExpenseSplitRow
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.ParticipantID,
		&i.ParticipantDisplayName,
		&i.AmountMinor,
		&i.SplitOrder,
	)
	return i, err
}

const listDayExpenseSplitsByExpenseIDs = `-- name: ListDayExpenseSplitsByExpenseIDs :many
SELECT
  expense_id::text,
  split_order,
  participant_display_name,
  amount_minor
FROM expense_splits
WHERE expense_id = ANY($1::uuid[])
ORDER BY expense_id ASC, split_order ASC
`

type ListDayExpenseSplitsByExpenseIDsRow struct {
	ExpenseID              string
	SplitOrder             int32
	ParticipantDisplayName string
	AmountMinor            int64
}

func (q *Queries) ListDayExpenseSplitsByExpenseIDs(ctx context.Context, expenseIds []pgtype.UUID) ([]ListDayExpenseSplitsByExpenseIDsRow, error) {
	rows, err := q.db.Query(ctx, listDayExpenseSplitsByExpenseIDs, expenseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDayExpenseSplitsByExpenseIDsRow
	for rows.Next() {
		var i ListDayExpenseSplitsByExpenseIDsRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.SplitOrder,
			&i.ParticipantDisplayName,
			&i.AmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDayExpensesByTripDay = `-- name: ListDayExpensesByTripDay :many
SELECT
  id::text,
  place_name,
  place_address,
  place_type,
  amount_minor,
  currency,
  payer_display_name,
  created_at
FROM expenses
WHERE trip_id = $1::uuid
  AND trip_day_id = $2::uuid
  AND anchor_type IN ('trip_day', 'schedule_item')
ORDER BY created_at DESC, id DESC
`

type ListDayExpensesByTripDayParams struct {
	TripID    pgtype.UUID
	TripDayID pgtype.UUID
}

type ListDayExpensesByTripDayRow struct {
	ID               string
	PlaceName        string
	PlaceAddress     string
	PlaceType        string
	AmountMinor      int64
	Currency         string
	PayerDisplayName string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListDayExpensesByTripDay(ctx context.Context, arg ListDayExpensesByTripDayParams) ([]ListDayExpensesByTripDayRow, error) {
	rows, err := q.db.Query(ctx, listDayExpensesByTripDay, arg.TripID, arg.TripDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDayExpensesByTripDayRow
	for rows.Next() {
		var i ListDayExpensesByTripDayRow
		if err := rows.Scan(
			&i.ID,
			&i.PlaceName,
			&i.PlaceAddress,
			&i.PlaceType,
			&i.AmountMinor,
			&i.Currency,
			&i.PayerDisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuickExpenseSplitParticipants = `-- name: ListQuickExpenseSplitParticipants :many
SELECT
  id::text,
  display_name,
  joined_at
FROM trip_participants
WHERE trip_id = $1::uuid
ORDER BY joined_at ASC, id ASC
`

type ListQuickExpenseSplitParticipantsRow struct {
	ID          string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) ListQuickExpenseSplitParticipants(ctx context.Context, tripID pgtype.UUID) ([]ListQuickExpenseSplitParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listQuickExpenseSplitParticipants, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuickExpenseSplitParticipantsRow
	for rows.Next() {
		var i ListQuickExpenseSplitParticipantsRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
