// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpenseByTripDayAndID = `-- name: DeleteExpenseByTripDayAndID :one
DELETE FROM expenses
WHERE trip_id = $1::uuid
  AND trip_day_id = $2::uuid
  AND id = $3::uuid
  AND anchor_type IN ('trip_day', 'schedule_item')
RETURNING id::text
`

type DeleteExpenseByTripDayAndIDParams struct {
	TripID    pgtype.UUID
	TripDayID pgtype.UUID
	ExpenseID pgtype.UUID
}

func (q *Queries) DeleteExpenseByTripDayAndID(ctx context.Context, arg DeleteExpenseByTripDayAndIDParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteExpenseByTripDayAndID, arg.TripID, arg.TripDayID, arg.ExpenseID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteExpenseSplitsByExpenseID = `-- name: DeleteExpenseSplitsByExpenseID :exec
DELETE FROM expense_splits
WHERE expense_id = $1::uuid
`

func (q *Queries) DeleteExpenseSplitsByExpenseID(ctx context.Context, expenseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseSplitsByExpenseID, expenseID)
	return err
}

const getExpenseByTripDayAndID = `-- name: GetExpenseByTripDayAndID :one
SELECT
  e.id::text AS id,
  e.trip_id::text AS trip_id,
  e.anchor_type,
  COALESCE(e.trip_day_id::text, '')::text AS trip_day_id,
  COALESCE(e.schedule_item_id::text, '')::text AS schedule_item_id,
  e.expense_date,
  COALESCE(live_place.name, e.place_name, '지출')::text AS display_title,
  COALESCE(live_place.id::text, e.trip_place_id::text, '')::text AS trip_place_id,
  COALESCE(live_place.name, e.place_name, '')::text AS place_name,
  COALESCE(live_place.address, e.place_address, '')::text AS place_address,
  COALESCE(live_place.place_type, e.place_type, '')::text AS place_type,
  CASE
    WHEN live_place.id IS NOT NULL THEN 'live'
    WHEN e.place_name IS NOT NULL THEN 'fallback'
    ELSE ''
  END::text AS place_source,
  e.amount_minor,
  e.currency,
  COALESCE(payer.id::text, e.payer_participant_id::text, '')::text AS payer_participant_id,
  COALESCE(payer.display_name, e.payer_display_name, '여행자')::text AS payer_display_name,
  CASE
    WHEN payer.id IS NOT NULL THEN 'live'
    ELSE 'fallback'
  END::text AS payer_source,
  e.memo,
  e.split_policy,
  e.created_at
FROM expenses e
LEFT JOIN schedule_items si
  ON e.anchor_type = 'schedule_item'
 AND si.id = e.schedule_item_id
 AND si.trip_day_id = e.trip_day_id
 AND si.trip_id = e.trip_id
 AND si.deleted_at IS NULL
LEFT JOIN trip_places live_place
  ON live_place.id = si.trip_place_id
 AND live_place.trip_id = e.trip_id
LEFT JOIN trip_participants payer
  ON payer.id = e.payer_participant_id
 AND payer.trip_id = e.trip_id
WHERE e.trip_id = $1::uuid
  AND e.trip_day_id = $2::uuid
  AND e.id = $3::uuid
  AND e.anchor_type IN ('trip_day', 'schedule_item')
`

type GetExpenseByTripDayAndIDParams struct {
	TripID    pgtype.UUID
	TripDayID pgtype.UUID
	ExpenseID pgtype.UUID
}

type GetExpenseByTripDayAndIDRow struct {
	ID                 string
	TripID             string
	AnchorType         string
	TripDayID          string
	ScheduleItemID     string
	ExpenseDate        pgtype.Date
	DisplayTitle       string
	TripPlaceID        string
	PlaceName          string
	PlaceAddress       string
	PlaceType          string
	PlaceSource        string
	AmountMinor        int64
	Currency           string
	PayerParticipantID string
	PayerDisplayName   string
	PayerSource        string
	Memo               pgtype.Text
	SplitPolicy        string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) GetExpenseByTripDayAndID(ctx context.Context, arg GetExpenseByTripDayAndIDParams) (GetExpenseByTripDayAndIDRow, error) {
	row := q.db.QueryRow(ctx, getExpenseByTripDayAndID, arg.TripID, arg.TripDayID, arg.ExpenseID)
	var i GetExpenseByTripDayAndIDRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.AnchorType,
		&i.TripDayID,
		&i.ScheduleItemID,
		&i.ExpenseDate,
		&i.DisplayTitle,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceAddress,
		&i.PlaceType,
		&i.PlaceSource,
		&i.AmountMinor,
		&i.Currency,
		&i.PayerParticipantID,
		&i.PayerDisplayName,
		&i.PayerSource,
		&i.Memo,
		&i.SplitPolicy,
		&i.CreatedAt,
	)
	return i, err
}

const getQuickExpensePayerParticipant = `-- name: GetQuickExpensePayerParticipant :one
SELECT
  id::text,
  display_name,
  joined_at
FROM trip_participants
WHERE trip_id = $1::uuid
  AND id = $2::uuid
`

type GetQuickExpensePayerParticipantParams struct {
	TripID             pgtype.UUID
	PayerParticipantID pgtype.UUID
}

type GetQuickExpensePayerParticipantRow struct {
	ID          string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) GetQuickExpensePayerParticipant(ctx context.Context, arg GetQuickExpensePayerParticipantParams) (GetQuickExpensePayerParticipantRow, error) {
	row := q.db.QueryRow(ctx, getQuickExpensePayerParticipant, arg.TripID, arg.PayerParticipantID)
	var i GetQuickExpensePayerParticipantRow
	err := row.Scan(&i.ID, &i.DisplayName, &i.JoinedAt)
	return i, err
}

const getQuickExpenseScheduleItem = `-- name: GetQuickExpenseScheduleItem :one
SELECT
  si.id::text AS schedule_item_id,
  si.trip_day_id::text AS trip_day_id,
  td.date AS trip_day_date,
  tp.id::text AS trip_place_id,
  tp.name AS place_name,
  tp.place_type,
  tp.address AS place_address
FROM schedule_items si
JOIN trip_days td
  ON td.id = si.trip_day_id
 AND td.trip_id = si.trip_id
 AND td.deleted_at IS NULL
JOIN trip_places tp
  ON tp.id = si.trip_place_id
 AND tp.trip_id = si.trip_id
WHERE si.trip_id = $1::uuid
  AND si.trip_day_id = $2::uuid
  AND si.id = $3::uuid
  AND si.deleted_at IS NULL
`

type GetQuickExpenseScheduleItemParams struct {
	TripID         pgtype.UUID
	TripDayID      pgtype.UUID
	ScheduleItemID pgtype.UUID
}

type GetQuickExpenseScheduleItemRow struct {
	ScheduleItemID string
	TripDayID      string
	TripDayDate    pgtype.Date
	TripPlaceID    string
	PlaceName      string
	PlaceType      string
	PlaceAddress   string
}

func (q *Queries) GetQuickExpenseScheduleItem(ctx context.Context, arg GetQuickExpenseScheduleItemParams) (GetQuickExpenseScheduleItemRow, error) {
	row := q.db.QueryRow(ctx, getQuickExpenseScheduleItem, arg.TripID, arg.TripDayID, arg.ScheduleItemID)
	var i GetQuickExpenseScheduleItemRow
	err := row.Scan(
		&i.ScheduleItemID,
		&i.TripDayID,
		&i.TripDayDate,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceType,
		&i.PlaceAddress,
	)
	return i, err
}

const getTripDefaultCurrencyForQuickExpense = `-- name: GetTripDefaultCurrencyForQuickExpense :one
SELECT
  id::text,
  default_currency
FROM trips
WHERE id = $1::uuid
`

type GetTripDefaultCurrencyForQuickExpenseRow struct {
	ID              string
	DefaultCurrency string
}

func (q *Queries) GetTripDefaultCurrencyForQuickExpense(ctx context.Context, tripID pgtype.UUID) (GetTripDefaultCurrencyForQuickExpenseRow, error) {
	row := q.db.QueryRow(ctx, getTripDefaultCurrencyForQuickExpense, tripID)
	var i GetTripDefaultCurrencyForQuickExpenseRow
	err := row.Scan(&i.ID, &i.DefaultCurrency)
	return i, err
}

const insertExpense = `-- name: InsertExpense :one
INSERT INTO expenses (
  trip_id,
  anchor_type,
  trip_day_id,
  schedule_item_id,
  expense_date,
  trip_place_id,
  place_name,
  place_address,
  place_type,
  amount_minor,
  currency,
  split_policy,
  payer_participant_id,
  payer_display_name,
  created_by
) VALUES (
  $1::uuid,
  $2,
  $3::uuid,
  $4::uuid,
  $5,
  $6::uuid,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13::uuid,
  $14,
  $15::uuid
)
RETURNING
  id::text,
  trip_id::text,
  anchor_type,
  COALESCE(trip_day_id::text, '')::text AS trip_day_id,
  COALESCE(schedule_item_id::text, '')::text AS schedule_item_id,
  expense_date,
  COALESCE(trip_place_id::text, '')::text AS trip_place_id,
  COALESCE(place_name, '')::text AS place_name,
  COALESCE(place_address, '')::text AS place_address,
  COALESCE(place_type, '')::text AS place_type,
  amount_minor,
  currency,
  split_policy,
  COALESCE(payer_participant_id::text, '')::text AS payer_participant_id,
  payer_display_name,
  created_at
`

type InsertExpenseParams struct {
	TripID             pgtype.UUID
	AnchorType         string
	TripDayID          pgtype.UUID
	ScheduleItemID     pgtype.UUID
	ExpenseDate        pgtype.Date
	TripPlaceID        pgtype.UUID
	PlaceName          pgtype.Text
	PlaceAddress       pgtype.Text
	PlaceType          pgtype.Text
	AmountMinor        int64
	Currency           string
	SplitPolicy        string
	PayerParticipantID pgtype.UUID
	PayerDisplayName   string
	CreatedBy          pgtype.UUID
}

type InsertExpenseRow struct {
	ID                 string
	TripID             string
	AnchorType         string
	TripDayID          string
	ScheduleItemID     string
	ExpenseDate        pgtype.Date
	TripPlaceID        string
	PlaceName          string
	PlaceAddress       string
	PlaceType          string
	AmountMinor        int64
	Currency           string
	SplitPolicy        string
	PayerParticipantID string
	PayerDisplayName   string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) InsertExpense(ctx context.Context, arg InsertExpenseParams) (InsertExpenseRow, error) {
	row := q.db.QueryRow(ctx, insertExpense,
		arg.TripID,
		arg.AnchorType,
		arg.TripDayID,
		arg.ScheduleItemID,
		arg.ExpenseDate,
		arg.TripPlaceID,
		arg.PlaceName,
		arg.PlaceAddress,
		arg.PlaceType,
		arg.AmountMinor,
		arg.Currency,
		arg.SplitPolicy,
		arg.PayerParticipantID,
		arg.PayerDisplayName,
		arg.CreatedBy,
	)
	var i InsertExpenseRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.AnchorType,
		&i.TripDayID,
		&i.ScheduleItemID,
		&i.ExpenseDate,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceAddress,
		&i.PlaceType,
		&i.AmountMinor,
		&i.Currency,
		&i.SplitPolicy,
		&i.PayerParticipantID,
		&i.PayerDisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const insertExpenseSplit = `-- name: InsertExpenseSplit :one
INSERT INTO expense_splits (
  expense_id,
  participant_id,
  participant_display_name,
  amount_minor,
  split_order
) VALUES (
  $1::uuid,
  $2::uuid,
  $3,
  $4,
  $5
)
RETURNING
  id::text,
  expense_id::text,
  COALESCE(participant_id::text, '')::text AS participant_id,
  participant_display_name,
  amount_minor,
  split_order
`

type InsertExpenseSplitParams struct {
	ExpenseID              pgtype.UUID
	ParticipantID          pgtype.UUID
	ParticipantDisplayName string
	AmountMinor            int64
	SplitOrder             int32
}

type InsertExpenseSplitRow struct {
	ID                     string
	ExpenseID              string
	ParticipantID          string
	ParticipantDisplayName string
	AmountMinor            int64
	SplitOrder             int32
}

func (q *Queries) InsertExpenseSplit(ctx context.Context, arg InsertExpenseSplitParams) (InsertExpenseSplitRow, error) {
	row := q.db.QueryRow(ctx, insertExpenseSplit,
		arg.ExpenseID,
		arg.ParticipantID,
		arg.ParticipantDisplayName,
		arg.AmountMinor,
		arg.SplitOrder,
	)
	var i InsertExpenseSplitRow
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.ParticipantID,
		&i.ParticipantDisplayName,
		&i.AmountMinor,
		&i.SplitOrder,
	)
	return i, err
}

const listDayExpenseSplitsByExpenseIDs = `-- name: ListDayExpenseSplitsByExpenseIDs :many
SELECT
  es.expense_id::text AS expense_id,
  es.split_order,
  COALESCE(participant.id::text, es.participant_id::text, '')::text AS participant_id,
  COALESCE(participant.display_name, es.participant_display_name, '여행자')::text AS participant_display_name,
  CASE
    WHEN participant.id IS NOT NULL THEN 'live'
    ELSE 'fallback'
  END::text AS participant_source,
  es.amount_minor
FROM expense_splits es
JOIN expenses e
  ON e.id = es.expense_id
LEFT JOIN trip_participants participant
  ON participant.id = es.participant_id
 AND participant.trip_id = e.trip_id
WHERE es.expense_id = ANY($1::uuid[])
ORDER BY es.expense_id ASC, es.split_order ASC
`

type ListDayExpenseSplitsByExpenseIDsRow struct {
	ExpenseID              string
	SplitOrder             int32
	ParticipantID          string
	ParticipantDisplayName string
	ParticipantSource      string
	AmountMinor            int64
}

func (q *Queries) ListDayExpenseSplitsByExpenseIDs(ctx context.Context, expenseIds []pgtype.UUID) ([]ListDayExpenseSplitsByExpenseIDsRow, error) {
	rows, err := q.db.Query(ctx, listDayExpenseSplitsByExpenseIDs, expenseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDayExpenseSplitsByExpenseIDsRow
	for rows.Next() {
		var i ListDayExpenseSplitsByExpenseIDsRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.SplitOrder,
			&i.ParticipantID,
			&i.ParticipantDisplayName,
			&i.ParticipantSource,
			&i.AmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDayExpensesByTripDay = `-- name: ListDayExpensesByTripDay :many
SELECT
  e.id::text AS id,
  e.anchor_type,
  COALESCE(e.trip_day_id::text, '')::text AS trip_day_id,
  COALESCE(e.schedule_item_id::text, '')::text AS schedule_item_id,
  e.expense_date,
  COALESCE(live_place.name, e.place_name, '지출')::text AS display_title,
  COALESCE(live_place.id::text, e.trip_place_id::text, '')::text AS trip_place_id,
  COALESCE(live_place.name, e.place_name, '')::text AS place_name,
  COALESCE(live_place.address, e.place_address, '')::text AS place_address,
  COALESCE(live_place.place_type, e.place_type, '')::text AS place_type,
  CASE
    WHEN live_place.id IS NOT NULL THEN 'live'
    WHEN e.place_name IS NOT NULL THEN 'fallback'
    ELSE ''
  END::text AS place_source,
  e.amount_minor,
  e.currency,
  COALESCE(payer.id::text, e.payer_participant_id::text, '')::text AS payer_participant_id,
  COALESCE(payer.display_name, e.payer_display_name, '여행자')::text AS payer_display_name,
  CASE
    WHEN payer.id IS NOT NULL THEN 'live'
    ELSE 'fallback'
  END::text AS payer_source,
  e.split_policy,
  e.created_at
FROM expenses e
LEFT JOIN schedule_items si
  ON e.anchor_type = 'schedule_item'
 AND si.id = e.schedule_item_id
 AND si.trip_day_id = e.trip_day_id
 AND si.trip_id = e.trip_id
 AND si.deleted_at IS NULL
LEFT JOIN trip_places live_place
  ON live_place.id = si.trip_place_id
 AND live_place.trip_id = e.trip_id
LEFT JOIN trip_participants payer
  ON payer.id = e.payer_participant_id
 AND payer.trip_id = e.trip_id
WHERE e.trip_id = $1::uuid
  AND e.trip_day_id = $2::uuid
  AND e.anchor_type IN ('trip_day', 'schedule_item')
ORDER BY e.created_at DESC, e.id DESC
`

type ListDayExpensesByTripDayParams struct {
	TripID    pgtype.UUID
	TripDayID pgtype.UUID
}

type ListDayExpensesByTripDayRow struct {
	ID                 string
	AnchorType         string
	TripDayID          string
	ScheduleItemID     string
	ExpenseDate        pgtype.Date
	DisplayTitle       string
	TripPlaceID        string
	PlaceName          string
	PlaceAddress       string
	PlaceType          string
	PlaceSource        string
	AmountMinor        int64
	Currency           string
	PayerParticipantID string
	PayerDisplayName   string
	PayerSource        string
	SplitPolicy        string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) ListDayExpensesByTripDay(ctx context.Context, arg ListDayExpensesByTripDayParams) ([]ListDayExpensesByTripDayRow, error) {
	rows, err := q.db.Query(ctx, listDayExpensesByTripDay, arg.TripID, arg.TripDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDayExpensesByTripDayRow
	for rows.Next() {
		var i ListDayExpensesByTripDayRow
		if err := rows.Scan(
			&i.ID,
			&i.AnchorType,
			&i.TripDayID,
			&i.ScheduleItemID,
			&i.ExpenseDate,
			&i.DisplayTitle,
			&i.TripPlaceID,
			&i.PlaceName,
			&i.PlaceAddress,
			&i.PlaceType,
			&i.PlaceSource,
			&i.AmountMinor,
			&i.Currency,
			&i.PayerParticipantID,
			&i.PayerDisplayName,
			&i.PayerSource,
			&i.SplitPolicy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseSplitsByExpenseID = `-- name: ListExpenseSplitsByExpenseID :many
SELECT
  COALESCE(participant.id::text, es.participant_id::text, '')::text AS participant_id,
  COALESCE(participant.display_name, es.participant_display_name, '여행자')::text AS participant_display_name,
  CASE
    WHEN participant.id IS NOT NULL THEN 'live'
    ELSE 'fallback'
  END::text AS participant_source,
  es.amount_minor,
  es.split_order
FROM expense_splits es
JOIN expenses e
  ON e.id = es.expense_id
LEFT JOIN trip_participants participant
  ON participant.id = es.participant_id
 AND participant.trip_id = e.trip_id
WHERE es.expense_id = $1::uuid
ORDER BY es.split_order ASC
`

type ListExpenseSplitsByExpenseIDRow struct {
	ParticipantID          string
	ParticipantDisplayName string
	ParticipantSource      string
	AmountMinor            int64
	SplitOrder             int32
}

func (q *Queries) ListExpenseSplitsByExpenseID(ctx context.Context, expenseID pgtype.UUID) ([]ListExpenseSplitsByExpenseIDRow, error) {
	rows, err := q.db.Query(ctx, listExpenseSplitsByExpenseID, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseSplitsByExpenseIDRow
	for rows.Next() {
		var i ListExpenseSplitsByExpenseIDRow
		if err := rows.Scan(
			&i.ParticipantID,
			&i.ParticipantDisplayName,
			&i.ParticipantSource,
			&i.AmountMinor,
			&i.SplitOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuickExpenseSplitParticipants = `-- name: ListQuickExpenseSplitParticipants :many
SELECT
  id::text,
  display_name,
  joined_at
FROM trip_participants
WHERE trip_id = $1::uuid
ORDER BY joined_at ASC, id ASC
`

type ListQuickExpenseSplitParticipantsRow struct {
	ID          string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) ListQuickExpenseSplitParticipants(ctx context.Context, tripID pgtype.UUID) ([]ListQuickExpenseSplitParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listQuickExpenseSplitParticipants, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuickExpenseSplitParticipantsRow
	for rows.Next() {
		var i ListQuickExpenseSplitParticipantsRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementParticipantsByTrip = `-- name: ListSettlementParticipantsByTrip :many
SELECT
  id::text,
  display_name,
  joined_at
FROM trip_participants
WHERE trip_id = $1::uuid
ORDER BY joined_at ASC, id ASC
`

type ListSettlementParticipantsByTripRow struct {
	ID          string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) ListSettlementParticipantsByTrip(ctx context.Context, tripID pgtype.UUID) ([]ListSettlementParticipantsByTripRow, error) {
	rows, err := q.db.Query(ctx, listSettlementParticipantsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettlementParticipantsByTripRow
	for rows.Next() {
		var i ListSettlementParticipantsByTripRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementParticipantsByTrips = `-- name: ListSettlementParticipantsByTrips :many
SELECT
  trip_id::text,
  id::text,
  display_name,
  joined_at
FROM trip_participants
WHERE trip_id = ANY($1::uuid[])
ORDER BY trip_id ASC, joined_at ASC, id ASC
`

type ListSettlementParticipantsByTripsRow struct {
	TripID      string
	ID          string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) ListSettlementParticipantsByTrips(ctx context.Context, tripIds []pgtype.UUID) ([]ListSettlementParticipantsByTripsRow, error) {
	rows, err := q.db.Query(ctx, listSettlementParticipantsByTrips, tripIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettlementParticipantsByTripsRow
	for rows.Next() {
		var i ListSettlementParticipantsByTripsRow
		if err := rows.Scan(
			&i.TripID,
			&i.ID,
			&i.DisplayName,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementRowsByTrip = `-- name: ListSettlementRowsByTrip :many
SELECT
  e.id::text AS expense_id,
  e.currency,
  e.amount_minor AS expense_amount_minor,
  COALESCE(payer.id::text, '')::text AS payer_participant_id,
  COALESCE(payer.display_name, e.payer_display_name, '여행자')::text AS payer_display_name,
  (payer.id IS NOT NULL)::boolean AS payer_participant_live,
  COALESCE(es.split_order, 0)::integer AS split_order,
  COALESCE(split_participant.id::text, '')::text AS split_participant_id,
  COALESCE(split_participant.display_name, es.participant_display_name, '여행자')::text AS split_participant_display_name,
  (split_participant.id IS NOT NULL)::boolean AS split_participant_live,
  COALESCE(es.amount_minor, 0)::bigint AS split_amount_minor
FROM expenses e
LEFT JOIN trip_participants payer
  ON payer.id = e.payer_participant_id
 AND payer.trip_id = e.trip_id
LEFT JOIN expense_splits es
  ON es.expense_id = e.id
LEFT JOIN trip_participants split_participant
  ON split_participant.id = es.participant_id
 AND split_participant.trip_id = e.trip_id
WHERE e.trip_id = $1::uuid
  AND e.anchor_type IN ('trip', 'trip_day', 'schedule_item')
ORDER BY e.currency ASC, e.created_at ASC, e.id ASC, es.split_order ASC
`

type ListSettlementRowsByTripRow struct {
	ExpenseID                   string
	Currency                    string
	ExpenseAmountMinor          int64
	PayerParticipantID          string
	PayerDisplayName            string
	PayerParticipantLive        bool
	SplitOrder                  int32
	SplitParticipantID          string
	SplitParticipantDisplayName string
	SplitParticipantLive        bool
	SplitAmountMinor            int64
}

func (q *Queries) ListSettlementRowsByTrip(ctx context.Context, tripID pgtype.UUID) ([]ListSettlementRowsByTripRow, error) {
	rows, err := q.db.Query(ctx, listSettlementRowsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettlementRowsByTripRow
	for rows.Next() {
		var i ListSettlementRowsByTripRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.Currency,
			&i.ExpenseAmountMinor,
			&i.PayerParticipantID,
			&i.PayerDisplayName,
			&i.PayerParticipantLive,
			&i.SplitOrder,
			&i.SplitParticipantID,
			&i.SplitParticipantDisplayName,
			&i.SplitParticipantLive,
			&i.SplitAmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementRowsByTrips = `-- name: ListSettlementRowsByTrips :many
SELECT
  e.trip_id::text AS trip_id,
  e.id::text AS expense_id,
  e.currency,
  e.amount_minor AS expense_amount_minor,
  COALESCE(payer.id::text, '')::text AS payer_participant_id,
  COALESCE(payer.display_name, e.payer_display_name, '여행자')::text AS payer_display_name,
  (payer.id IS NOT NULL)::boolean AS payer_participant_live,
  COALESCE(es.split_order, 0)::integer AS split_order,
  COALESCE(split_participant.id::text, '')::text AS split_participant_id,
  COALESCE(split_participant.display_name, es.participant_display_name, '여행자')::text AS split_participant_display_name,
  (split_participant.id IS NOT NULL)::boolean AS split_participant_live,
  COALESCE(es.amount_minor, 0)::bigint AS split_amount_minor
FROM expenses e
LEFT JOIN trip_participants payer
  ON payer.id = e.payer_participant_id
 AND payer.trip_id = e.trip_id
LEFT JOIN expense_splits es
  ON es.expense_id = e.id
LEFT JOIN trip_participants split_participant
  ON split_participant.id = es.participant_id
 AND split_participant.trip_id = e.trip_id
WHERE e.trip_id = ANY($1::uuid[])
  AND e.anchor_type IN ('trip', 'trip_day', 'schedule_item')
ORDER BY e.trip_id ASC, e.currency ASC, e.created_at ASC, e.id ASC, es.split_order ASC
`

type ListSettlementRowsByTripsRow struct {
	TripID                      string
	ExpenseID                   string
	Currency                    string
	ExpenseAmountMinor          int64
	PayerParticipantID          string
	PayerDisplayName            string
	PayerParticipantLive        bool
	SplitOrder                  int32
	SplitParticipantID          string
	SplitParticipantDisplayName string
	SplitParticipantLive        bool
	SplitAmountMinor            int64
}

func (q *Queries) ListSettlementRowsByTrips(ctx context.Context, tripIds []pgtype.UUID) ([]ListSettlementRowsByTripsRow, error) {
	rows, err := q.db.Query(ctx, listSettlementRowsByTrips, tripIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSettlementRowsByTripsRow
	for rows.Next() {
		var i ListSettlementRowsByTripsRow
		if err := rows.Scan(
			&i.TripID,
			&i.ExpenseID,
			&i.Currency,
			&i.ExpenseAmountMinor,
			&i.PayerParticipantID,
			&i.PayerDisplayName,
			&i.PayerParticipantLive,
			&i.SplitOrder,
			&i.SplitParticipantID,
			&i.SplitParticipantDisplayName,
			&i.SplitParticipantLive,
			&i.SplitAmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripExpensesByTrip = `-- name: ListTripExpensesByTrip :many
SELECT
  e.id::text AS id,
  e.anchor_type,
  COALESCE(e.trip_day_id::text, '')::text AS trip_day_id,
  COALESCE(e.schedule_item_id::text, '')::text AS schedule_item_id,
  e.expense_date,
  COALESCE(live_place.name, e.place_name, '지출')::text AS display_title,
  COALESCE(live_place.id::text, e.trip_place_id::text, '')::text AS trip_place_id,
  COALESCE(live_place.name, e.place_name, '')::text AS place_name,
  COALESCE(live_place.address, e.place_address, '')::text AS place_address,
  COALESCE(live_place.place_type, e.place_type, '')::text AS place_type,
  CASE
    WHEN live_place.id IS NOT NULL THEN 'live'
    WHEN e.place_name IS NOT NULL THEN 'fallback'
    ELSE ''
  END::text AS place_source,
  e.amount_minor,
  e.currency,
  COALESCE(payer.id::text, e.payer_participant_id::text, '')::text AS payer_participant_id,
  COALESCE(payer.display_name, e.payer_display_name, '여행자')::text AS payer_display_name,
  CASE
    WHEN payer.id IS NOT NULL THEN 'live'
    ELSE 'fallback'
  END::text AS payer_source,
  e.split_policy,
  e.created_at
FROM expenses e
LEFT JOIN schedule_items si
  ON e.anchor_type = 'schedule_item'
 AND si.id = e.schedule_item_id
 AND si.trip_day_id = e.trip_day_id
 AND si.trip_id = e.trip_id
 AND si.deleted_at IS NULL
LEFT JOIN trip_places live_place
  ON live_place.id = si.trip_place_id
 AND live_place.trip_id = e.trip_id
LEFT JOIN trip_participants payer
  ON payer.id = e.payer_participant_id
 AND payer.trip_id = e.trip_id
WHERE e.trip_id = $1::uuid
  AND e.anchor_type IN ('trip_day', 'schedule_item')
ORDER BY e.trip_day_id ASC, e.created_at DESC, e.id DESC
`

type ListTripExpensesByTripRow struct {
	ID                 string
	AnchorType         string
	TripDayID          string
	ScheduleItemID     string
	ExpenseDate        pgtype.Date
	DisplayTitle       string
	TripPlaceID        string
	PlaceName          string
	PlaceAddress       string
	PlaceType          string
	PlaceSource        string
	AmountMinor        int64
	Currency           string
	PayerParticipantID string
	PayerDisplayName   string
	PayerSource        string
	SplitPolicy        string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) ListTripExpensesByTrip(ctx context.Context, tripID pgtype.UUID) ([]ListTripExpensesByTripRow, error) {
	rows, err := q.db.Query(ctx, listTripExpensesByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripExpensesByTripRow
	for rows.Next() {
		var i ListTripExpensesByTripRow
		if err := rows.Scan(
			&i.ID,
			&i.AnchorType,
			&i.TripDayID,
			&i.ScheduleItemID,
			&i.ExpenseDate,
			&i.DisplayTitle,
			&i.TripPlaceID,
			&i.PlaceName,
			&i.PlaceAddress,
			&i.PlaceType,
			&i.PlaceSource,
			&i.AmountMinor,
			&i.Currency,
			&i.PayerParticipantID,
			&i.PayerDisplayName,
			&i.PayerSource,
			&i.SplitPolicy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET
  anchor_type = $1,
  schedule_item_id = $2::uuid,
  trip_place_id = $3::uuid,
  place_name = $4,
  place_address = $5,
  place_type = $6,
  amount_minor = $7,
  split_policy = $8,
  payer_participant_id = $9::uuid,
  payer_display_name = $10,
  memo = $11,
  updated_at = now()
WHERE trip_id = $12::uuid
  AND trip_day_id = $13::uuid
  AND id = $14::uuid
  AND anchor_type IN ('trip_day', 'schedule_item')
RETURNING
  id::text,
  trip_id::text,
  anchor_type,
  COALESCE(trip_day_id::text, '')::text AS trip_day_id,
  COALESCE(schedule_item_id::text, '')::text AS schedule_item_id,
  expense_date,
  COALESCE(trip_place_id::text, '')::text AS trip_place_id,
  COALESCE(place_name, '')::text AS place_name,
  COALESCE(place_address, '')::text AS place_address,
  COALESCE(place_type, '')::text AS place_type,
  amount_minor,
  currency,
  split_policy,
  COALESCE(payer_participant_id::text, '')::text AS payer_participant_id,
  payer_display_name,
  memo,
  created_at
`

type UpdateExpenseParams struct {
	AnchorType         string
	ScheduleItemID     pgtype.UUID
	TripPlaceID        pgtype.UUID
	PlaceName          pgtype.Text
	PlaceAddress       pgtype.Text
	PlaceType          pgtype.Text
	AmountMinor        int64
	SplitPolicy        string
	PayerParticipantID pgtype.UUID
	PayerDisplayName   string
	Memo               pgtype.Text
	TripID             pgtype.UUID
	TripDayID          pgtype.UUID
	ExpenseID          pgtype.UUID
}

type UpdateExpenseRow struct {
	ID                 string
	TripID             string
	AnchorType         string
	TripDayID          string
	ScheduleItemID     string
	ExpenseDate        pgtype.Date
	TripPlaceID        string
	PlaceName          string
	PlaceAddress       string
	PlaceType          string
	AmountMinor        int64
	Currency           string
	SplitPolicy        string
	PayerParticipantID string
	PayerDisplayName   string
	Memo               pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (UpdateExpenseRow, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.AnchorType,
		arg.ScheduleItemID,
		arg.TripPlaceID,
		arg.PlaceName,
		arg.PlaceAddress,
		arg.PlaceType,
		arg.AmountMinor,
		arg.SplitPolicy,
		arg.PayerParticipantID,
		arg.PayerDisplayName,
		arg.Memo,
		arg.TripID,
		arg.TripDayID,
		arg.ExpenseID,
	)
	var i UpdateExpenseRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.AnchorType,
		&i.TripDayID,
		&i.ScheduleItemID,
		&i.ExpenseDate,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceAddress,
		&i.PlaceType,
		&i.AmountMinor,
		&i.Currency,
		&i.SplitPolicy,
		&i.PayerParticipantID,
		&i.PayerDisplayName,
		&i.Memo,
		&i.CreatedAt,
	)
	return i, err
}
