// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuickExpenseItineraryItem = `-- name: GetQuickExpenseItineraryItem :one
SELECT
  ii.id::text AS itinerary_item_id,
  ii.scheduled_date,
  tp.id::text AS trip_place_id,
  tp.name AS place_name,
  tp.place_type,
  tp.address AS place_address
FROM itinerary_items ii
JOIN trip_places tp
  ON tp.id = ii.trip_place_id
 AND tp.trip_id = ii.trip_id
WHERE ii.trip_id = $1::uuid
  AND ii.scheduled_date = $2
  AND ii.id = $3::uuid
`

type GetQuickExpenseItineraryItemParams struct {
	TripID          pgtype.UUID
	ScheduledDate   pgtype.Date
	ItineraryItemID pgtype.UUID
}

type GetQuickExpenseItineraryItemRow struct {
	ItineraryItemID string
	ScheduledDate   pgtype.Date
	TripPlaceID     string
	PlaceName       string
	PlaceType       string
	PlaceAddress    string
}

func (q *Queries) GetQuickExpenseItineraryItem(ctx context.Context, arg GetQuickExpenseItineraryItemParams) (GetQuickExpenseItineraryItemRow, error) {
	row := q.db.QueryRow(ctx, getQuickExpenseItineraryItem, arg.TripID, arg.ScheduledDate, arg.ItineraryItemID)
	var i GetQuickExpenseItineraryItemRow
	err := row.Scan(
		&i.ItineraryItemID,
		&i.ScheduledDate,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceType,
		&i.PlaceAddress,
	)
	return i, err
}

const getQuickExpensePayerParticipant = `-- name: GetQuickExpensePayerParticipant :one
SELECT
  id::text,
  display_name,
  joined_at
FROM trip_participants
WHERE trip_id = $1::uuid
  AND id = $2::uuid
`

type GetQuickExpensePayerParticipantParams struct {
	TripID             pgtype.UUID
	PayerParticipantID pgtype.UUID
}

type GetQuickExpensePayerParticipantRow struct {
	ID          string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) GetQuickExpensePayerParticipant(ctx context.Context, arg GetQuickExpensePayerParticipantParams) (GetQuickExpensePayerParticipantRow, error) {
	row := q.db.QueryRow(ctx, getQuickExpensePayerParticipant, arg.TripID, arg.PayerParticipantID)
	var i GetQuickExpensePayerParticipantRow
	err := row.Scan(&i.ID, &i.DisplayName, &i.JoinedAt)
	return i, err
}

const getTripDefaultCurrencyForQuickExpense = `-- name: GetTripDefaultCurrencyForQuickExpense :one
SELECT
  id::text,
  default_currency
FROM trips
WHERE id = $1::uuid
`

type GetTripDefaultCurrencyForQuickExpenseRow struct {
	ID              string
	DefaultCurrency string
}

func (q *Queries) GetTripDefaultCurrencyForQuickExpense(ctx context.Context, tripID pgtype.UUID) (GetTripDefaultCurrencyForQuickExpenseRow, error) {
	row := q.db.QueryRow(ctx, getTripDefaultCurrencyForQuickExpense, tripID)
	var i GetTripDefaultCurrencyForQuickExpenseRow
	err := row.Scan(&i.ID, &i.DefaultCurrency)
	return i, err
}

const insertExpense = `-- name: InsertExpense :one
INSERT INTO expenses (
  trip_id,
  scheduled_date,
  itinerary_item_id,
  trip_place_id,
  place_name,
  place_address,
  place_type,
  amount_minor,
  currency,
  payer_participant_id,
  payer_display_name,
  created_by
) VALUES (
  $1::uuid,
  $2,
  $3::uuid,
  $4::uuid,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10::uuid,
  $11,
  $12::uuid
)
RETURNING
  id::text,
  trip_id::text,
  scheduled_date,
  itinerary_item_id::text,
  trip_place_id::text,
  place_name,
  place_address,
  place_type,
  amount_minor,
  currency,
  payer_participant_id::text,
  payer_display_name,
  created_at
`

type InsertExpenseParams struct {
	TripID             pgtype.UUID
	ScheduledDate      pgtype.Date
	ItineraryItemID    pgtype.UUID
	TripPlaceID        pgtype.UUID
	PlaceName          string
	PlaceAddress       string
	PlaceType          string
	AmountMinor        int64
	Currency           string
	PayerParticipantID pgtype.UUID
	PayerDisplayName   string
	CreatedBy          pgtype.UUID
}

type InsertExpenseRow struct {
	ID                 string
	TripID             string
	ScheduledDate      pgtype.Date
	ItineraryItemID    string
	TripPlaceID        string
	PlaceName          string
	PlaceAddress       string
	PlaceType          string
	AmountMinor        int64
	Currency           string
	PayerParticipantID string
	PayerDisplayName   string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) InsertExpense(ctx context.Context, arg InsertExpenseParams) (InsertExpenseRow, error) {
	row := q.db.QueryRow(ctx, insertExpense,
		arg.TripID,
		arg.ScheduledDate,
		arg.ItineraryItemID,
		arg.TripPlaceID,
		arg.PlaceName,
		arg.PlaceAddress,
		arg.PlaceType,
		arg.AmountMinor,
		arg.Currency,
		arg.PayerParticipantID,
		arg.PayerDisplayName,
		arg.CreatedBy,
	)
	var i InsertExpenseRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.ScheduledDate,
		&i.ItineraryItemID,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceAddress,
		&i.PlaceType,
		&i.AmountMinor,
		&i.Currency,
		&i.PayerParticipantID,
		&i.PayerDisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const insertExpenseSplit = `-- name: InsertExpenseSplit :one
INSERT INTO expense_splits (
  expense_id,
  participant_id,
  participant_display_name,
  amount_minor,
  split_order
) VALUES (
  $1::uuid,
  $2::uuid,
  $3,
  $4,
  $5
)
RETURNING
  participant_id::text,
  participant_display_name,
  amount_minor,
  split_order
`

type InsertExpenseSplitParams struct {
	ExpenseID              pgtype.UUID
	ParticipantID          pgtype.UUID
	ParticipantDisplayName string
	AmountMinor            int64
	SplitOrder             int32
}

type InsertExpenseSplitRow struct {
	ParticipantID          string
	ParticipantDisplayName string
	AmountMinor            int64
	SplitOrder             int32
}

func (q *Queries) InsertExpenseSplit(ctx context.Context, arg InsertExpenseSplitParams) (InsertExpenseSplitRow, error) {
	row := q.db.QueryRow(ctx, insertExpenseSplit,
		arg.ExpenseID,
		arg.ParticipantID,
		arg.ParticipantDisplayName,
		arg.AmountMinor,
		arg.SplitOrder,
	)
	var i InsertExpenseSplitRow
	err := row.Scan(
		&i.ParticipantID,
		&i.ParticipantDisplayName,
		&i.AmountMinor,
		&i.SplitOrder,
	)
	return i, err
}

const listDayExpenseSplitsByExpenseIDs = `-- name: ListDayExpenseSplitsByExpenseIDs :many
SELECT
  expense_id::text,
  split_order,
  participant_display_name,
  amount_minor
FROM expense_splits
WHERE expense_id = ANY($1::uuid[])
ORDER BY expense_id ASC, split_order ASC
`

type ListDayExpenseSplitsByExpenseIDsRow struct {
	ExpenseID              string
	SplitOrder             int32
	ParticipantDisplayName string
	AmountMinor            int64
}

func (q *Queries) ListDayExpenseSplitsByExpenseIDs(ctx context.Context, expenseIds []pgtype.UUID) ([]ListDayExpenseSplitsByExpenseIDsRow, error) {
	rows, err := q.db.Query(ctx, listDayExpenseSplitsByExpenseIDs, expenseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDayExpenseSplitsByExpenseIDsRow
	for rows.Next() {
		var i ListDayExpenseSplitsByExpenseIDsRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.SplitOrder,
			&i.ParticipantDisplayName,
			&i.AmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDayExpensesByTripAndDate = `-- name: ListDayExpensesByTripAndDate :many
SELECT
  id::text,
  place_name,
  place_address,
  place_type,
  amount_minor,
  currency,
  payer_display_name,
  created_at
FROM expenses
WHERE trip_id = $1::uuid
  AND scheduled_date = $2
ORDER BY created_at DESC, id DESC
`

type ListDayExpensesByTripAndDateParams struct {
	TripID        pgtype.UUID
	ScheduledDate pgtype.Date
}

type ListDayExpensesByTripAndDateRow struct {
	ID               string
	PlaceName        string
	PlaceAddress     string
	PlaceType        string
	AmountMinor      int64
	Currency         string
	PayerDisplayName string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListDayExpensesByTripAndDate(ctx context.Context, arg ListDayExpensesByTripAndDateParams) ([]ListDayExpensesByTripAndDateRow, error) {
	rows, err := q.db.Query(ctx, listDayExpensesByTripAndDate, arg.TripID, arg.ScheduledDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDayExpensesByTripAndDateRow
	for rows.Next() {
		var i ListDayExpensesByTripAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.PlaceName,
			&i.PlaceAddress,
			&i.PlaceType,
			&i.AmountMinor,
			&i.Currency,
			&i.PayerDisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuickExpenseSplitParticipants = `-- name: ListQuickExpenseSplitParticipants :many
SELECT
  id::text,
  display_name,
  joined_at
FROM trip_participants
WHERE trip_id = $1::uuid
ORDER BY joined_at ASC, id ASC
`

type ListQuickExpenseSplitParticipantsRow struct {
	ID          string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) ListQuickExpenseSplitParticipants(ctx context.Context, tripID pgtype.UUID) ([]ListQuickExpenseSplitParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listQuickExpenseSplitParticipants, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuickExpenseSplitParticipantsRow
	for rows.Next() {
		var i ListQuickExpenseSplitParticipantsRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
