// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: flights.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimStorageObjectDeletionJobs = `-- name: ClaimStorageObjectDeletionJobs :many
UPDATE storage_object_deletion_jobs
SET status = 'running',
    updated_at = now()
WHERE id IN (
  SELECT id
  FROM storage_object_deletion_jobs
  WHERE status IN ('pending', 'failed')
    AND attempts < 5
    AND next_attempt_at <= now()
  ORDER BY next_attempt_at ASC, id ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
RETURNING
  id::text,
  bucket,
  object_key,
  object_generation,
  reason,
  status,
  attempts,
  next_attempt_at,
  last_error,
  created_at,
  updated_at,
  processed_at
`

type ClaimStorageObjectDeletionJobsRow struct {
	ID               string
	Bucket           string
	ObjectKey        string
	ObjectGeneration pgtype.Text
	Reason           string
	Status           string
	Attempts         int32
	NextAttemptAt    pgtype.Timestamptz
	LastError        pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ProcessedAt      pgtype.Timestamptz
}

func (q *Queries) ClaimStorageObjectDeletionJobs(ctx context.Context, limitCount int32) ([]ClaimStorageObjectDeletionJobsRow, error) {
	rows, err := q.db.Query(ctx, claimStorageObjectDeletionJobs, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimStorageObjectDeletionJobsRow
	for rows.Next() {
		var i ClaimStorageObjectDeletionJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Bucket,
			&i.ObjectKey,
			&i.ObjectGeneration,
			&i.Reason,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearFlightBoardingPassMetadata = `-- name: ClearFlightBoardingPassMetadata :one
UPDATE flight_personal_details
SET boarding_pass_bucket = NULL,
    boarding_pass_object_key = NULL,
    boarding_pass_generation = NULL,
    boarding_pass_content_type = NULL,
    boarding_pass_byte_size = NULL,
    boarding_pass_uploaded_at = NULL,
    updated_at = now()
WHERE trip_id = $1::uuid
  AND flight_id = $2::uuid
  AND passenger_participant_id = $3::uuid
RETURNING
  id::text,
  flight_id::text,
  trip_id::text,
  passenger_participant_id::text,
  created_by_user_id::text,
  reservation_number,
  seat,
  check_in_url,
  boarding_pass_bucket,
  boarding_pass_object_key,
  boarding_pass_generation,
  boarding_pass_content_type,
  boarding_pass_byte_size,
  boarding_pass_uploaded_at,
  created_at,
  updated_at
`

type ClearFlightBoardingPassMetadataParams struct {
	TripID                 pgtype.UUID
	FlightID               pgtype.UUID
	PassengerParticipantID pgtype.UUID
}

type ClearFlightBoardingPassMetadataRow struct {
	ID                      string
	FlightID                string
	TripID                  string
	PassengerParticipantID  string
	CreatedByUserID         string
	ReservationNumber       pgtype.Text
	Seat                    pgtype.Text
	CheckInUrl              pgtype.Text
	BoardingPassBucket      pgtype.Text
	BoardingPassObjectKey   pgtype.Text
	BoardingPassGeneration  pgtype.Text
	BoardingPassContentType pgtype.Text
	BoardingPassByteSize    pgtype.Int4
	BoardingPassUploadedAt  pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) ClearFlightBoardingPassMetadata(ctx context.Context, arg ClearFlightBoardingPassMetadataParams) (ClearFlightBoardingPassMetadataRow, error) {
	row := q.db.QueryRow(ctx, clearFlightBoardingPassMetadata, arg.TripID, arg.FlightID, arg.PassengerParticipantID)
	var i ClearFlightBoardingPassMetadataRow
	err := row.Scan(
		&i.ID,
		&i.FlightID,
		&i.TripID,
		&i.PassengerParticipantID,
		&i.CreatedByUserID,
		&i.ReservationNumber,
		&i.Seat,
		&i.CheckInUrl,
		&i.BoardingPassBucket,
		&i.BoardingPassObjectKey,
		&i.BoardingPassGeneration,
		&i.BoardingPassContentType,
		&i.BoardingPassByteSize,
		&i.BoardingPassUploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlight = `-- name: CreateFlight :one
INSERT INTO flights (
  trip_id,
  flight_number,
  display_title,
  departure_airport_text,
  departure_airport_code,
  departure_local_date,
  departure_local_time,
  departure_time_zone,
  departure_at,
  arrival_airport_text,
  arrival_airport_code,
  arrival_local_date,
  arrival_local_time,
  arrival_time_zone,
  arrival_at,
  created_by_user_id
) VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16::uuid
)
RETURNING
  id::text,
  trip_id::text,
  flight_number,
  display_title,
  departure_airport_text,
  departure_airport_code,
  departure_local_date,
  departure_local_time,
  departure_time_zone,
  departure_at,
  arrival_airport_text,
  arrival_airport_code,
  arrival_local_date,
  arrival_local_time,
  arrival_time_zone,
  arrival_at,
  created_by_user_id::text,
  created_at,
  updated_at
`

type CreateFlightParams struct {
	TripID               pgtype.UUID
	FlightNumber         pgtype.Text
	DisplayTitle         string
	DepartureAirportText string
	DepartureAirportCode pgtype.Text
	DepartureLocalDate   pgtype.Date
	DepartureLocalTime   pgtype.Time
	DepartureTimeZone    string
	DepartureAt          pgtype.Timestamptz
	ArrivalAirportText   string
	ArrivalAirportCode   pgtype.Text
	ArrivalLocalDate     pgtype.Date
	ArrivalLocalTime     pgtype.Time
	ArrivalTimeZone      string
	ArrivalAt            pgtype.Timestamptz
	CreatedByUserID      pgtype.UUID
}

type CreateFlightRow struct {
	ID                   string
	TripID               string
	FlightNumber         pgtype.Text
	DisplayTitle         string
	DepartureAirportText string
	DepartureAirportCode pgtype.Text
	DepartureLocalDate   pgtype.Date
	DepartureLocalTime   pgtype.Time
	DepartureTimeZone    string
	DepartureAt          pgtype.Timestamptz
	ArrivalAirportText   string
	ArrivalAirportCode   pgtype.Text
	ArrivalLocalDate     pgtype.Date
	ArrivalLocalTime     pgtype.Time
	ArrivalTimeZone      string
	ArrivalAt            pgtype.Timestamptz
	CreatedByUserID      string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) CreateFlight(ctx context.Context, arg CreateFlightParams) (CreateFlightRow, error) {
	row := q.db.QueryRow(ctx, createFlight,
		arg.TripID,
		arg.FlightNumber,
		arg.DisplayTitle,
		arg.DepartureAirportText,
		arg.DepartureAirportCode,
		arg.DepartureLocalDate,
		arg.DepartureLocalTime,
		arg.DepartureTimeZone,
		arg.DepartureAt,
		arg.ArrivalAirportText,
		arg.ArrivalAirportCode,
		arg.ArrivalLocalDate,
		arg.ArrivalLocalTime,
		arg.ArrivalTimeZone,
		arg.ArrivalAt,
		arg.CreatedByUserID,
	)
	var i CreateFlightRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.FlightNumber,
		&i.DisplayTitle,
		&i.DepartureAirportText,
		&i.DepartureAirportCode,
		&i.DepartureLocalDate,
		&i.DepartureLocalTime,
		&i.DepartureTimeZone,
		&i.DepartureAt,
		&i.ArrivalAirportText,
		&i.ArrivalAirportCode,
		&i.ArrivalLocalDate,
		&i.ArrivalLocalTime,
		&i.ArrivalTimeZone,
		&i.ArrivalAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlightPassenger = `-- name: CreateFlightPassenger :one
INSERT INTO flight_passengers (
  flight_id,
  trip_id,
  participant_id,
  added_by_user_id
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::uuid
)
RETURNING
  id::text,
  flight_id::text,
  trip_id::text,
  participant_id::text,
  added_by_user_id::text,
  created_at
`

type CreateFlightPassengerParams struct {
	FlightID      pgtype.UUID
	TripID        pgtype.UUID
	ParticipantID pgtype.UUID
	AddedByUserID pgtype.UUID
}

type CreateFlightPassengerRow struct {
	ID            string
	FlightID      string
	TripID        string
	ParticipantID string
	AddedByUserID string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateFlightPassenger(ctx context.Context, arg CreateFlightPassengerParams) (CreateFlightPassengerRow, error) {
	row := q.db.QueryRow(ctx, createFlightPassenger,
		arg.FlightID,
		arg.TripID,
		arg.ParticipantID,
		arg.AddedByUserID,
	)
	var i CreateFlightPassengerRow
	err := row.Scan(
		&i.ID,
		&i.FlightID,
		&i.TripID,
		&i.ParticipantID,
		&i.AddedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createStorageObjectDeletionJob = `-- name: CreateStorageObjectDeletionJob :one
INSERT INTO storage_object_deletion_jobs (
  bucket,
  object_key,
  object_generation,
  reason
) VALUES (
  $1,
  $2,
  $3,
  $4
)
ON CONFLICT DO NOTHING
RETURNING
  id::text,
  bucket,
  object_key,
  object_generation,
  reason,
  status,
  attempts,
  next_attempt_at,
  last_error,
  created_at,
  updated_at,
  processed_at
`

type CreateStorageObjectDeletionJobParams struct {
	Bucket           string
	ObjectKey        string
	ObjectGeneration pgtype.Text
	Reason           string
}

type CreateStorageObjectDeletionJobRow struct {
	ID               string
	Bucket           string
	ObjectKey        string
	ObjectGeneration pgtype.Text
	Reason           string
	Status           string
	Attempts         int32
	NextAttemptAt    pgtype.Timestamptz
	LastError        pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ProcessedAt      pgtype.Timestamptz
}

func (q *Queries) CreateStorageObjectDeletionJob(ctx context.Context, arg CreateStorageObjectDeletionJobParams) (CreateStorageObjectDeletionJobRow, error) {
	row := q.db.QueryRow(ctx, createStorageObjectDeletionJob,
		arg.Bucket,
		arg.ObjectKey,
		arg.ObjectGeneration,
		arg.Reason,
	)
	var i CreateStorageObjectDeletionJobRow
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.ObjectGeneration,
		&i.Reason,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const enqueueFlightBoardingPassDeletionJobsForParticipant = `-- name: EnqueueFlightBoardingPassDeletionJobsForParticipant :exec
INSERT INTO storage_object_deletion_jobs (
  bucket,
  object_key,
  object_generation,
  reason
)
SELECT
  boarding_pass_bucket,
  boarding_pass_object_key,
  boarding_pass_generation,
  $1
FROM flight_personal_details
WHERE trip_id = $2::uuid
  AND passenger_participant_id = $3::uuid
  AND boarding_pass_object_key IS NOT NULL
ON CONFLICT DO NOTHING
`

type EnqueueFlightBoardingPassDeletionJobsForParticipantParams struct {
	Reason        string
	TripID        pgtype.UUID
	ParticipantID pgtype.UUID
}

func (q *Queries) EnqueueFlightBoardingPassDeletionJobsForParticipant(ctx context.Context, arg EnqueueFlightBoardingPassDeletionJobsForParticipantParams) error {
	_, err := q.db.Exec(ctx, enqueueFlightBoardingPassDeletionJobsForParticipant, arg.Reason, arg.TripID, arg.ParticipantID)
	return err
}

const enqueueFlightBoardingPassDeletionJobsForTrip = `-- name: EnqueueFlightBoardingPassDeletionJobsForTrip :exec
INSERT INTO storage_object_deletion_jobs (
  bucket,
  object_key,
  object_generation,
  reason
)
SELECT
  boarding_pass_bucket,
  boarding_pass_object_key,
  boarding_pass_generation,
  $1
FROM flight_personal_details
WHERE trip_id = $2::uuid
  AND boarding_pass_object_key IS NOT NULL
ON CONFLICT DO NOTHING
`

type EnqueueFlightBoardingPassDeletionJobsForTripParams struct {
	Reason string
	TripID pgtype.UUID
}

func (q *Queries) EnqueueFlightBoardingPassDeletionJobsForTrip(ctx context.Context, arg EnqueueFlightBoardingPassDeletionJobsForTripParams) error {
	_, err := q.db.Exec(ctx, enqueueFlightBoardingPassDeletionJobsForTrip, arg.Reason, arg.TripID)
	return err
}

const getFlightByTrip = `-- name: GetFlightByTrip :one
SELECT
  id::text,
  trip_id::text,
  flight_number,
  display_title,
  departure_airport_text,
  departure_airport_code,
  departure_local_date,
  departure_local_time,
  departure_time_zone,
  departure_at,
  arrival_airport_text,
  arrival_airport_code,
  arrival_local_date,
  arrival_local_time,
  arrival_time_zone,
  arrival_at,
  created_by_user_id::text,
  created_at,
  updated_at
FROM flights
WHERE trip_id = $1::uuid
  AND id = $2::uuid
`

type GetFlightByTripParams struct {
	TripID   pgtype.UUID
	FlightID pgtype.UUID
}

type GetFlightByTripRow struct {
	ID                   string
	TripID               string
	FlightNumber         pgtype.Text
	DisplayTitle         string
	DepartureAirportText string
	DepartureAirportCode pgtype.Text
	DepartureLocalDate   pgtype.Date
	DepartureLocalTime   pgtype.Time
	DepartureTimeZone    string
	DepartureAt          pgtype.Timestamptz
	ArrivalAirportText   string
	ArrivalAirportCode   pgtype.Text
	ArrivalLocalDate     pgtype.Date
	ArrivalLocalTime     pgtype.Time
	ArrivalTimeZone      string
	ArrivalAt            pgtype.Timestamptz
	CreatedByUserID      string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) GetFlightByTrip(ctx context.Context, arg GetFlightByTripParams) (GetFlightByTripRow, error) {
	row := q.db.QueryRow(ctx, getFlightByTrip, arg.TripID, arg.FlightID)
	var i GetFlightByTripRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.FlightNumber,
		&i.DisplayTitle,
		&i.DepartureAirportText,
		&i.DepartureAirportCode,
		&i.DepartureLocalDate,
		&i.DepartureLocalTime,
		&i.DepartureTimeZone,
		&i.DepartureAt,
		&i.ArrivalAirportText,
		&i.ArrivalAirportCode,
		&i.ArrivalLocalDate,
		&i.ArrivalLocalTime,
		&i.ArrivalTimeZone,
		&i.ArrivalAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlightPassengerParticipantForUser = `-- name: GetFlightPassengerParticipantForUser :one
SELECT fp.participant_id::text
FROM flight_passengers fp
JOIN trip_participants tp ON tp.id = fp.participant_id
WHERE fp.trip_id = $1::uuid
  AND fp.flight_id = $2::uuid
  AND tp.user_id = $3::uuid
`

type GetFlightPassengerParticipantForUserParams struct {
	TripID   pgtype.UUID
	FlightID pgtype.UUID
	UserID   pgtype.UUID
}

func (q *Queries) GetFlightPassengerParticipantForUser(ctx context.Context, arg GetFlightPassengerParticipantForUserParams) (string, error) {
	row := q.db.QueryRow(ctx, getFlightPassengerParticipantForUser, arg.TripID, arg.FlightID, arg.UserID)
	var fp_participant_id string
	err := row.Scan(&fp_participant_id)
	return fp_participant_id, err
}

const getFlightPersonalDetail = `-- name: GetFlightPersonalDetail :one
SELECT
  id::text,
  flight_id::text,
  trip_id::text,
  passenger_participant_id::text,
  created_by_user_id::text,
  reservation_number,
  seat,
  check_in_url,
  boarding_pass_bucket,
  boarding_pass_object_key,
  boarding_pass_generation,
  boarding_pass_content_type,
  boarding_pass_byte_size,
  boarding_pass_uploaded_at,
  created_at,
  updated_at
FROM flight_personal_details
WHERE trip_id = $1::uuid
  AND flight_id = $2::uuid
  AND passenger_participant_id = $3::uuid
`

type GetFlightPersonalDetailParams struct {
	TripID                 pgtype.UUID
	FlightID               pgtype.UUID
	PassengerParticipantID pgtype.UUID
}

type GetFlightPersonalDetailRow struct {
	ID                      string
	FlightID                string
	TripID                  string
	PassengerParticipantID  string
	CreatedByUserID         string
	ReservationNumber       pgtype.Text
	Seat                    pgtype.Text
	CheckInUrl              pgtype.Text
	BoardingPassBucket      pgtype.Text
	BoardingPassObjectKey   pgtype.Text
	BoardingPassGeneration  pgtype.Text
	BoardingPassContentType pgtype.Text
	BoardingPassByteSize    pgtype.Int4
	BoardingPassUploadedAt  pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) GetFlightPersonalDetail(ctx context.Context, arg GetFlightPersonalDetailParams) (GetFlightPersonalDetailRow, error) {
	row := q.db.QueryRow(ctx, getFlightPersonalDetail, arg.TripID, arg.FlightID, arg.PassengerParticipantID)
	var i GetFlightPersonalDetailRow
	err := row.Scan(
		&i.ID,
		&i.FlightID,
		&i.TripID,
		&i.PassengerParticipantID,
		&i.CreatedByUserID,
		&i.ReservationNumber,
		&i.Seat,
		&i.CheckInUrl,
		&i.BoardingPassBucket,
		&i.BoardingPassObjectKey,
		&i.BoardingPassGeneration,
		&i.BoardingPassContentType,
		&i.BoardingPassByteSize,
		&i.BoardingPassUploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFlightPassengersByFlight = `-- name: ListFlightPassengersByFlight :many
SELECT
  fp.flight_id::text AS flight_id,
  fp.participant_id::text AS participant_id,
  tp.display_name
FROM flight_passengers fp
JOIN trip_participants tp ON tp.id = fp.participant_id
WHERE fp.trip_id = $1::uuid
  AND fp.flight_id = $2::uuid
ORDER BY tp.joined_at ASC, fp.participant_id ASC
`

type ListFlightPassengersByFlightParams struct {
	TripID   pgtype.UUID
	FlightID pgtype.UUID
}

type ListFlightPassengersByFlightRow struct {
	FlightID      string
	ParticipantID string
	DisplayName   string
}

func (q *Queries) ListFlightPassengersByFlight(ctx context.Context, arg ListFlightPassengersByFlightParams) ([]ListFlightPassengersByFlightRow, error) {
	rows, err := q.db.Query(ctx, listFlightPassengersByFlight, arg.TripID, arg.FlightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlightPassengersByFlightRow
	for rows.Next() {
		var i ListFlightPassengersByFlightRow
		if err := rows.Scan(&i.FlightID, &i.ParticipantID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlightPassengersByTrip = `-- name: ListFlightPassengersByTrip :many
SELECT
  fp.flight_id::text AS flight_id,
  fp.participant_id::text AS participant_id,
  tp.display_name
FROM flight_passengers fp
JOIN trip_participants tp ON tp.id = fp.participant_id
WHERE fp.trip_id = $1::uuid
ORDER BY fp.flight_id ASC, tp.joined_at ASC, fp.participant_id ASC
`

type ListFlightPassengersByTripRow struct {
	FlightID      string
	ParticipantID string
	DisplayName   string
}

func (q *Queries) ListFlightPassengersByTrip(ctx context.Context, tripID pgtype.UUID) ([]ListFlightPassengersByTripRow, error) {
	rows, err := q.db.Query(ctx, listFlightPassengersByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlightPassengersByTripRow
	for rows.Next() {
		var i ListFlightPassengersByTripRow
		if err := rows.Scan(&i.FlightID, &i.ParticipantID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlightsByTrip = `-- name: ListFlightsByTrip :many
SELECT
  id::text,
  trip_id::text,
  flight_number,
  display_title,
  departure_airport_text,
  departure_airport_code,
  departure_local_date,
  departure_local_time,
  departure_time_zone,
  departure_at,
  arrival_airport_text,
  arrival_airport_code,
  arrival_local_date,
  arrival_local_time,
  arrival_time_zone,
  arrival_at,
  created_by_user_id::text,
  created_at,
  updated_at
FROM flights
WHERE trip_id = $1::uuid
ORDER BY departure_at ASC, id ASC
`

type ListFlightsByTripRow struct {
	ID                   string
	TripID               string
	FlightNumber         pgtype.Text
	DisplayTitle         string
	DepartureAirportText string
	DepartureAirportCode pgtype.Text
	DepartureLocalDate   pgtype.Date
	DepartureLocalTime   pgtype.Time
	DepartureTimeZone    string
	DepartureAt          pgtype.Timestamptz
	ArrivalAirportText   string
	ArrivalAirportCode   pgtype.Text
	ArrivalLocalDate     pgtype.Date
	ArrivalLocalTime     pgtype.Time
	ArrivalTimeZone      string
	ArrivalAt            pgtype.Timestamptz
	CreatedByUserID      string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) ListFlightsByTrip(ctx context.Context, tripID pgtype.UUID) ([]ListFlightsByTripRow, error) {
	rows, err := q.db.Query(ctx, listFlightsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlightsByTripRow
	for rows.Next() {
		var i ListFlightsByTripRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.FlightNumber,
			&i.DisplayTitle,
			&i.DepartureAirportText,
			&i.DepartureAirportCode,
			&i.DepartureLocalDate,
			&i.DepartureLocalTime,
			&i.DepartureTimeZone,
			&i.DepartureAt,
			&i.ArrivalAirportText,
			&i.ArrivalAirportCode,
			&i.ArrivalLocalDate,
			&i.ArrivalLocalTime,
			&i.ArrivalTimeZone,
			&i.ArrivalAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyFlightPersonalDetailsByTrip = `-- name: ListMyFlightPersonalDetailsByTrip :many
SELECT
  fpd.id::text AS id,
  fpd.flight_id::text AS flight_id,
  fpd.trip_id::text AS trip_id,
  fpd.passenger_participant_id::text AS passenger_participant_id,
  fpd.created_by_user_id::text AS created_by_user_id,
  fpd.reservation_number,
  fpd.seat,
  fpd.check_in_url,
  fpd.boarding_pass_bucket,
  fpd.boarding_pass_object_key,
  fpd.boarding_pass_generation,
  fpd.boarding_pass_content_type,
  fpd.boarding_pass_byte_size,
  fpd.boarding_pass_uploaded_at,
  fpd.created_at,
  fpd.updated_at
FROM flight_personal_details fpd
JOIN trip_participants tp ON tp.id = fpd.passenger_participant_id
WHERE fpd.trip_id = $1::uuid
  AND tp.user_id = $2::uuid
ORDER BY fpd.flight_id ASC
`

type ListMyFlightPersonalDetailsByTripParams struct {
	TripID pgtype.UUID
	UserID pgtype.UUID
}

type ListMyFlightPersonalDetailsByTripRow struct {
	ID                      string
	FlightID                string
	TripID                  string
	PassengerParticipantID  string
	CreatedByUserID         string
	ReservationNumber       pgtype.Text
	Seat                    pgtype.Text
	CheckInUrl              pgtype.Text
	BoardingPassBucket      pgtype.Text
	BoardingPassObjectKey   pgtype.Text
	BoardingPassGeneration  pgtype.Text
	BoardingPassContentType pgtype.Text
	BoardingPassByteSize    pgtype.Int4
	BoardingPassUploadedAt  pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) ListMyFlightPersonalDetailsByTrip(ctx context.Context, arg ListMyFlightPersonalDetailsByTripParams) ([]ListMyFlightPersonalDetailsByTripRow, error) {
	rows, err := q.db.Query(ctx, listMyFlightPersonalDetailsByTrip, arg.TripID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyFlightPersonalDetailsByTripRow
	for rows.Next() {
		var i ListMyFlightPersonalDetailsByTripRow
		if err := rows.Scan(
			&i.ID,
			&i.FlightID,
			&i.TripID,
			&i.PassengerParticipantID,
			&i.CreatedByUserID,
			&i.ReservationNumber,
			&i.Seat,
			&i.CheckInUrl,
			&i.BoardingPassBucket,
			&i.BoardingPassObjectKey,
			&i.BoardingPassGeneration,
			&i.BoardingPassContentType,
			&i.BoardingPassByteSize,
			&i.BoardingPassUploadedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFlightPassengerForUpdate = `-- name: LockFlightPassengerForUpdate :one
SELECT participant_id::text
FROM flight_passengers
WHERE trip_id = $1::uuid
  AND flight_id = $2::uuid
  AND participant_id = $3::uuid
FOR UPDATE
`

type LockFlightPassengerForUpdateParams struct {
	TripID        pgtype.UUID
	FlightID      pgtype.UUID
	ParticipantID pgtype.UUID
}

func (q *Queries) LockFlightPassengerForUpdate(ctx context.Context, arg LockFlightPassengerForUpdateParams) (string, error) {
	row := q.db.QueryRow(ctx, lockFlightPassengerForUpdate, arg.TripID, arg.FlightID, arg.ParticipantID)
	var participant_id string
	err := row.Scan(&participant_id)
	return participant_id, err
}

const lockFlightPersonalDetailForUpdate = `-- name: LockFlightPersonalDetailForUpdate :one
SELECT
  id::text,
  flight_id::text,
  trip_id::text,
  passenger_participant_id::text,
  created_by_user_id::text,
  reservation_number,
  seat,
  check_in_url,
  boarding_pass_bucket,
  boarding_pass_object_key,
  boarding_pass_generation,
  boarding_pass_content_type,
  boarding_pass_byte_size,
  boarding_pass_uploaded_at,
  created_at,
  updated_at
FROM flight_personal_details
WHERE trip_id = $1::uuid
  AND flight_id = $2::uuid
  AND passenger_participant_id = $3::uuid
FOR UPDATE
`

type LockFlightPersonalDetailForUpdateParams struct {
	TripID                 pgtype.UUID
	FlightID               pgtype.UUID
	PassengerParticipantID pgtype.UUID
}

type LockFlightPersonalDetailForUpdateRow struct {
	ID                      string
	FlightID                string
	TripID                  string
	PassengerParticipantID  string
	CreatedByUserID         string
	ReservationNumber       pgtype.Text
	Seat                    pgtype.Text
	CheckInUrl              pgtype.Text
	BoardingPassBucket      pgtype.Text
	BoardingPassObjectKey   pgtype.Text
	BoardingPassGeneration  pgtype.Text
	BoardingPassContentType pgtype.Text
	BoardingPassByteSize    pgtype.Int4
	BoardingPassUploadedAt  pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) LockFlightPersonalDetailForUpdate(ctx context.Context, arg LockFlightPersonalDetailForUpdateParams) (LockFlightPersonalDetailForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockFlightPersonalDetailForUpdate, arg.TripID, arg.FlightID, arg.PassengerParticipantID)
	var i LockFlightPersonalDetailForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.FlightID,
		&i.TripID,
		&i.PassengerParticipantID,
		&i.CreatedByUserID,
		&i.ReservationNumber,
		&i.Seat,
		&i.CheckInUrl,
		&i.BoardingPassBucket,
		&i.BoardingPassObjectKey,
		&i.BoardingPassGeneration,
		&i.BoardingPassContentType,
		&i.BoardingPassByteSize,
		&i.BoardingPassUploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markStorageObjectDeletionJobFailed = `-- name: MarkStorageObjectDeletionJobFailed :exec
UPDATE storage_object_deletion_jobs
SET status = CASE WHEN attempts + 1 >= 5 THEN 'failed' ELSE 'pending' END,
    attempts = attempts + 1,
    next_attempt_at = now() + (interval '1 minute' * LEAST(60, (attempts + 1) * (attempts + 1))),
    last_error = $1,
    updated_at = now()
WHERE id = $2::uuid
`

type MarkStorageObjectDeletionJobFailedParams struct {
	LastError pgtype.Text
	JobID     pgtype.UUID
}

func (q *Queries) MarkStorageObjectDeletionJobFailed(ctx context.Context, arg MarkStorageObjectDeletionJobFailedParams) error {
	_, err := q.db.Exec(ctx, markStorageObjectDeletionJobFailed, arg.LastError, arg.JobID)
	return err
}

const markStorageObjectDeletionJobSucceeded = `-- name: MarkStorageObjectDeletionJobSucceeded :exec
UPDATE storage_object_deletion_jobs
SET status = 'succeeded',
    processed_at = now(),
    updated_at = now(),
    last_error = NULL
WHERE id = $1::uuid
`

func (q *Queries) MarkStorageObjectDeletionJobSucceeded(ctx context.Context, jobID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markStorageObjectDeletionJobSucceeded, jobID)
	return err
}

const upsertFlightBoardingPassMetadata = `-- name: UpsertFlightBoardingPassMetadata :one
INSERT INTO flight_personal_details (
  flight_id,
  trip_id,
  passenger_participant_id,
  created_by_user_id,
  boarding_pass_bucket,
  boarding_pass_object_key,
  boarding_pass_generation,
  boarding_pass_content_type,
  boarding_pass_byte_size,
  boarding_pass_uploaded_at
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
ON CONFLICT (flight_id, passenger_participant_id) DO UPDATE
SET boarding_pass_bucket = EXCLUDED.boarding_pass_bucket,
    boarding_pass_object_key = EXCLUDED.boarding_pass_object_key,
    boarding_pass_generation = EXCLUDED.boarding_pass_generation,
    boarding_pass_content_type = EXCLUDED.boarding_pass_content_type,
    boarding_pass_byte_size = EXCLUDED.boarding_pass_byte_size,
    boarding_pass_uploaded_at = EXCLUDED.boarding_pass_uploaded_at,
    updated_at = now()
RETURNING
  id::text,
  flight_id::text,
  trip_id::text,
  passenger_participant_id::text,
  created_by_user_id::text,
  reservation_number,
  seat,
  check_in_url,
  boarding_pass_bucket,
  boarding_pass_object_key,
  boarding_pass_generation,
  boarding_pass_content_type,
  boarding_pass_byte_size,
  boarding_pass_uploaded_at,
  created_at,
  updated_at
`

type UpsertFlightBoardingPassMetadataParams struct {
	FlightID                pgtype.UUID
	TripID                  pgtype.UUID
	PassengerParticipantID  pgtype.UUID
	CreatedByUserID         pgtype.UUID
	BoardingPassBucket      pgtype.Text
	BoardingPassObjectKey   pgtype.Text
	BoardingPassGeneration  pgtype.Text
	BoardingPassContentType pgtype.Text
	BoardingPassByteSize    pgtype.Int4
	BoardingPassUploadedAt  pgtype.Timestamptz
}

type UpsertFlightBoardingPassMetadataRow struct {
	ID                      string
	FlightID                string
	TripID                  string
	PassengerParticipantID  string
	CreatedByUserID         string
	ReservationNumber       pgtype.Text
	Seat                    pgtype.Text
	CheckInUrl              pgtype.Text
	BoardingPassBucket      pgtype.Text
	BoardingPassObjectKey   pgtype.Text
	BoardingPassGeneration  pgtype.Text
	BoardingPassContentType pgtype.Text
	BoardingPassByteSize    pgtype.Int4
	BoardingPassUploadedAt  pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) UpsertFlightBoardingPassMetadata(ctx context.Context, arg UpsertFlightBoardingPassMetadataParams) (UpsertFlightBoardingPassMetadataRow, error) {
	row := q.db.QueryRow(ctx, upsertFlightBoardingPassMetadata,
		arg.FlightID,
		arg.TripID,
		arg.PassengerParticipantID,
		arg.CreatedByUserID,
		arg.BoardingPassBucket,
		arg.BoardingPassObjectKey,
		arg.BoardingPassGeneration,
		arg.BoardingPassContentType,
		arg.BoardingPassByteSize,
		arg.BoardingPassUploadedAt,
	)
	var i UpsertFlightBoardingPassMetadataRow
	err := row.Scan(
		&i.ID,
		&i.FlightID,
		&i.TripID,
		&i.PassengerParticipantID,
		&i.CreatedByUserID,
		&i.ReservationNumber,
		&i.Seat,
		&i.CheckInUrl,
		&i.BoardingPassBucket,
		&i.BoardingPassObjectKey,
		&i.BoardingPassGeneration,
		&i.BoardingPassContentType,
		&i.BoardingPassByteSize,
		&i.BoardingPassUploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFlightPersonalDetail = `-- name: UpsertFlightPersonalDetail :one
INSERT INTO flight_personal_details (
  flight_id,
  trip_id,
  passenger_participant_id,
  created_by_user_id,
  reservation_number,
  seat,
  check_in_url
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4::uuid,
  $5,
  $6,
  $7
)
ON CONFLICT (flight_id, passenger_participant_id) DO UPDATE
SET reservation_number = EXCLUDED.reservation_number,
    seat = EXCLUDED.seat,
    check_in_url = EXCLUDED.check_in_url,
    updated_at = now()
RETURNING
  id::text,
  flight_id::text,
  trip_id::text,
  passenger_participant_id::text,
  created_by_user_id::text,
  reservation_number,
  seat,
  check_in_url,
  boarding_pass_bucket,
  boarding_pass_object_key,
  boarding_pass_generation,
  boarding_pass_content_type,
  boarding_pass_byte_size,
  boarding_pass_uploaded_at,
  created_at,
  updated_at
`

type UpsertFlightPersonalDetailParams struct {
	FlightID               pgtype.UUID
	TripID                 pgtype.UUID
	PassengerParticipantID pgtype.UUID
	CreatedByUserID        pgtype.UUID
	ReservationNumber      pgtype.Text
	Seat                   pgtype.Text
	CheckInUrl             pgtype.Text
}

type UpsertFlightPersonalDetailRow struct {
	ID                      string
	FlightID                string
	TripID                  string
	PassengerParticipantID  string
	CreatedByUserID         string
	ReservationNumber       pgtype.Text
	Seat                    pgtype.Text
	CheckInUrl              pgtype.Text
	BoardingPassBucket      pgtype.Text
	BoardingPassObjectKey   pgtype.Text
	BoardingPassGeneration  pgtype.Text
	BoardingPassContentType pgtype.Text
	BoardingPassByteSize    pgtype.Int4
	BoardingPassUploadedAt  pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) UpsertFlightPersonalDetail(ctx context.Context, arg UpsertFlightPersonalDetailParams) (UpsertFlightPersonalDetailRow, error) {
	row := q.db.QueryRow(ctx, upsertFlightPersonalDetail,
		arg.FlightID,
		arg.TripID,
		arg.PassengerParticipantID,
		arg.CreatedByUserID,
		arg.ReservationNumber,
		arg.Seat,
		arg.CheckInUrl,
	)
	var i UpsertFlightPersonalDetailRow
	err := row.Scan(
		&i.ID,
		&i.FlightID,
		&i.TripID,
		&i.PassengerParticipantID,
		&i.CreatedByUserID,
		&i.ReservationNumber,
		&i.Seat,
		&i.CheckInUrl,
		&i.BoardingPassBucket,
		&i.BoardingPassObjectKey,
		&i.BoardingPassGeneration,
		&i.BoardingPassContentType,
		&i.BoardingPassByteSize,
		&i.BoardingPassUploadedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
