// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: meetings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
  meeting_id,
  event_type,
  title,
  start_date,
  end_date,
  default_currency,
  status,
  trip_id,
  created_by
) VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8::uuid,
  $9::uuid
)
RETURNING
  id::text,
  meeting_id::text,
  event_type,
  title,
  start_date,
  end_date,
  default_currency,
  status,
  COALESCE(trip_id::text, ''::text)::text AS trip_id,
  created_by::text,
  created_at,
  updated_at
`

type CreateEventParams struct {
	MeetingID       pgtype.UUID
	EventType       string
	Title           string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	Status          string
	TripID          pgtype.UUID
	CreatedBy       pgtype.UUID
}

type CreateEventRow struct {
	ID              string
	MeetingID       string
	EventType       string
	Title           string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	Status          string
	TripID          string
	CreatedBy       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.MeetingID,
		arg.EventType,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.DefaultCurrency,
		arg.Status,
		arg.TripID,
		arg.CreatedBy,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.EventType,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.DefaultCurrency,
		&i.Status,
		&i.TripID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEventParticipant = `-- name: CreateEventParticipant :one
INSERT INTO event_participants (
  event_id,
  meeting_member_id,
  user_id,
  role,
  display_name
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4,
  $5
)
RETURNING
  id::text,
  event_id::text,
  COALESCE(meeting_member_id::text, ''::text)::text AS meeting_member_id,
  user_id::text,
  role,
  display_name,
  joined_at
`

type CreateEventParticipantParams struct {
	EventID         pgtype.UUID
	MeetingMemberID pgtype.UUID
	UserID          pgtype.UUID
	Role            string
	DisplayName     string
}

type CreateEventParticipantRow struct {
	ID              string
	EventID         string
	MeetingMemberID string
	UserID          string
	Role            string
	DisplayName     string
	JoinedAt        pgtype.Timestamptz
}

func (q *Queries) CreateEventParticipant(ctx context.Context, arg CreateEventParticipantParams) (CreateEventParticipantRow, error) {
	row := q.db.QueryRow(ctx, createEventParticipant,
		arg.EventID,
		arg.MeetingMemberID,
		arg.UserID,
		arg.Role,
		arg.DisplayName,
	)
	var i CreateEventParticipantRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.MeetingMemberID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.JoinedAt,
	)
	return i, err
}

const createMeeting = `-- name: CreateMeeting :one
INSERT INTO meetings (
  name,
  visibility,
  created_by
) VALUES (
  $1,
  $2,
  $3::uuid
)
RETURNING
  id::text,
  name,
  visibility,
  created_by::text,
  created_at,
  updated_at
`

type CreateMeetingParams struct {
	Name       string
	Visibility string
	CreatedBy  pgtype.UUID
}

type CreateMeetingRow struct {
	ID         string
	Name       string
	Visibility string
	CreatedBy  string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateMeeting(ctx context.Context, arg CreateMeetingParams) (CreateMeetingRow, error) {
	row := q.db.QueryRow(ctx, createMeeting, arg.Name, arg.Visibility, arg.CreatedBy)
	var i CreateMeetingRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Visibility,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMeetingMember = `-- name: CreateMeetingMember :one
INSERT INTO meeting_members (
  meeting_id,
  user_id,
  role,
  display_name
) VALUES (
  $1::uuid,
  $2::uuid,
  $3,
  $4
)
RETURNING
  id::text,
  meeting_id::text,
  user_id::text,
  role,
  display_name,
  joined_at
`

type CreateMeetingMemberParams struct {
	MeetingID   pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	DisplayName string
}

type CreateMeetingMemberRow struct {
	ID          string
	MeetingID   string
	UserID      string
	Role        string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) CreateMeetingMember(ctx context.Context, arg CreateMeetingMemberParams) (CreateMeetingMemberRow, error) {
	row := q.db.QueryRow(ctx, createMeetingMember,
		arg.MeetingID,
		arg.UserID,
		arg.Role,
		arg.DisplayName,
	)
	var i CreateMeetingMemberRow
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.JoinedAt,
	)
	return i, err
}

const getEventForParticipant = `-- name: GetEventForParticipant :one
SELECT
  e.id::text AS id,
  e.meeting_id::text AS meeting_id,
  m.name AS meeting_name,
  m.visibility AS meeting_visibility,
  e.event_type,
  e.title,
  e.start_date,
  e.end_date,
  e.default_currency,
  e.status,
  COALESCE(e.trip_id::text, ''::text)::text AS trip_id,
  e.created_by::text AS created_by,
  e.created_at,
  e.updated_at,
  m.id::text AS result_meeting_id,
  m.name AS result_meeting_name,
  m.visibility AS result_meeting_visibility,
  m.created_by::text AS result_meeting_created_by,
  m.created_at AS result_meeting_created_at,
  m.updated_at AS result_meeting_updated_at
FROM events e
JOIN meetings m ON m.id = e.meeting_id
JOIN event_participants ep ON ep.event_id = e.id
WHERE e.id = $1::uuid
  AND ep.user_id = $2::uuid
`

type GetEventForParticipantParams struct {
	EventID pgtype.UUID
	UserID  pgtype.UUID
}

type GetEventForParticipantRow struct {
	ID                      string
	MeetingID               string
	MeetingName             string
	MeetingVisibility       string
	EventType               string
	Title                   string
	StartDate               pgtype.Date
	EndDate                 pgtype.Date
	DefaultCurrency         string
	Status                  string
	TripID                  string
	CreatedBy               string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	ResultMeetingID         string
	ResultMeetingName       string
	ResultMeetingVisibility string
	ResultMeetingCreatedBy  string
	ResultMeetingCreatedAt  pgtype.Timestamptz
	ResultMeetingUpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetEventForParticipant(ctx context.Context, arg GetEventForParticipantParams) (GetEventForParticipantRow, error) {
	row := q.db.QueryRow(ctx, getEventForParticipant, arg.EventID, arg.UserID)
	var i GetEventForParticipantRow
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.MeetingName,
		&i.MeetingVisibility,
		&i.EventType,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.DefaultCurrency,
		&i.Status,
		&i.TripID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResultMeetingID,
		&i.ResultMeetingName,
		&i.ResultMeetingVisibility,
		&i.ResultMeetingCreatedBy,
		&i.ResultMeetingCreatedAt,
		&i.ResultMeetingUpdatedAt,
	)
	return i, err
}

const getMeetingCreator = `-- name: GetMeetingCreator :one
SELECT
  id::text,
  display_name
FROM users
WHERE id = $1::uuid
  AND deleted_at IS NULL
`

type GetMeetingCreatorRow struct {
	ID          string
	DisplayName string
}

func (q *Queries) GetMeetingCreator(ctx context.Context, dollar_1 pgtype.UUID) (GetMeetingCreatorRow, error) {
	row := q.db.QueryRow(ctx, getMeetingCreator, dollar_1)
	var i GetMeetingCreatorRow
	err := row.Scan(&i.ID, &i.DisplayName)
	return i, err
}

const getMeetingMemberByMeetingAndUser = `-- name: GetMeetingMemberByMeetingAndUser :one
SELECT
  id::text,
  meeting_id::text,
  user_id::text,
  role,
  display_name,
  joined_at
FROM meeting_members
WHERE meeting_id = $1::uuid
  AND user_id = $2::uuid
`

type GetMeetingMemberByMeetingAndUserParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

type GetMeetingMemberByMeetingAndUserRow struct {
	ID          string
	MeetingID   string
	UserID      string
	Role        string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) GetMeetingMemberByMeetingAndUser(ctx context.Context, arg GetMeetingMemberByMeetingAndUserParams) (GetMeetingMemberByMeetingAndUserRow, error) {
	row := q.db.QueryRow(ctx, getMeetingMemberByMeetingAndUser, arg.Column1, arg.Column2)
	var i GetMeetingMemberByMeetingAndUserRow
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.JoinedAt,
	)
	return i, err
}

const getMeetingMemberForUser = `-- name: GetMeetingMemberForUser :one
SELECT
  id::text,
  meeting_id::text,
  user_id::text,
  role,
  display_name,
  joined_at
FROM meeting_members
WHERE meeting_id = $1::uuid
  AND user_id = $2::uuid
`

type GetMeetingMemberForUserParams struct {
	MeetingID pgtype.UUID
	UserID    pgtype.UUID
}

type GetMeetingMemberForUserRow struct {
	ID          string
	MeetingID   string
	UserID      string
	Role        string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) GetMeetingMemberForUser(ctx context.Context, arg GetMeetingMemberForUserParams) (GetMeetingMemberForUserRow, error) {
	row := q.db.QueryRow(ctx, getMeetingMemberForUser, arg.MeetingID, arg.UserID)
	var i GetMeetingMemberForUserRow
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.JoinedAt,
	)
	return i, err
}

const getSavedMeetingForMember = `-- name: GetSavedMeetingForMember :one
SELECT
  m.id::text,
  m.name,
  m.visibility,
  m.created_by::text,
  m.created_at,
  m.updated_at
FROM meetings m
JOIN meeting_members mm ON mm.meeting_id = m.id
WHERE m.id = $1::uuid
  AND mm.user_id = $2::uuid
  AND m.visibility = 'saved'
`

type GetSavedMeetingForMemberParams struct {
	MeetingID pgtype.UUID
	UserID    pgtype.UUID
}

type GetSavedMeetingForMemberRow struct {
	MID        string
	Name       string
	Visibility string
	MCreatedBy string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetSavedMeetingForMember(ctx context.Context, arg GetSavedMeetingForMemberParams) (GetSavedMeetingForMemberRow, error) {
	row := q.db.QueryRow(ctx, getSavedMeetingForMember, arg.MeetingID, arg.UserID)
	var i GetSavedMeetingForMemberRow
	err := row.Scan(
		&i.MID,
		&i.Name,
		&i.Visibility,
		&i.MCreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsForSavedMeetingByMemberUser = `-- name: ListEventsForSavedMeetingByMemberUser :many
SELECT
  e.id::text AS id,
  e.meeting_id::text AS meeting_id,
  m.name AS meeting_name,
  m.visibility AS meeting_visibility,
  e.event_type,
  e.title,
  e.start_date,
  e.end_date,
  e.default_currency,
  e.status,
  COALESCE(e.trip_id::text, ''::text)::text AS trip_id,
  e.created_by::text AS created_by,
  e.created_at,
  e.updated_at
FROM meetings m
JOIN meeting_members requester ON requester.meeting_id = m.id
JOIN events e ON e.meeting_id = m.id
WHERE m.id = $1::uuid
  AND requester.user_id = $2::uuid
  AND m.visibility = 'saved'
ORDER BY
  e.start_date ASC,
  e.end_date ASC,
  e.created_at DESC,
  e.id DESC
`

type ListEventsForSavedMeetingByMemberUserParams struct {
	MeetingID pgtype.UUID
	UserID    pgtype.UUID
}

type ListEventsForSavedMeetingByMemberUserRow struct {
	ID                string
	MeetingID         string
	MeetingName       string
	MeetingVisibility string
	EventType         string
	Title             string
	StartDate         pgtype.Date
	EndDate           pgtype.Date
	DefaultCurrency   string
	Status            string
	TripID            string
	CreatedBy         string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) ListEventsForSavedMeetingByMemberUser(ctx context.Context, arg ListEventsForSavedMeetingByMemberUserParams) ([]ListEventsForSavedMeetingByMemberUserRow, error) {
	rows, err := q.db.Query(ctx, listEventsForSavedMeetingByMemberUser, arg.MeetingID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsForSavedMeetingByMemberUserRow
	for rows.Next() {
		var i ListEventsForSavedMeetingByMemberUserRow
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.MeetingName,
			&i.MeetingVisibility,
			&i.EventType,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.DefaultCurrency,
			&i.Status,
			&i.TripID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetingMembersForSavedMeetingByMemberUser = `-- name: ListMeetingMembersForSavedMeetingByMemberUser :many
SELECT
  mm.id::text,
  mm.meeting_id::text,
  mm.user_id::text,
  mm.role,
  mm.display_name,
  mm.joined_at
FROM meetings m
JOIN meeting_members requester ON requester.meeting_id = m.id
JOIN meeting_members mm ON mm.meeting_id = m.id
WHERE m.id = $1::uuid
  AND requester.user_id = $2::uuid
  AND m.visibility = 'saved'
ORDER BY
  CASE WHEN mm.user_id = $2::uuid THEN 0 ELSE 1 END,
  mm.joined_at ASC,
  mm.id ASC
`

type ListMeetingMembersForSavedMeetingByMemberUserParams struct {
	MeetingID pgtype.UUID
	UserID    pgtype.UUID
}

type ListMeetingMembersForSavedMeetingByMemberUserRow struct {
	MmID        string
	MmMeetingID string
	MmUserID    string
	Role        string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) ListMeetingMembersForSavedMeetingByMemberUser(ctx context.Context, arg ListMeetingMembersForSavedMeetingByMemberUserParams) ([]ListMeetingMembersForSavedMeetingByMemberUserRow, error) {
	rows, err := q.db.Query(ctx, listMeetingMembersForSavedMeetingByMemberUser, arg.MeetingID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeetingMembersForSavedMeetingByMemberUserRow
	for rows.Next() {
		var i ListMeetingMembersForSavedMeetingByMemberUserRow
		if err := rows.Scan(
			&i.MmID,
			&i.MmMeetingID,
			&i.MmUserID,
			&i.Role,
			&i.DisplayName,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedMeetingsByMemberUser = `-- name: ListSavedMeetingsByMemberUser :many
SELECT
  m.id::text AS id,
  m.name,
  m.visibility,
  (
    SELECT count(*)::int
    FROM meeting_members members
    WHERE members.meeting_id = m.id
  ) AS member_count,
  mm.role AS my_role,
  m.created_at,
  m.updated_at
FROM meetings m
JOIN meeting_members mm ON mm.meeting_id = m.id
WHERE mm.user_id = $1::uuid
  AND m.visibility = 'saved'
ORDER BY m.created_at DESC, m.id DESC
`

type ListSavedMeetingsByMemberUserRow struct {
	ID          string
	Name        string
	Visibility  string
	MemberCount int32
	MyRole      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListSavedMeetingsByMemberUser(ctx context.Context, dollar_1 pgtype.UUID) ([]ListSavedMeetingsByMemberUserRow, error) {
	rows, err := q.db.Query(ctx, listSavedMeetingsByMemberUser, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavedMeetingsByMemberUserRow
	for rows.Next() {
		var i ListSavedMeetingsByMemberUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Visibility,
			&i.MemberCount,
			&i.MyRole,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
