// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppMetadatum struct {
	Key       string
	Value     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AuthIdentity struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	DisplayName     pgtype.Text
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AuthSession struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	LastUsedAt            pgtype.Timestamptz
	RotatedAt             pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type DayLodgingPlace struct {
	TripID      pgtype.UUID
	LodgingDate pgtype.Date
	TripPlaceID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ItineraryItem struct {
	ID            pgtype.UUID
	TripID        pgtype.UUID
	ScheduledDate pgtype.Date
	TripPlaceID   pgtype.UUID
	ItemOrder     int32
	Rank          string
	Version       int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Trip struct {
	ID              pgtype.UUID
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	CreatedBy       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type TripInvite struct {
	ID            pgtype.UUID
	TripID        pgtype.UUID
	Token         string
	CreatedBy     pgtype.UUID
	ExpiresAt     pgtype.Timestamptz
	DeactivatedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type TripParticipant struct {
	ID          pgtype.UUID
	TripID      pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

type TripPlace struct {
	ID        pgtype.UUID
	TripID    pgtype.UUID
	Name      string
	Address   string
	PlaceType string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	DeletedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
