// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppMetadatum struct {
	Key       string
	Value     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AuthIdentity struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	DisplayName     pgtype.Text
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AuthSession struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	RefreshTokenHash      string
	RefreshTokenExpiresAt pgtype.Timestamptz
	RevokedAt             pgtype.Timestamptz
	LastUsedAt            pgtype.Timestamptz
	RotatedAt             pgtype.Timestamptz
	DeviceName            pgtype.Text
	Platform              pgtype.Text
	UserAgent             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type Expense struct {
	ID                 pgtype.UUID
	TripID             pgtype.UUID
	AnchorType         string
	TripDayID          pgtype.UUID
	ScheduleItemID     pgtype.UUID
	ExpenseDate        pgtype.Date
	TripPlaceID        pgtype.UUID
	PlaceName          pgtype.Text
	PlaceAddress       pgtype.Text
	PlaceType          pgtype.Text
	AmountMinor        int64
	Currency           string
	SplitPolicy        string
	PayerParticipantID pgtype.UUID
	PayerDisplayName   string
	Memo               pgtype.Text
	CreatedBy          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type ExpenseSplit struct {
	ID                     pgtype.UUID
	ExpenseID              pgtype.UUID
	ParticipantID          pgtype.UUID
	ParticipantDisplayName string
	AmountMinor            int64
	SplitOrder             int32
	CreatedAt              pgtype.Timestamptz
}

type ScheduleItem struct {
	ID                        pgtype.UUID
	TripID                    pgtype.UUID
	TripDayID                 pgtype.UUID
	TripPlaceID               pgtype.UUID
	ItemOrder                 int32
	Rank                      string
	Version                   int32
	StartTime                 pgtype.Time
	EndTime                   pgtype.Time
	PlaceTitle                pgtype.Text
	PlaceMemo                 pgtype.Text
	ArrivedAt                 pgtype.Timestamptz
	SkippedAt                 pgtype.Timestamptz
	ItemKind                  string
	NonPlaceCategory          pgtype.Text
	NonPlaceTitle             pgtype.Text
	NonPlaceMemo              pgtype.Text
	NonPlaceLink              pgtype.Text
	TransportMode             pgtype.Text
	TransportReferenceNumber  pgtype.Text
	TransportBookingReference pgtype.Text
	TransportOriginText       pgtype.Text
	TransportDestinationText  pgtype.Text
	TransportTerminalText     pgtype.Text
	TransportGateText         pgtype.Text
	DeletedAt                 pgtype.Timestamptz
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type Trip struct {
	ID              pgtype.UUID
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	CreatedBy       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type TripDay struct {
	ID                 pgtype.UUID
	TripID             pgtype.UUID
	Date               pgtype.Date
	DayOrder           int32
	LodgingTripPlaceID pgtype.UUID
	DeletedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type TripInvite struct {
	ID            pgtype.UUID
	TripID        pgtype.UUID
	Token         string
	CreatedBy     pgtype.UUID
	ExpiresAt     pgtype.Timestamptz
	DeactivatedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type TripParticipant struct {
	ID          pgtype.UUID
	TripID      pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

type TripPlace struct {
	ID                pgtype.UUID
	TripID            pgtype.UUID
	Name              string
	Address           string
	PlaceType         string
	Provider          string
	GooglePlaceID     pgtype.Text
	Latitude          pgtype.Float8
	Longitude         pgtype.Float8
	GooglePrimaryType pgtype.Text
	GoogleTypes       []string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	DisplayName     string
	Email           pgtype.Text
	EmailNormalized pgtype.Text
	EmailVerified   bool
	AvatarUrl       pgtype.Text
	DeletedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
