// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotificationPushOutbox = `-- name: ClaimNotificationPushOutbox :many
WITH selected AS (
  SELECT id
  FROM notification_push_outbox
  WHERE status IN ('pending', 'failed')
    AND next_attempt_at <= now()
  ORDER BY next_attempt_at ASC, id ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE notification_push_outbox npo
SET
  status = 'running',
  attempts = attempts + 1,
  claimed_at = now(),
  updated_at = now()
FROM selected
WHERE npo.id = selected.id
RETURNING
  npo.id::text,
  COALESCE(npo.push_token_id::text, '')::text AS push_token_id,
  npo.user_id::text,
  npo.expo_push_token_snapshot,
  npo.title,
  npo.body,
  npo.data_json,
  npo.attempts
`

type ClaimNotificationPushOutboxRow struct {
	NpoID                 string
	PushTokenID           string
	NpoUserID             string
	ExpoPushTokenSnapshot string
	Title                 string
	Body                  string
	DataJson              []byte
	Attempts              int32
}

func (q *Queries) ClaimNotificationPushOutbox(ctx context.Context, limitCount int32) ([]ClaimNotificationPushOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimNotificationPushOutbox, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimNotificationPushOutboxRow
	for rows.Next() {
		var i ClaimNotificationPushOutboxRow
		if err := rows.Scan(
			&i.NpoID,
			&i.PushTokenID,
			&i.NpoUserID,
			&i.ExpoPushTokenSnapshot,
			&i.Title,
			&i.Body,
			&i.DataJson,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNotificationEvent = `-- name: CreateNotificationEvent :one
INSERT INTO notification_events (
  event_type,
  trip_id,
  actor_user_id,
  entity_type,
  entity_id,
  idempotency_key,
  payload_json
) VALUES (
  $1,
  $2::uuid,
  $3::uuid,
  $4,
  $5::uuid,
  $6,
  $7::jsonb
)
RETURNING
  id::text,
  created_at
`

type CreateNotificationEventParams struct {
	EventType      string
	TripID         pgtype.UUID
	ActorUserID    pgtype.UUID
	EntityType     string
	EntityID       pgtype.UUID
	IdempotencyKey string
	PayloadJson    []byte
}

type CreateNotificationEventRow struct {
	ID        string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) (CreateNotificationEventRow, error) {
	row := q.db.QueryRow(ctx, createNotificationEvent,
		arg.EventType,
		arg.TripID,
		arg.ActorUserID,
		arg.EntityType,
		arg.EntityID,
		arg.IdempotencyKey,
		arg.PayloadJson,
	)
	var i CreateNotificationEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createNotificationPushOutbox = `-- name: CreateNotificationPushOutbox :one
INSERT INTO notification_push_outbox (
  notification_id,
  push_token_id,
  user_id,
  provider,
  expo_push_token_snapshot,
  title,
  body,
  data_json
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  'expo',
  $4,
  $5,
  $6,
  $7::jsonb
)
RETURNING id::text
`

type CreateNotificationPushOutboxParams struct {
	NotificationID        pgtype.UUID
	PushTokenID           pgtype.UUID
	UserID                pgtype.UUID
	ExpoPushTokenSnapshot string
	Title                 string
	Body                  string
	DataJson              []byte
}

func (q *Queries) CreateNotificationPushOutbox(ctx context.Context, arg CreateNotificationPushOutboxParams) (string, error) {
	row := q.db.QueryRow(ctx, createNotificationPushOutbox,
		arg.NotificationID,
		arg.PushTokenID,
		arg.UserID,
		arg.ExpoPushTokenSnapshot,
		arg.Title,
		arg.Body,
		arg.DataJson,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createUserNotification = `-- name: CreateUserNotification :one
INSERT INTO user_notifications (
  event_id,
  user_id,
  trip_id,
  recipient_reason,
  title,
  body,
  action_path,
  snapshot_json
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  $4,
  $5,
  $6,
  $7,
  $8::jsonb
)
RETURNING
  id::text,
  user_id::text,
  created_at
`

type CreateUserNotificationParams struct {
	EventID         pgtype.UUID
	UserID          pgtype.UUID
	TripID          pgtype.UUID
	RecipientReason string
	Title           string
	Body            string
	ActionPath      string
	SnapshotJson    []byte
}

type CreateUserNotificationRow struct {
	ID        string
	UserID    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUserNotification(ctx context.Context, arg CreateUserNotificationParams) (CreateUserNotificationRow, error) {
	row := q.db.QueryRow(ctx, createUserNotification,
		arg.EventID,
		arg.UserID,
		arg.TripID,
		arg.RecipientReason,
		arg.Title,
		arg.Body,
		arg.ActionPath,
		arg.SnapshotJson,
	)
	var i CreateUserNotificationRow
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const deactivateActivePushTokenDuplicates = `-- name: DeactivateActivePushTokenDuplicates :exec
UPDATE user_push_tokens
SET
  status = 'revoked',
  revoked_at = now(),
  updated_at = now()
WHERE expo_push_token = $1
  AND status = 'active'
  AND NOT (user_id = $2::uuid AND installation_id = $3)
`

type DeactivateActivePushTokenDuplicatesParams struct {
	ExpoPushToken  string
	UserID         pgtype.UUID
	InstallationID string
}

func (q *Queries) DeactivateActivePushTokenDuplicates(ctx context.Context, arg DeactivateActivePushTokenDuplicatesParams) error {
	_, err := q.db.Exec(ctx, deactivateActivePushTokenDuplicates, arg.ExpoPushToken, arg.UserID, arg.InstallationID)
	return err
}

const listActivePushTokensForUsers = `-- name: ListActivePushTokensForUsers :many
SELECT
  id::text,
  user_id::text,
  installation_id,
  expo_push_token,
  platform
FROM user_push_tokens
WHERE user_id = ANY($1::uuid[])
  AND status = 'active'
ORDER BY user_id ASC, updated_at DESC, id ASC
`

type ListActivePushTokensForUsersRow struct {
	ID             string
	UserID         string
	InstallationID string
	ExpoPushToken  string
	Platform       string
}

func (q *Queries) ListActivePushTokensForUsers(ctx context.Context, userIds []pgtype.UUID) ([]ListActivePushTokensForUsersRow, error) {
	rows, err := q.db.Query(ctx, listActivePushTokensForUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePushTokensForUsersRow
	for rows.Next() {
		var i ListActivePushTokensForUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstallationID,
			&i.ExpoPushToken,
			&i.Platform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT
  un.id::text,
  un.event_id::text,
  ne.event_type,
  un.user_id::text,
  un.trip_id::text,
  un.title,
  un.body,
  un.action_path,
  un.snapshot_json,
  un.read_at,
  un.created_at
FROM user_notifications un
JOIN notification_events ne ON ne.id = un.event_id
WHERE un.user_id = $1::uuid
  AND (
    $2::timestamptz IS NULL
    OR (un.created_at, un.id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY un.created_at DESC, un.id DESC
LIMIT $4
`

type ListUserNotificationsParams struct {
	UserID          pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	LimitCount      int32
}

type ListUserNotificationsRow struct {
	UnID         string
	UnEventID    string
	EventType    string
	UnUserID     string
	UnTripID     string
	Title        string
	Body         string
	ActionPath   string
	SnapshotJson []byte
	ReadAt       pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]ListUserNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listUserNotifications,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserNotificationsRow
	for rows.Next() {
		var i ListUserNotificationsRow
		if err := rows.Scan(
			&i.UnID,
			&i.UnEventID,
			&i.EventType,
			&i.UnUserID,
			&i.UnTripID,
			&i.Title,
			&i.Body,
			&i.ActionPath,
			&i.SnapshotJson,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationPushOutboxDead = `-- name: MarkNotificationPushOutboxDead :exec
UPDATE notification_push_outbox
SET
  status = 'dead',
  last_error = $1,
  processed_at = now(),
  claimed_at = NULL,
  updated_at = now()
WHERE id = $2::uuid
`

type MarkNotificationPushOutboxDeadParams struct {
	LastError pgtype.Text
	OutboxID  pgtype.UUID
}

func (q *Queries) MarkNotificationPushOutboxDead(ctx context.Context, arg MarkNotificationPushOutboxDeadParams) error {
	_, err := q.db.Exec(ctx, markNotificationPushOutboxDead, arg.LastError, arg.OutboxID)
	return err
}

const markNotificationPushOutboxFailed = `-- name: MarkNotificationPushOutboxFailed :exec
UPDATE notification_push_outbox
SET
  status = 'failed',
  next_attempt_at = now() + (interval '1 minute' * LEAST(60, attempts * attempts)),
  last_error = $1,
  claimed_at = NULL,
  updated_at = now()
WHERE id = $2::uuid
`

type MarkNotificationPushOutboxFailedParams struct {
	LastError pgtype.Text
	OutboxID  pgtype.UUID
}

func (q *Queries) MarkNotificationPushOutboxFailed(ctx context.Context, arg MarkNotificationPushOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationPushOutboxFailed, arg.LastError, arg.OutboxID)
	return err
}

const markNotificationPushOutboxSkipped = `-- name: MarkNotificationPushOutboxSkipped :exec
UPDATE notification_push_outbox
SET
  status = 'skipped',
  last_error = $1,
  processed_at = now(),
  claimed_at = NULL,
  updated_at = now()
WHERE id = $2::uuid
`

type MarkNotificationPushOutboxSkippedParams struct {
	LastError pgtype.Text
	OutboxID  pgtype.UUID
}

func (q *Queries) MarkNotificationPushOutboxSkipped(ctx context.Context, arg MarkNotificationPushOutboxSkippedParams) error {
	_, err := q.db.Exec(ctx, markNotificationPushOutboxSkipped, arg.LastError, arg.OutboxID)
	return err
}

const markNotificationPushOutboxSucceeded = `-- name: MarkNotificationPushOutboxSucceeded :exec
UPDATE notification_push_outbox
SET
  status = 'succeeded',
  provider_message_id = $1,
  processed_at = now(),
  claimed_at = NULL,
  updated_at = now()
WHERE id = $2::uuid
`

type MarkNotificationPushOutboxSucceededParams struct {
	ProviderMessageID pgtype.Text
	OutboxID          pgtype.UUID
}

func (q *Queries) MarkNotificationPushOutboxSucceeded(ctx context.Context, arg MarkNotificationPushOutboxSucceededParams) error {
	_, err := q.db.Exec(ctx, markNotificationPushOutboxSucceeded, arg.ProviderMessageID, arg.OutboxID)
	return err
}

const markPushTokenInvalid = `-- name: MarkPushTokenInvalid :exec
UPDATE user_push_tokens
SET
  status = 'invalid',
  invalidated_at = COALESCE(invalidated_at, now()),
  updated_at = now()
WHERE id = $1::uuid
`

func (q *Queries) MarkPushTokenInvalid(ctx context.Context, pushTokenID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markPushTokenInvalid, pushTokenID)
	return err
}

const markUserNotificationRead = `-- name: MarkUserNotificationRead :one
UPDATE user_notifications
SET read_at = COALESCE(read_at, now())
WHERE id = $1::uuid
  AND user_id = $2::uuid
RETURNING
  user_notifications.id::text,
  user_notifications.event_id::text,
  (SELECT ne.event_type FROM notification_events ne WHERE ne.id = user_notifications.event_id) AS event_type,
  user_notifications.user_id::text,
  user_notifications.trip_id::text,
  user_notifications.title,
  user_notifications.body,
  user_notifications.action_path,
  user_notifications.snapshot_json,
  user_notifications.read_at,
  user_notifications.created_at
`

type MarkUserNotificationReadParams struct {
	NotificationID pgtype.UUID
	UserID         pgtype.UUID
}

type MarkUserNotificationReadRow struct {
	UserNotificationsID      string
	UserNotificationsEventID string
	EventType                string
	UserNotificationsUserID  string
	UserNotificationsTripID  string
	Title                    string
	Body                     string
	ActionPath               string
	SnapshotJson             []byte
	ReadAt                   pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
}

func (q *Queries) MarkUserNotificationRead(ctx context.Context, arg MarkUserNotificationReadParams) (MarkUserNotificationReadRow, error) {
	row := q.db.QueryRow(ctx, markUserNotificationRead, arg.NotificationID, arg.UserID)
	var i MarkUserNotificationReadRow
	err := row.Scan(
		&i.UserNotificationsID,
		&i.UserNotificationsEventID,
		&i.EventType,
		&i.UserNotificationsUserID,
		&i.UserNotificationsTripID,
		&i.Title,
		&i.Body,
		&i.ActionPath,
		&i.SnapshotJson,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const recoverStaleNotificationPushOutbox = `-- name: RecoverStaleNotificationPushOutbox :exec
UPDATE notification_push_outbox
SET
  status = 'failed',
  next_attempt_at = now(),
  last_error = COALESCE(last_error, 'worker claim timed out'),
  updated_at = now()
WHERE status = 'running'
  AND claimed_at IS NOT NULL
  AND claimed_at <= $1::timestamptz
`

func (q *Queries) RecoverStaleNotificationPushOutbox(ctx context.Context, staleBefore pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, recoverStaleNotificationPushOutbox, staleBefore)
	return err
}

const revokePushToken = `-- name: RevokePushToken :exec
UPDATE user_push_tokens
SET
  status = 'revoked',
  revoked_at = COALESCE(revoked_at, now()),
  updated_at = now()
WHERE user_id = $1::uuid
  AND installation_id = $2
  AND status = 'active'
`

type RevokePushTokenParams struct {
	UserID         pgtype.UUID
	InstallationID string
}

func (q *Queries) RevokePushToken(ctx context.Context, arg RevokePushTokenParams) error {
	_, err := q.db.Exec(ctx, revokePushToken, arg.UserID, arg.InstallationID)
	return err
}

const upsertPushToken = `-- name: UpsertPushToken :one
INSERT INTO user_push_tokens (
  user_id,
  installation_id,
  expo_push_token,
  platform,
  status,
  last_registered_at,
  revoked_at,
  invalidated_at,
  updated_at
) VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  'active',
  now(),
  NULL,
  NULL,
  now()
)
ON CONFLICT (user_id, installation_id) DO UPDATE
SET
  expo_push_token = EXCLUDED.expo_push_token,
  platform = EXCLUDED.platform,
  status = 'active',
  last_registered_at = now(),
  revoked_at = NULL,
  invalidated_at = NULL,
  updated_at = now()
RETURNING
  id::text,
  user_id::text,
  installation_id,
  expo_push_token,
  platform,
  status,
  last_registered_at
`

type UpsertPushTokenParams struct {
	UserID         pgtype.UUID
	InstallationID string
	ExpoPushToken  string
	Platform       string
}

type UpsertPushTokenRow struct {
	ID               string
	UserID           string
	InstallationID   string
	ExpoPushToken    string
	Platform         string
	Status           string
	LastRegisteredAt pgtype.Timestamptz
}

func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) (UpsertPushTokenRow, error) {
	row := q.db.QueryRow(ctx, upsertPushToken,
		arg.UserID,
		arg.InstallationID,
		arg.ExpoPushToken,
		arg.Platform,
	)
	var i UpsertPushTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.ExpoPushToken,
		&i.Platform,
		&i.Status,
		&i.LastRegisteredAt,
	)
	return i, err
}
