// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: trips.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countScheduleItemsByTripDayAndPlace = `-- name: CountScheduleItemsByTripDayAndPlace :one
SELECT count(*)::int
FROM schedule_items
WHERE trip_id = $1::uuid
  AND trip_day_id = $2::uuid
  AND trip_place_id = $3::uuid
  AND deleted_at IS NULL
`

type CountScheduleItemsByTripDayAndPlaceParams struct {
	TripID      pgtype.UUID
	TripDayID   pgtype.UUID
	TripPlaceID pgtype.UUID
}

func (q *Queries) CountScheduleItemsByTripDayAndPlace(ctx context.Context, arg CountScheduleItemsByTripDayAndPlaceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countScheduleItemsByTripDayAndPlace, arg.TripID, arg.TripDayID, arg.TripPlaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countScheduleItemsByTripPlaceID = `-- name: CountScheduleItemsByTripPlaceID :one
SELECT count(*)::int AS total_count
FROM schedule_items
WHERE trip_id = $1::uuid
  AND trip_place_id = $2::uuid
  AND deleted_at IS NULL
`

type CountScheduleItemsByTripPlaceIDParams struct {
	TripID      pgtype.UUID
	TripPlaceID pgtype.UUID
}

func (q *Queries) CountScheduleItemsByTripPlaceID(ctx context.Context, arg CountScheduleItemsByTripPlaceIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, countScheduleItemsByTripPlaceID, arg.TripID, arg.TripPlaceID)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const countTripDaysByLodgingPlaceID = `-- name: CountTripDaysByLodgingPlaceID :one
SELECT count(*)::int AS total_count
FROM trip_days
WHERE trip_id = $1::uuid
  AND lodging_trip_place_id = $2::uuid
  AND deleted_at IS NULL
`

type CountTripDaysByLodgingPlaceIDParams struct {
	TripID      pgtype.UUID
	TripPlaceID pgtype.UUID
}

func (q *Queries) CountTripDaysByLodgingPlaceID(ctx context.Context, arg CountTripDaysByLodgingPlaceIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, countTripDaysByLodgingPlaceID, arg.TripID, arg.TripPlaceID)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const countTripParticipantsByTripID = `-- name: CountTripParticipantsByTripID :one
SELECT count(*)::int AS total_count
FROM trip_participants
WHERE trip_id = $1::uuid
`

func (q *Queries) CountTripParticipantsByTripID(ctx context.Context, dollar_1 pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countTripParticipantsByTripID, dollar_1)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const createScheduleItemAtEnd = `-- name: CreateScheduleItemAtEnd :one
INSERT INTO schedule_items (
  trip_id,
  trip_day_id,
  trip_place_id,
  item_order,
  rank
) VALUES (
  $1::uuid,
  $2::uuid,
  $3::uuid,
  (
    SELECT COALESCE(MAX(item_order), 0) + 1
    FROM schedule_items
    WHERE trip_day_id = $2::uuid
      AND deleted_at IS NULL
  ),
  lpad(
    (
      SELECT COALESCE(MAX(rank::bigint), 0) + 1024
      FROM schedule_items
      WHERE trip_day_id = $2::uuid
        AND deleted_at IS NULL
    )::text,
    19,
    '0'
  )
)
RETURNING
  id::text,
  item_order,
  version,
  arrived_at,
  skipped_at
`

type CreateScheduleItemAtEndParams struct {
	TripID      pgtype.UUID
	TripDayID   pgtype.UUID
	TripPlaceID pgtype.UUID
}

type CreateScheduleItemAtEndRow struct {
	ID        string
	ItemOrder int32
	Version   int32
	ArrivedAt pgtype.Timestamptz
	SkippedAt pgtype.Timestamptz
}

func (q *Queries) CreateScheduleItemAtEnd(ctx context.Context, arg CreateScheduleItemAtEndParams) (CreateScheduleItemAtEndRow, error) {
	row := q.db.QueryRow(ctx, createScheduleItemAtEnd, arg.TripID, arg.TripDayID, arg.TripPlaceID)
	var i CreateScheduleItemAtEndRow
	err := row.Scan(
		&i.ID,
		&i.ItemOrder,
		&i.Version,
		&i.ArrivedAt,
		&i.SkippedAt,
	)
	return i, err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (
  name,
  start_date,
  end_date,
  default_currency,
  created_by
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5::uuid
)
RETURNING
  id::text,
  name,
  start_date,
  end_date,
  default_currency,
  created_by::text,
  created_at,
  updated_at
`

type CreateTripParams struct {
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	Column5         pgtype.UUID
}

type CreateTripRow struct {
	ID              string
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	CreatedBy       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (CreateTripRow, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.DefaultCurrency,
		arg.Column5,
	)
	var i CreateTripRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.DefaultCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTripInvite = `-- name: CreateTripInvite :one
INSERT INTO trip_invites (
  trip_id,
  token,
  created_by,
  expires_at,
  created_at
) VALUES (
  $1::uuid,
  $2,
  $3::uuid,
  $4,
  $5
)
RETURNING
  id::text,
  trip_id::text,
  token,
  expires_at,
  deactivated_at,
  created_at,
  created_by::text
`

type CreateTripInviteParams struct {
	TripID    pgtype.UUID
	Token     string
	CreatedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type CreateTripInviteRow struct {
	ID            string
	TripID        string
	Token         string
	ExpiresAt     pgtype.Timestamptz
	DeactivatedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	CreatedBy     string
}

func (q *Queries) CreateTripInvite(ctx context.Context, arg CreateTripInviteParams) (CreateTripInviteRow, error) {
	row := q.db.QueryRow(ctx, createTripInvite,
		arg.TripID,
		arg.Token,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i CreateTripInviteRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Token,
		&i.ExpiresAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createTripParticipant = `-- name: CreateTripParticipant :one
INSERT INTO trip_participants (
  trip_id,
  user_id,
  role,
  display_name
) VALUES (
  $1::uuid,
  $2::uuid,
  $3,
  $4
)
RETURNING
  id::text,
  trip_id::text,
  user_id::text,
  role,
  display_name,
  joined_at
`

type CreateTripParticipantParams struct {
	Column1     pgtype.UUID
	Column2     pgtype.UUID
	Role        string
	DisplayName string
}

type CreateTripParticipantRow struct {
	ID          string
	TripID      string
	UserID      string
	Role        string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) CreateTripParticipant(ctx context.Context, arg CreateTripParticipantParams) (CreateTripParticipantRow, error) {
	row := q.db.QueryRow(ctx, createTripParticipant,
		arg.Column1,
		arg.Column2,
		arg.Role,
		arg.DisplayName,
	)
	var i CreateTripParticipantRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.JoinedAt,
	)
	return i, err
}

const createTripPlace = `-- name: CreateTripPlace :one
INSERT INTO trip_places (
  trip_id,
  name,
  address,
  place_type
) VALUES (
  $1::uuid,
  $2,
  $3,
  $4
)
RETURNING
  id::text,
  name,
  place_type,
  address,
  provider,
  google_place_id,
  latitude,
  longitude
`

type CreateTripPlaceParams struct {
	TripID    pgtype.UUID
	Name      string
	Address   string
	PlaceType string
}

type CreateTripPlaceRow struct {
	ID            string
	Name          string
	PlaceType     string
	Address       string
	Provider      string
	GooglePlaceID pgtype.Text
	Latitude      pgtype.Float8
	Longitude     pgtype.Float8
}

func (q *Queries) CreateTripPlace(ctx context.Context, arg CreateTripPlaceParams) (CreateTripPlaceRow, error) {
	row := q.db.QueryRow(ctx, createTripPlace,
		arg.TripID,
		arg.Name,
		arg.Address,
		arg.PlaceType,
	)
	var i CreateTripPlaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaceType,
		&i.Address,
		&i.Provider,
		&i.GooglePlaceID,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const deactivateTripInvite = `-- name: DeactivateTripInvite :exec
UPDATE trip_invites
SET deactivated_at = $1
WHERE id = $2::uuid
`

type DeactivateTripInviteParams struct {
	DeactivatedAt pgtype.Timestamptz
	InviteID      pgtype.UUID
}

func (q *Queries) DeactivateTripInvite(ctx context.Context, arg DeactivateTripInviteParams) error {
	_, err := q.db.Exec(ctx, deactivateTripInvite, arg.DeactivatedAt, arg.InviteID)
	return err
}

const deleteDayLodgingPlace = `-- name: DeleteDayLodgingPlace :exec
UPDATE trip_days
SET lodging_trip_place_id = NULL,
    updated_at = now()
WHERE trip_id = $1::uuid
  AND id = $2::uuid
  AND deleted_at IS NULL
`

type DeleteDayLodgingPlaceParams struct {
	TripID    pgtype.UUID
	TripDayID pgtype.UUID
}

func (q *Queries) DeleteDayLodgingPlace(ctx context.Context, arg DeleteDayLodgingPlaceParams) error {
	_, err := q.db.Exec(ctx, deleteDayLodgingPlace, arg.TripID, arg.TripDayID)
	return err
}

const deleteTripByID = `-- name: DeleteTripByID :one
DELETE FROM trips
WHERE id = $1::uuid
RETURNING id::text
`

func (q *Queries) DeleteTripByID(ctx context.Context, dollar_1 pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteTripByID, dollar_1)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteTripMemberParticipant = `-- name: DeleteTripMemberParticipant :one
DELETE FROM trip_participants
WHERE trip_id = $1::uuid
  AND id = $2::uuid
  AND role = 'member'
RETURNING
  id::text,
  user_id::text
`

type DeleteTripMemberParticipantParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

type DeleteTripMemberParticipantRow struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteTripMemberParticipant(ctx context.Context, arg DeleteTripMemberParticipantParams) (DeleteTripMemberParticipantRow, error) {
	row := q.db.QueryRow(ctx, deleteTripMemberParticipant, arg.Column1, arg.Column2)
	var i DeleteTripMemberParticipantRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const deleteTripPlaceByID = `-- name: DeleteTripPlaceByID :exec
DELETE FROM trip_places
WHERE trip_id = $1::uuid
  AND id = $2::uuid
`

type DeleteTripPlaceByIDParams struct {
	TripID      pgtype.UUID
	TripPlaceID pgtype.UUID
}

func (q *Queries) DeleteTripPlaceByID(ctx context.Context, arg DeleteTripPlaceByIDParams) error {
	_, err := q.db.Exec(ctx, deleteTripPlaceByID, arg.TripID, arg.TripPlaceID)
	return err
}

const getActiveTripDayByTripAndID = `-- name: GetActiveTripDayByTripAndID :one
SELECT
  td.id::text AS id,
  td.date,
  td.day_order,
  COALESCE(tp.id::text, ''::text)::text AS lodging_trip_place_id,
  tp.name AS lodging_place_name,
  tp.place_type AS lodging_place_type,
  tp.address AS lodging_place_address,
  tp.provider AS lodging_place_provider,
  tp.google_place_id AS lodging_google_place_id,
  tp.latitude AS lodging_latitude,
  tp.longitude AS lodging_longitude
FROM trip_days td
LEFT JOIN trip_places tp
  ON tp.id = td.lodging_trip_place_id
 AND tp.trip_id = td.trip_id
WHERE td.trip_id = $1::uuid
  AND td.id = $2::uuid
  AND td.deleted_at IS NULL
`

type GetActiveTripDayByTripAndIDParams struct {
	TripID    pgtype.UUID
	TripDayID pgtype.UUID
}

type GetActiveTripDayByTripAndIDRow struct {
	ID                   string
	Date                 pgtype.Date
	DayOrder             int32
	LodgingTripPlaceID   string
	LodgingPlaceName     pgtype.Text
	LodgingPlaceType     pgtype.Text
	LodgingPlaceAddress  pgtype.Text
	LodgingPlaceProvider pgtype.Text
	LodgingGooglePlaceID pgtype.Text
	LodgingLatitude      pgtype.Float8
	LodgingLongitude     pgtype.Float8
}

func (q *Queries) GetActiveTripDayByTripAndID(ctx context.Context, arg GetActiveTripDayByTripAndIDParams) (GetActiveTripDayByTripAndIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveTripDayByTripAndID, arg.TripID, arg.TripDayID)
	var i GetActiveTripDayByTripAndIDRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.DayOrder,
		&i.LodgingTripPlaceID,
		&i.LodgingPlaceName,
		&i.LodgingPlaceType,
		&i.LodgingPlaceAddress,
		&i.LodgingPlaceProvider,
		&i.LodgingGooglePlaceID,
		&i.LodgingLatitude,
		&i.LodgingLongitude,
	)
	return i, err
}

const getCurrentTripInviteForUpdate = `-- name: GetCurrentTripInviteForUpdate :one
SELECT
  id::text,
  trip_id::text,
  token,
  expires_at,
  deactivated_at,
  created_at,
  created_by::text
FROM trip_invites
WHERE trip_id = $1::uuid
  AND deactivated_at IS NULL
FOR UPDATE
`

type GetCurrentTripInviteForUpdateRow struct {
	ID            string
	TripID        string
	Token         string
	ExpiresAt     pgtype.Timestamptz
	DeactivatedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	CreatedBy     string
}

func (q *Queries) GetCurrentTripInviteForUpdate(ctx context.Context, tripID pgtype.UUID) (GetCurrentTripInviteForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCurrentTripInviteForUpdate, tripID)
	var i GetCurrentTripInviteForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Token,
		&i.ExpiresAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getGoogleTripPlaceByGooglePlaceID = `-- name: GetGoogleTripPlaceByGooglePlaceID :one
SELECT
  id::text AS id,
  name,
  place_type,
  address,
  provider,
  google_place_id,
  latitude,
  longitude
FROM trip_places
WHERE trip_id = $1::uuid
  AND provider = 'google'
  AND google_place_id = $2
`

type GetGoogleTripPlaceByGooglePlaceIDParams struct {
	TripID        pgtype.UUID
	GooglePlaceID pgtype.Text
}

type GetGoogleTripPlaceByGooglePlaceIDRow struct {
	ID            string
	Name          string
	PlaceType     string
	Address       string
	Provider      string
	GooglePlaceID pgtype.Text
	Latitude      pgtype.Float8
	Longitude     pgtype.Float8
}

func (q *Queries) GetGoogleTripPlaceByGooglePlaceID(ctx context.Context, arg GetGoogleTripPlaceByGooglePlaceIDParams) (GetGoogleTripPlaceByGooglePlaceIDRow, error) {
	row := q.db.QueryRow(ctx, getGoogleTripPlaceByGooglePlaceID, arg.TripID, arg.GooglePlaceID)
	var i GetGoogleTripPlaceByGooglePlaceIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaceType,
		&i.Address,
		&i.Provider,
		&i.GooglePlaceID,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getScheduleItemByTripDayAndID = `-- name: GetScheduleItemByTripDayAndID :one
SELECT
  si.id::text AS id,
  si.item_order,
  si.version,
  si.start_time,
  si.end_time,
  si.arrived_at,
  si.skipped_at,
  COALESCE(td.lodging_trip_place_id = si.trip_place_id, false) AS is_lodging,
  tp.id::text AS trip_place_id,
  tp.name AS place_name,
  tp.place_type,
  tp.address,
  tp.provider,
  tp.google_place_id,
  tp.latitude,
  tp.longitude
FROM schedule_items si
JOIN trip_days td
  ON td.id = si.trip_day_id
 AND td.trip_id = si.trip_id
 AND td.deleted_at IS NULL
JOIN trip_places tp
  ON tp.id = si.trip_place_id
 AND tp.trip_id = si.trip_id
WHERE si.trip_id = $1::uuid
  AND si.trip_day_id = $2::uuid
  AND si.id = $3::uuid
  AND si.deleted_at IS NULL
`

type GetScheduleItemByTripDayAndIDParams struct {
	TripID         pgtype.UUID
	TripDayID      pgtype.UUID
	ScheduleItemID pgtype.UUID
}

type GetScheduleItemByTripDayAndIDRow struct {
	ID            string
	ItemOrder     int32
	Version       int32
	StartTime     pgtype.Time
	EndTime       pgtype.Time
	ArrivedAt     pgtype.Timestamptz
	SkippedAt     pgtype.Timestamptz
	IsLodging     interface{}
	TripPlaceID   string
	PlaceName     string
	PlaceType     string
	Address       string
	Provider      string
	GooglePlaceID pgtype.Text
	Latitude      pgtype.Float8
	Longitude     pgtype.Float8
}

func (q *Queries) GetScheduleItemByTripDayAndID(ctx context.Context, arg GetScheduleItemByTripDayAndIDParams) (GetScheduleItemByTripDayAndIDRow, error) {
	row := q.db.QueryRow(ctx, getScheduleItemByTripDayAndID, arg.TripID, arg.TripDayID, arg.ScheduleItemID)
	var i GetScheduleItemByTripDayAndIDRow
	err := row.Scan(
		&i.ID,
		&i.ItemOrder,
		&i.Version,
		&i.StartTime,
		&i.EndTime,
		&i.ArrivedAt,
		&i.SkippedAt,
		&i.IsLodging,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceType,
		&i.Address,
		&i.Provider,
		&i.GooglePlaceID,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getTripByID = `-- name: GetTripByID :one
SELECT
  id::text,
  name,
  start_date,
  end_date,
  default_currency,
  created_by::text,
  created_at,
  updated_at
FROM trips
WHERE id = $1::uuid
`

type GetTripByIDRow struct {
	ID              string
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	CreatedBy       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetTripByID(ctx context.Context, dollar_1 pgtype.UUID) (GetTripByIDRow, error) {
	row := q.db.QueryRow(ctx, getTripByID, dollar_1)
	var i GetTripByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.DefaultCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripInviteForAccept = `-- name: GetTripInviteForAccept :one
SELECT
  ti.id::text,
  ti.trip_id::text,
  t.name AS trip_name,
  ti.expires_at,
  ti.deactivated_at
FROM trip_invites ti
JOIN trips t ON t.id = ti.trip_id
WHERE ti.token = $1
FOR UPDATE OF ti
`

type GetTripInviteForAcceptRow struct {
	TiID          string
	TiTripID      string
	TripName      string
	ExpiresAt     pgtype.Timestamptz
	DeactivatedAt pgtype.Timestamptz
}

func (q *Queries) GetTripInviteForAccept(ctx context.Context, token string) (GetTripInviteForAcceptRow, error) {
	row := q.db.QueryRow(ctx, getTripInviteForAccept, token)
	var i GetTripInviteForAcceptRow
	err := row.Scan(
		&i.TiID,
		&i.TiTripID,
		&i.TripName,
		&i.ExpiresAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getTripParticipantMembership = `-- name: GetTripParticipantMembership :one
SELECT id::text
FROM trip_participants
WHERE trip_id = $1::uuid
  AND user_id = $2::uuid
`

type GetTripParticipantMembershipParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

func (q *Queries) GetTripParticipantMembership(ctx context.Context, arg GetTripParticipantMembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, getTripParticipantMembership, arg.Column1, arg.Column2)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getTripParticipantRole = `-- name: GetTripParticipantRole :one
SELECT role
FROM trip_participants
WHERE trip_id = $1::uuid
  AND user_id = $2::uuid
`

type GetTripParticipantRoleParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

func (q *Queries) GetTripParticipantRole(ctx context.Context, arg GetTripParticipantRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getTripParticipantRole, arg.Column1, arg.Column2)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getTripPlaceSummaryByTripAndPlace = `-- name: GetTripPlaceSummaryByTripAndPlace :one
SELECT
  id::text AS id,
  name,
  place_type,
  address,
  provider,
  google_place_id,
  latitude,
  longitude
FROM trip_places
WHERE trip_id = $1::uuid
  AND id = $2::uuid
`

type GetTripPlaceSummaryByTripAndPlaceParams struct {
	TripID      pgtype.UUID
	TripPlaceID pgtype.UUID
}

type GetTripPlaceSummaryByTripAndPlaceRow struct {
	ID            string
	Name          string
	PlaceType     string
	Address       string
	Provider      string
	GooglePlaceID pgtype.Text
	Latitude      pgtype.Float8
	Longitude     pgtype.Float8
}

func (q *Queries) GetTripPlaceSummaryByTripAndPlace(ctx context.Context, arg GetTripPlaceSummaryByTripAndPlaceParams) (GetTripPlaceSummaryByTripAndPlaceRow, error) {
	row := q.db.QueryRow(ctx, getTripPlaceSummaryByTripAndPlace, arg.TripID, arg.TripPlaceID)
	var i GetTripPlaceSummaryByTripAndPlaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaceType,
		&i.Address,
		&i.Provider,
		&i.GooglePlaceID,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const listActiveTripDaysByTrip = `-- name: ListActiveTripDaysByTrip :many
SELECT
  td.id::text AS id,
  td.date,
  td.day_order,
  COALESCE(tp.id::text, ''::text)::text AS lodging_trip_place_id,
  tp.name AS lodging_place_name,
  tp.place_type AS lodging_place_type,
  tp.address AS lodging_place_address,
  tp.provider AS lodging_place_provider,
  tp.google_place_id AS lodging_google_place_id,
  tp.latitude AS lodging_latitude,
  tp.longitude AS lodging_longitude
FROM trip_days td
LEFT JOIN trip_places tp
  ON tp.id = td.lodging_trip_place_id
 AND tp.trip_id = td.trip_id
WHERE td.trip_id = $1::uuid
  AND td.deleted_at IS NULL
ORDER BY td.day_order ASC, td.date ASC
`

type ListActiveTripDaysByTripRow struct {
	ID                   string
	Date                 pgtype.Date
	DayOrder             int32
	LodgingTripPlaceID   string
	LodgingPlaceName     pgtype.Text
	LodgingPlaceType     pgtype.Text
	LodgingPlaceAddress  pgtype.Text
	LodgingPlaceProvider pgtype.Text
	LodgingGooglePlaceID pgtype.Text
	LodgingLatitude      pgtype.Float8
	LodgingLongitude     pgtype.Float8
}

func (q *Queries) ListActiveTripDaysByTrip(ctx context.Context, dollar_1 pgtype.UUID) ([]ListActiveTripDaysByTripRow, error) {
	rows, err := q.db.Query(ctx, listActiveTripDaysByTrip, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTripDaysByTripRow
	for rows.Next() {
		var i ListActiveTripDaysByTripRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.DayOrder,
			&i.LodgingTripPlaceID,
			&i.LodgingPlaceName,
			&i.LodgingPlaceType,
			&i.LodgingPlaceAddress,
			&i.LodgingPlaceProvider,
			&i.LodgingGooglePlaceID,
			&i.LodgingLatitude,
			&i.LodgingLongitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleItemsByTripDay = `-- name: ListScheduleItemsByTripDay :many
SELECT
  si.id::text AS id,
  si.item_order,
  si.version,
  si.start_time,
  si.end_time,
  si.arrived_at,
  si.skipped_at,
  COALESCE(td.lodging_trip_place_id = si.trip_place_id, false) AS is_lodging,
  tp.id::text AS trip_place_id,
  tp.name AS place_name,
  tp.place_type,
  tp.address,
  tp.provider,
  tp.google_place_id,
  tp.latitude,
  tp.longitude
FROM schedule_items si
JOIN trip_days td
  ON td.id = si.trip_day_id
 AND td.trip_id = si.trip_id
 AND td.deleted_at IS NULL
JOIN trip_places tp
  ON tp.id = si.trip_place_id
 AND tp.trip_id = si.trip_id
WHERE si.trip_id = $1::uuid
  AND si.trip_day_id = $2::uuid
  AND si.deleted_at IS NULL
ORDER BY si.rank ASC, si.id ASC
`

type ListScheduleItemsByTripDayParams struct {
	TripID    pgtype.UUID
	TripDayID pgtype.UUID
}

type ListScheduleItemsByTripDayRow struct {
	ID            string
	ItemOrder     int32
	Version       int32
	StartTime     pgtype.Time
	EndTime       pgtype.Time
	ArrivedAt     pgtype.Timestamptz
	SkippedAt     pgtype.Timestamptz
	IsLodging     interface{}
	TripPlaceID   string
	PlaceName     string
	PlaceType     string
	Address       string
	Provider      string
	GooglePlaceID pgtype.Text
	Latitude      pgtype.Float8
	Longitude     pgtype.Float8
}

func (q *Queries) ListScheduleItemsByTripDay(ctx context.Context, arg ListScheduleItemsByTripDayParams) ([]ListScheduleItemsByTripDayRow, error) {
	rows, err := q.db.Query(ctx, listScheduleItemsByTripDay, arg.TripID, arg.TripDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleItemsByTripDayRow
	for rows.Next() {
		var i ListScheduleItemsByTripDayRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemOrder,
			&i.Version,
			&i.StartTime,
			&i.EndTime,
			&i.ArrivedAt,
			&i.SkippedAt,
			&i.IsLodging,
			&i.TripPlaceID,
			&i.PlaceName,
			&i.PlaceType,
			&i.Address,
			&i.Provider,
			&i.GooglePlaceID,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripParticipantPreviewByTripID = `-- name: ListTripParticipantPreviewByTripID :many
SELECT display_name
FROM trip_participants
WHERE trip_id = $1::uuid
ORDER BY
  CASE WHEN role = 'owner' THEN 0 ELSE 1 END,
  joined_at ASC,
  id ASC
LIMIT 3
`

func (q *Queries) ListTripParticipantPreviewByTripID(ctx context.Context, dollar_1 pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listTripParticipantPreviewByTripID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var display_name string
		if err := rows.Scan(&display_name); err != nil {
			return nil, err
		}
		items = append(items, display_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripParticipantsByTripID = `-- name: ListTripParticipantsByTripID :many
SELECT
  id::text,
  display_name,
  role,
  joined_at
FROM trip_participants
WHERE trip_id = $1::uuid
ORDER BY
  CASE WHEN role = 'owner' THEN 0 ELSE 1 END,
  joined_at ASC,
  id ASC
`

type ListTripParticipantsByTripIDRow struct {
	ID          string
	DisplayName string
	Role        string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) ListTripParticipantsByTripID(ctx context.Context, dollar_1 pgtype.UUID) ([]ListTripParticipantsByTripIDRow, error) {
	rows, err := q.db.Query(ctx, listTripParticipantsByTripID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripParticipantsByTripIDRow
	for rows.Next() {
		var i ListTripParticipantsByTripIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByParticipantUser = `-- name: ListTripsByParticipantUser :many
SELECT
  t.id::text AS id,
  tp.id::text AS participant_id,
  t.name,
  t.start_date,
  t.end_date,
  t.default_currency,
  tp.joined_at,
  t.created_at,
  tp.role AS my_role,
  (
    SELECT count(*)::int
    FROM trip_participants participants
    WHERE participants.trip_id = t.id
  ) AS participant_count
FROM trips t
JOIN trip_participants tp ON tp.trip_id = t.id
WHERE tp.user_id = $1::uuid
ORDER BY tp.joined_at DESC, t.created_at DESC, t.id DESC
`

type ListTripsByParticipantUserRow struct {
	ID               string
	ParticipantID    string
	Name             string
	StartDate        pgtype.Date
	EndDate          pgtype.Date
	DefaultCurrency  string
	JoinedAt         pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	MyRole           string
	ParticipantCount int32
}

func (q *Queries) ListTripsByParticipantUser(ctx context.Context, dollar_1 pgtype.UUID) ([]ListTripsByParticipantUserRow, error) {
	rows, err := q.db.Query(ctx, listTripsByParticipantUser, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripsByParticipantUserRow
	for rows.Next() {
		var i ListTripsByParticipantUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.DefaultCurrency,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.MyRole,
			&i.ParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTripForInvite = `-- name: LockTripForInvite :one
SELECT id::text
FROM trips
WHERE id = $1::uuid
FOR UPDATE
`

func (q *Queries) LockTripForInvite(ctx context.Context, tripID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lockTripForInvite, tripID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setDayLodgingPlace = `-- name: SetDayLodgingPlace :one
WITH updated AS (
  UPDATE trip_days
  SET lodging_trip_place_id = $1::uuid,
      updated_at = now()
  WHERE trip_id = $2::uuid
    AND id = $3::uuid
    AND deleted_at IS NULL
  RETURNING trip_id, lodging_trip_place_id
)
SELECT
  tp.id::text AS id,
  tp.name,
  tp.place_type,
  tp.address,
  tp.provider,
  tp.google_place_id,
  tp.latitude,
  tp.longitude
FROM updated
JOIN trip_places tp
  ON tp.id = updated.lodging_trip_place_id
 AND tp.trip_id = updated.trip_id
`

type SetDayLodgingPlaceParams struct {
	TripPlaceID pgtype.UUID
	TripID      pgtype.UUID
	TripDayID   pgtype.UUID
}

type SetDayLodgingPlaceRow struct {
	ID            string
	Name          string
	PlaceType     string
	Address       string
	Provider      string
	GooglePlaceID pgtype.Text
	Latitude      pgtype.Float8
	Longitude     pgtype.Float8
}

func (q *Queries) SetDayLodgingPlace(ctx context.Context, arg SetDayLodgingPlaceParams) (SetDayLodgingPlaceRow, error) {
	row := q.db.QueryRow(ctx, setDayLodgingPlace, arg.TripPlaceID, arg.TripID, arg.TripDayID)
	var i SetDayLodgingPlaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaceType,
		&i.Address,
		&i.Provider,
		&i.GooglePlaceID,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const softDeleteScheduleItemByTripDayAndID = `-- name: SoftDeleteScheduleItemByTripDayAndID :one
WITH target AS (
  SELECT
    si.id,
    si.trip_id,
    si.trip_day_id,
    tp.id AS trip_place_id,
    tp.name AS place_name,
    tp.address AS place_address,
    tp.place_type
  FROM schedule_items si
  JOIN trip_places tp
    ON tp.id = si.trip_place_id
   AND tp.trip_id = si.trip_id
  WHERE si.trip_id = $1::uuid
    AND si.trip_day_id = $2::uuid
    AND si.id = $3::uuid
    AND si.deleted_at IS NULL
), refreshed_expenses AS (
  UPDATE expenses e
  SET trip_place_id = target.trip_place_id,
      place_name = target.place_name,
      place_address = target.place_address,
      place_type = target.place_type,
      updated_at = now()
  FROM target
  WHERE e.trip_id = target.trip_id
    AND e.trip_day_id = target.trip_day_id
    AND e.schedule_item_id = target.id
    AND e.anchor_type = 'schedule_item'
  RETURNING e.id
), deleted_item AS (
  UPDATE schedule_items si
  SET deleted_at = now(),
      updated_at = now()
  FROM target
  WHERE si.trip_id = target.trip_id
    AND si.trip_day_id = target.trip_day_id
    AND si.id = target.id
  RETURNING target.trip_place_id::text AS trip_place_id
)
SELECT trip_place_id
FROM deleted_item
`

type SoftDeleteScheduleItemByTripDayAndIDParams struct {
	TripID         pgtype.UUID
	TripDayID      pgtype.UUID
	ScheduleItemID pgtype.UUID
}

func (q *Queries) SoftDeleteScheduleItemByTripDayAndID(ctx context.Context, arg SoftDeleteScheduleItemByTripDayAndIDParams) (string, error) {
	row := q.db.QueryRow(ctx, softDeleteScheduleItemByTripDayAndID, arg.TripID, arg.TripDayID, arg.ScheduleItemID)
	var trip_place_id string
	err := row.Scan(&trip_place_id)
	return trip_place_id, err
}

const updateTripBasicInfo = `-- name: UpdateTripBasicInfo :one
UPDATE trips
SET
  name = $2,
  start_date = $3,
  end_date = $4,
  default_currency = $5,
  updated_at = now()
WHERE id = $1::uuid
RETURNING
  id::text,
  name,
  start_date,
  end_date,
  default_currency,
  created_by::text,
  created_at,
  updated_at
`

type UpdateTripBasicInfoParams struct {
	Column1         pgtype.UUID
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
}

type UpdateTripBasicInfoRow struct {
	ID              string
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	CreatedBy       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateTripBasicInfo(ctx context.Context, arg UpdateTripBasicInfoParams) (UpdateTripBasicInfoRow, error) {
	row := q.db.QueryRow(ctx, updateTripBasicInfo,
		arg.Column1,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.DefaultCurrency,
	)
	var i UpdateTripBasicInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.DefaultCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTripPlaceSnapshotByScheduleItem = `-- name: UpdateTripPlaceSnapshotByScheduleItem :one
WITH target AS (
  SELECT
    si.id,
    si.item_order,
    si.version,
    si.start_time,
    si.end_time,
    si.arrived_at,
    si.skipped_at,
    si.trip_place_id,
    si.trip_day_id,
    si.trip_id
  FROM schedule_items si
  JOIN trip_days td
    ON td.id = si.trip_day_id
   AND td.trip_id = si.trip_id
   AND td.deleted_at IS NULL
  WHERE si.trip_id = $1::uuid
    AND si.trip_day_id = $2::uuid
    AND si.id = $3::uuid
    AND si.deleted_at IS NULL
), updated_item AS (
  UPDATE schedule_items si
  SET
    start_time = $4::time,
    end_time = $5::time,
    updated_at = now()
  FROM target
  WHERE si.id = target.id
    AND si.trip_id = target.trip_id
  RETURNING
    si.id,
    si.item_order,
    si.version,
    si.start_time,
    si.end_time,
    si.arrived_at,
    si.skipped_at,
    si.trip_place_id,
    si.trip_day_id,
    si.trip_id
), updated_place AS (
  UPDATE trip_places tp
  SET
    name = $6,
    address = $7,
    place_type = $8,
    updated_at = now()
  FROM target
  WHERE tp.id = target.trip_place_id
    AND tp.trip_id = target.trip_id
  RETURNING
    tp.id::text AS id,
    tp.name,
    tp.place_type,
    tp.address,
    tp.provider,
    tp.google_place_id,
    tp.latitude,
    tp.longitude
)
SELECT
  updated_item.id::text AS id,
  updated_item.item_order,
  updated_item.version,
  updated_item.start_time,
  updated_item.end_time,
  updated_item.arrived_at,
  updated_item.skipped_at,
  COALESCE(td.lodging_trip_place_id = updated_item.trip_place_id, false) AS is_lodging,
  updated_place.id AS trip_place_id,
  updated_place.name AS place_name,
  updated_place.place_type,
  updated_place.address,
  updated_place.provider,
  updated_place.google_place_id,
  updated_place.latitude,
  updated_place.longitude
FROM updated_item
JOIN updated_place ON true
JOIN trip_days td
  ON td.id = updated_item.trip_day_id
 AND td.trip_id = updated_item.trip_id
`

type UpdateTripPlaceSnapshotByScheduleItemParams struct {
	TripID         pgtype.UUID
	TripDayID      pgtype.UUID
	ScheduleItemID pgtype.UUID
	StartTime      pgtype.Time
	EndTime        pgtype.Time
	Name           string
	Address        string
	PlaceType      string
}

type UpdateTripPlaceSnapshotByScheduleItemRow struct {
	ID            string
	ItemOrder     int32
	Version       int32
	StartTime     pgtype.Time
	EndTime       pgtype.Time
	ArrivedAt     pgtype.Timestamptz
	SkippedAt     pgtype.Timestamptz
	IsLodging     interface{}
	TripPlaceID   string
	PlaceName     string
	PlaceType     string
	Address       string
	Provider      string
	GooglePlaceID pgtype.Text
	Latitude      pgtype.Float8
	Longitude     pgtype.Float8
}

func (q *Queries) UpdateTripPlaceSnapshotByScheduleItem(ctx context.Context, arg UpdateTripPlaceSnapshotByScheduleItemParams) (UpdateTripPlaceSnapshotByScheduleItemRow, error) {
	row := q.db.QueryRow(ctx, updateTripPlaceSnapshotByScheduleItem,
		arg.TripID,
		arg.TripDayID,
		arg.ScheduleItemID,
		arg.StartTime,
		arg.EndTime,
		arg.Name,
		arg.Address,
		arg.PlaceType,
	)
	var i UpdateTripPlaceSnapshotByScheduleItemRow
	err := row.Scan(
		&i.ID,
		&i.ItemOrder,
		&i.Version,
		&i.StartTime,
		&i.EndTime,
		&i.ArrivedAt,
		&i.SkippedAt,
		&i.IsLodging,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceType,
		&i.Address,
		&i.Provider,
		&i.GooglePlaceID,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const upsertGoogleTripPlace = `-- name: UpsertGoogleTripPlace :one
INSERT INTO trip_places (
  trip_id,
  name,
  address,
  place_type,
  provider,
  google_place_id,
  latitude,
  longitude,
  google_primary_type,
  google_types
) VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  'google',
  $5,
  $6,
  $7,
  $8,
  $9::text[]
)
ON CONFLICT (trip_id, google_place_id) WHERE provider = 'google' DO UPDATE
SET google_place_id = EXCLUDED.google_place_id
RETURNING
  id::text,
  name,
  place_type,
  address,
  provider,
  google_place_id,
  latitude,
  longitude
`

type UpsertGoogleTripPlaceParams struct {
	TripID            pgtype.UUID
	Name              string
	Address           string
	PlaceType         string
	GooglePlaceID     pgtype.Text
	Latitude          pgtype.Float8
	Longitude         pgtype.Float8
	GooglePrimaryType pgtype.Text
	GoogleTypes       []string
}

type UpsertGoogleTripPlaceRow struct {
	ID            string
	Name          string
	PlaceType     string
	Address       string
	Provider      string
	GooglePlaceID pgtype.Text
	Latitude      pgtype.Float8
	Longitude     pgtype.Float8
}

func (q *Queries) UpsertGoogleTripPlace(ctx context.Context, arg UpsertGoogleTripPlaceParams) (UpsertGoogleTripPlaceRow, error) {
	row := q.db.QueryRow(ctx, upsertGoogleTripPlace,
		arg.TripID,
		arg.Name,
		arg.Address,
		arg.PlaceType,
		arg.GooglePlaceID,
		arg.Latitude,
		arg.Longitude,
		arg.GooglePrimaryType,
		arg.GoogleTypes,
	)
	var i UpsertGoogleTripPlaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaceType,
		&i.Address,
		&i.Provider,
		&i.GooglePlaceID,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}
