// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: trips.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDayLodgingPlacesByTripPlaceID = `-- name: CountDayLodgingPlacesByTripPlaceID :one
SELECT count(*)::int AS total_count
FROM day_lodging_places
WHERE trip_id = $1::uuid
  AND trip_place_id = $2::uuid
`

type CountDayLodgingPlacesByTripPlaceIDParams struct {
	TripID      pgtype.UUID
	TripPlaceID pgtype.UUID
}

func (q *Queries) CountDayLodgingPlacesByTripPlaceID(ctx context.Context, arg CountDayLodgingPlacesByTripPlaceIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, countDayLodgingPlacesByTripPlaceID, arg.TripID, arg.TripPlaceID)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const countItineraryItemsByTripDateAndPlace = `-- name: CountItineraryItemsByTripDateAndPlace :one
SELECT count(*)::int
FROM itinerary_items
WHERE trip_id = $1::uuid
  AND scheduled_date = $2
  AND trip_place_id = $3::uuid
`

type CountItineraryItemsByTripDateAndPlaceParams struct {
	TripID        pgtype.UUID
	ScheduledDate pgtype.Date
	TripPlaceID   pgtype.UUID
}

func (q *Queries) CountItineraryItemsByTripDateAndPlace(ctx context.Context, arg CountItineraryItemsByTripDateAndPlaceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countItineraryItemsByTripDateAndPlace, arg.TripID, arg.ScheduledDate, arg.TripPlaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countItineraryItemsByTripPlaceID = `-- name: CountItineraryItemsByTripPlaceID :one
SELECT count(*)::int AS total_count
FROM itinerary_items
WHERE trip_id = $1::uuid
  AND trip_place_id = $2::uuid
`

type CountItineraryItemsByTripPlaceIDParams struct {
	TripID      pgtype.UUID
	TripPlaceID pgtype.UUID
}

func (q *Queries) CountItineraryItemsByTripPlaceID(ctx context.Context, arg CountItineraryItemsByTripPlaceIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, countItineraryItemsByTripPlaceID, arg.TripID, arg.TripPlaceID)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const countTripParticipantsByTripID = `-- name: CountTripParticipantsByTripID :one
SELECT count(*)::int AS total_count
FROM trip_participants
WHERE trip_id = $1::uuid
`

func (q *Queries) CountTripParticipantsByTripID(ctx context.Context, dollar_1 pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countTripParticipantsByTripID, dollar_1)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const createItineraryItemAtEnd = `-- name: CreateItineraryItemAtEnd :one
INSERT INTO itinerary_items (
  trip_id,
  scheduled_date,
  trip_place_id,
  item_order,
  rank
) VALUES (
  $1::uuid,
  $2,
  $3::uuid,
  (
    SELECT COALESCE(MAX(item_order), 0) + 1
    FROM itinerary_items
    WHERE trip_id = $1::uuid
      AND scheduled_date = $2
  ),
  lpad(
    (
      SELECT COALESCE(MAX(rank::bigint), 0) + 1024
      FROM itinerary_items
      WHERE trip_id = $1::uuid
        AND scheduled_date = $2
    )::text,
    19,
    '0'
  )
)
RETURNING
  id::text,
  item_order,
  version,
  arrived_at
`

type CreateItineraryItemAtEndParams struct {
	TripID        pgtype.UUID
	ScheduledDate pgtype.Date
	TripPlaceID   pgtype.UUID
}

type CreateItineraryItemAtEndRow struct {
	ID        string
	ItemOrder int32
	Version   int32
	ArrivedAt pgtype.Timestamptz
}

func (q *Queries) CreateItineraryItemAtEnd(ctx context.Context, arg CreateItineraryItemAtEndParams) (CreateItineraryItemAtEndRow, error) {
	row := q.db.QueryRow(ctx, createItineraryItemAtEnd, arg.TripID, arg.ScheduledDate, arg.TripPlaceID)
	var i CreateItineraryItemAtEndRow
	err := row.Scan(
		&i.ID,
		&i.ItemOrder,
		&i.Version,
		&i.ArrivedAt,
	)
	return i, err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (
  name,
  start_date,
  end_date,
  default_currency,
  created_by
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5::uuid
)
RETURNING
  id::text,
  name,
  start_date,
  end_date,
  default_currency,
  created_by::text,
  created_at,
  updated_at
`

type CreateTripParams struct {
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	Column5         pgtype.UUID
}

type CreateTripRow struct {
	ID              string
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	CreatedBy       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (CreateTripRow, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.DefaultCurrency,
		arg.Column5,
	)
	var i CreateTripRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.DefaultCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTripInvite = `-- name: CreateTripInvite :one
INSERT INTO trip_invites (
  trip_id,
  token,
  created_by,
  expires_at,
  created_at
) VALUES (
  $1::uuid,
  $2,
  $3::uuid,
  $4,
  $5
)
RETURNING
  id::text,
  trip_id::text,
  token,
  expires_at,
  deactivated_at,
  created_at,
  created_by::text
`

type CreateTripInviteParams struct {
	TripID    pgtype.UUID
	Token     string
	CreatedBy pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type CreateTripInviteRow struct {
	ID            string
	TripID        string
	Token         string
	ExpiresAt     pgtype.Timestamptz
	DeactivatedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	CreatedBy     string
}

func (q *Queries) CreateTripInvite(ctx context.Context, arg CreateTripInviteParams) (CreateTripInviteRow, error) {
	row := q.db.QueryRow(ctx, createTripInvite,
		arg.TripID,
		arg.Token,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i CreateTripInviteRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Token,
		&i.ExpiresAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createTripParticipant = `-- name: CreateTripParticipant :one
INSERT INTO trip_participants (
  trip_id,
  user_id,
  role,
  display_name
) VALUES (
  $1::uuid,
  $2::uuid,
  $3,
  $4
)
RETURNING
  id::text,
  trip_id::text,
  user_id::text,
  role,
  display_name,
  joined_at
`

type CreateTripParticipantParams struct {
	Column1     pgtype.UUID
	Column2     pgtype.UUID
	Role        string
	DisplayName string
}

type CreateTripParticipantRow struct {
	ID          string
	TripID      string
	UserID      string
	Role        string
	DisplayName string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) CreateTripParticipant(ctx context.Context, arg CreateTripParticipantParams) (CreateTripParticipantRow, error) {
	row := q.db.QueryRow(ctx, createTripParticipant,
		arg.Column1,
		arg.Column2,
		arg.Role,
		arg.DisplayName,
	)
	var i CreateTripParticipantRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
		&i.JoinedAt,
	)
	return i, err
}

const createTripPlace = `-- name: CreateTripPlace :one
INSERT INTO trip_places (
  trip_id,
  name,
  address,
  place_type
) VALUES (
  $1::uuid,
  $2,
  $3,
  $4
)
RETURNING
  id::text,
  name,
  place_type,
  address
`

type CreateTripPlaceParams struct {
	TripID    pgtype.UUID
	Name      string
	Address   string
	PlaceType string
}

type CreateTripPlaceRow struct {
	ID        string
	Name      string
	PlaceType string
	Address   string
}

func (q *Queries) CreateTripPlace(ctx context.Context, arg CreateTripPlaceParams) (CreateTripPlaceRow, error) {
	row := q.db.QueryRow(ctx, createTripPlace,
		arg.TripID,
		arg.Name,
		arg.Address,
		arg.PlaceType,
	)
	var i CreateTripPlaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaceType,
		&i.Address,
	)
	return i, err
}

const deactivateTripInvite = `-- name: DeactivateTripInvite :exec
UPDATE trip_invites
SET deactivated_at = $1
WHERE id = $2::uuid
`

type DeactivateTripInviteParams struct {
	DeactivatedAt pgtype.Timestamptz
	InviteID      pgtype.UUID
}

func (q *Queries) DeactivateTripInvite(ctx context.Context, arg DeactivateTripInviteParams) error {
	_, err := q.db.Exec(ctx, deactivateTripInvite, arg.DeactivatedAt, arg.InviteID)
	return err
}

const deleteDayLodgingPlace = `-- name: DeleteDayLodgingPlace :exec
DELETE FROM day_lodging_places
WHERE trip_id = $1::uuid
  AND lodging_date = $2
`

type DeleteDayLodgingPlaceParams struct {
	TripID      pgtype.UUID
	LodgingDate pgtype.Date
}

func (q *Queries) DeleteDayLodgingPlace(ctx context.Context, arg DeleteDayLodgingPlaceParams) error {
	_, err := q.db.Exec(ctx, deleteDayLodgingPlace, arg.TripID, arg.LodgingDate)
	return err
}

const deleteItineraryItemByTripDateAndID = `-- name: DeleteItineraryItemByTripDateAndID :one
DELETE FROM itinerary_items
WHERE trip_id = $1::uuid
  AND scheduled_date = $2
  AND id = $3::uuid
RETURNING trip_place_id::text
`

type DeleteItineraryItemByTripDateAndIDParams struct {
	TripID        pgtype.UUID
	ScheduledDate pgtype.Date
	ItemID        pgtype.UUID
}

func (q *Queries) DeleteItineraryItemByTripDateAndID(ctx context.Context, arg DeleteItineraryItemByTripDateAndIDParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteItineraryItemByTripDateAndID, arg.TripID, arg.ScheduledDate, arg.ItemID)
	var trip_place_id string
	err := row.Scan(&trip_place_id)
	return trip_place_id, err
}

const deleteTripByID = `-- name: DeleteTripByID :one
DELETE FROM trips
WHERE id = $1::uuid
RETURNING id::text
`

func (q *Queries) DeleteTripByID(ctx context.Context, dollar_1 pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteTripByID, dollar_1)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteTripPlaceByID = `-- name: DeleteTripPlaceByID :exec
DELETE FROM trip_places
WHERE trip_id = $1::uuid
  AND id = $2::uuid
`

type DeleteTripPlaceByIDParams struct {
	TripID      pgtype.UUID
	TripPlaceID pgtype.UUID
}

func (q *Queries) DeleteTripPlaceByID(ctx context.Context, arg DeleteTripPlaceByIDParams) error {
	_, err := q.db.Exec(ctx, deleteTripPlaceByID, arg.TripID, arg.TripPlaceID)
	return err
}

const getCurrentTripInviteForUpdate = `-- name: GetCurrentTripInviteForUpdate :one
SELECT
  id::text,
  trip_id::text,
  token,
  expires_at,
  deactivated_at,
  created_at,
  created_by::text
FROM trip_invites
WHERE trip_id = $1::uuid
  AND deactivated_at IS NULL
FOR UPDATE
`

type GetCurrentTripInviteForUpdateRow struct {
	ID            string
	TripID        string
	Token         string
	ExpiresAt     pgtype.Timestamptz
	DeactivatedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	CreatedBy     string
}

func (q *Queries) GetCurrentTripInviteForUpdate(ctx context.Context, tripID pgtype.UUID) (GetCurrentTripInviteForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCurrentTripInviteForUpdate, tripID)
	var i GetCurrentTripInviteForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Token,
		&i.ExpiresAt,
		&i.DeactivatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getDayLodgingPlaceByTripAndDate = `-- name: GetDayLodgingPlaceByTripAndDate :one
SELECT
  tp.id::text AS id,
  tp.name,
  tp.place_type,
  tp.address
FROM day_lodging_places dlp
JOIN trip_places tp
  ON tp.id = dlp.trip_place_id
 AND tp.trip_id = dlp.trip_id
WHERE dlp.trip_id = $1::uuid
  AND dlp.lodging_date = $2
`

type GetDayLodgingPlaceByTripAndDateParams struct {
	TripID      pgtype.UUID
	LodgingDate pgtype.Date
}

type GetDayLodgingPlaceByTripAndDateRow struct {
	ID        string
	Name      string
	PlaceType string
	Address   string
}

func (q *Queries) GetDayLodgingPlaceByTripAndDate(ctx context.Context, arg GetDayLodgingPlaceByTripAndDateParams) (GetDayLodgingPlaceByTripAndDateRow, error) {
	row := q.db.QueryRow(ctx, getDayLodgingPlaceByTripAndDate, arg.TripID, arg.LodgingDate)
	var i GetDayLodgingPlaceByTripAndDateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaceType,
		&i.Address,
	)
	return i, err
}

const getGoogleTripPlaceByGooglePlaceID = `-- name: GetGoogleTripPlaceByGooglePlaceID :one
SELECT
  id::text AS id,
  name,
  place_type,
  address
FROM trip_places
WHERE trip_id = $1::uuid
  AND provider = 'google'
  AND google_place_id = $2
`

type GetGoogleTripPlaceByGooglePlaceIDParams struct {
	TripID        pgtype.UUID
	GooglePlaceID pgtype.Text
}

type GetGoogleTripPlaceByGooglePlaceIDRow struct {
	ID        string
	Name      string
	PlaceType string
	Address   string
}

func (q *Queries) GetGoogleTripPlaceByGooglePlaceID(ctx context.Context, arg GetGoogleTripPlaceByGooglePlaceIDParams) (GetGoogleTripPlaceByGooglePlaceIDRow, error) {
	row := q.db.QueryRow(ctx, getGoogleTripPlaceByGooglePlaceID, arg.TripID, arg.GooglePlaceID)
	var i GetGoogleTripPlaceByGooglePlaceIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaceType,
		&i.Address,
	)
	return i, err
}

const getItineraryItemByTripDateAndID = `-- name: GetItineraryItemByTripDateAndID :one
SELECT
  ii.id::text AS id,
  ii.item_order,
  ii.version,
  ii.arrived_at,
  (dlp.trip_place_id IS NOT NULL) AS is_lodging,
  tp.id::text AS trip_place_id,
  tp.name AS place_name,
  tp.place_type,
  tp.address
FROM itinerary_items ii
JOIN trip_places tp
  ON tp.id = ii.trip_place_id
 AND tp.trip_id = ii.trip_id
LEFT JOIN day_lodging_places dlp
  ON dlp.trip_id = ii.trip_id
 AND dlp.lodging_date = ii.scheduled_date
 AND dlp.trip_place_id = ii.trip_place_id
WHERE ii.trip_id = $1::uuid
  AND ii.scheduled_date = $2
  AND ii.id = $3::uuid
`

type GetItineraryItemByTripDateAndIDParams struct {
	TripID        pgtype.UUID
	ScheduledDate pgtype.Date
	ItemID        pgtype.UUID
}

type GetItineraryItemByTripDateAndIDRow struct {
	ID          string
	ItemOrder   int32
	Version     int32
	ArrivedAt   pgtype.Timestamptz
	IsLodging   interface{}
	TripPlaceID string
	PlaceName   string
	PlaceType   string
	Address     string
}

func (q *Queries) GetItineraryItemByTripDateAndID(ctx context.Context, arg GetItineraryItemByTripDateAndIDParams) (GetItineraryItemByTripDateAndIDRow, error) {
	row := q.db.QueryRow(ctx, getItineraryItemByTripDateAndID, arg.TripID, arg.ScheduledDate, arg.ItemID)
	var i GetItineraryItemByTripDateAndIDRow
	err := row.Scan(
		&i.ID,
		&i.ItemOrder,
		&i.Version,
		&i.ArrivedAt,
		&i.IsLodging,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceType,
		&i.Address,
	)
	return i, err
}

const getTripByID = `-- name: GetTripByID :one
SELECT
  id::text,
  name,
  start_date,
  end_date,
  default_currency,
  created_by::text,
  created_at,
  updated_at
FROM trips
WHERE id = $1::uuid
`

type GetTripByIDRow struct {
	ID              string
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	CreatedBy       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetTripByID(ctx context.Context, dollar_1 pgtype.UUID) (GetTripByIDRow, error) {
	row := q.db.QueryRow(ctx, getTripByID, dollar_1)
	var i GetTripByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.DefaultCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripInviteForAccept = `-- name: GetTripInviteForAccept :one
SELECT
  ti.id::text,
  ti.trip_id::text,
  t.name AS trip_name,
  ti.expires_at,
  ti.deactivated_at
FROM trip_invites ti
JOIN trips t ON t.id = ti.trip_id
WHERE ti.token = $1
FOR UPDATE OF ti
`

type GetTripInviteForAcceptRow struct {
	TiID          string
	TiTripID      string
	TripName      string
	ExpiresAt     pgtype.Timestamptz
	DeactivatedAt pgtype.Timestamptz
}

func (q *Queries) GetTripInviteForAccept(ctx context.Context, token string) (GetTripInviteForAcceptRow, error) {
	row := q.db.QueryRow(ctx, getTripInviteForAccept, token)
	var i GetTripInviteForAcceptRow
	err := row.Scan(
		&i.TiID,
		&i.TiTripID,
		&i.TripName,
		&i.ExpiresAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getTripParticipantMembership = `-- name: GetTripParticipantMembership :one
SELECT id::text
FROM trip_participants
WHERE trip_id = $1::uuid
  AND user_id = $2::uuid
`

type GetTripParticipantMembershipParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

func (q *Queries) GetTripParticipantMembership(ctx context.Context, arg GetTripParticipantMembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, getTripParticipantMembership, arg.Column1, arg.Column2)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getTripParticipantRole = `-- name: GetTripParticipantRole :one
SELECT role
FROM trip_participants
WHERE trip_id = $1::uuid
  AND user_id = $2::uuid
`

type GetTripParticipantRoleParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

func (q *Queries) GetTripParticipantRole(ctx context.Context, arg GetTripParticipantRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getTripParticipantRole, arg.Column1, arg.Column2)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getTripPlaceSummaryByTripAndPlace = `-- name: GetTripPlaceSummaryByTripAndPlace :one
SELECT
  id::text AS id,
  name,
  place_type,
  address
FROM trip_places
WHERE trip_id = $1::uuid
  AND id = $2::uuid
`

type GetTripPlaceSummaryByTripAndPlaceParams struct {
	TripID      pgtype.UUID
	TripPlaceID pgtype.UUID
}

type GetTripPlaceSummaryByTripAndPlaceRow struct {
	ID        string
	Name      string
	PlaceType string
	Address   string
}

func (q *Queries) GetTripPlaceSummaryByTripAndPlace(ctx context.Context, arg GetTripPlaceSummaryByTripAndPlaceParams) (GetTripPlaceSummaryByTripAndPlaceRow, error) {
	row := q.db.QueryRow(ctx, getTripPlaceSummaryByTripAndPlace, arg.TripID, arg.TripPlaceID)
	var i GetTripPlaceSummaryByTripAndPlaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaceType,
		&i.Address,
	)
	return i, err
}

const listDayLodgingPlacesByTrip = `-- name: ListDayLodgingPlacesByTrip :many
SELECT
  dlp.lodging_date,
  tp.id::text AS id,
  tp.name,
  tp.place_type,
  tp.address
FROM day_lodging_places dlp
JOIN trip_places tp
  ON tp.id = dlp.trip_place_id
 AND tp.trip_id = dlp.trip_id
WHERE dlp.trip_id = $1::uuid
ORDER BY dlp.lodging_date ASC
`

type ListDayLodgingPlacesByTripRow struct {
	LodgingDate pgtype.Date
	ID          string
	Name        string
	PlaceType   string
	Address     string
}

func (q *Queries) ListDayLodgingPlacesByTrip(ctx context.Context, dollar_1 pgtype.UUID) ([]ListDayLodgingPlacesByTripRow, error) {
	rows, err := q.db.Query(ctx, listDayLodgingPlacesByTrip, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDayLodgingPlacesByTripRow
	for rows.Next() {
		var i ListDayLodgingPlacesByTripRow
		if err := rows.Scan(
			&i.LodgingDate,
			&i.ID,
			&i.Name,
			&i.PlaceType,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItineraryItemsByTripAndDate = `-- name: ListItineraryItemsByTripAndDate :many
SELECT
  ii.id::text AS id,
  ii.version,
  ii.arrived_at,
  (dlp.trip_place_id IS NOT NULL) AS is_lodging,
  tp.id::text AS trip_place_id,
  tp.name AS place_name,
  tp.place_type,
  tp.address
FROM itinerary_items ii
JOIN trip_places tp
  ON tp.id = ii.trip_place_id
 AND tp.trip_id = ii.trip_id
LEFT JOIN day_lodging_places dlp
  ON dlp.trip_id = ii.trip_id
 AND dlp.lodging_date = ii.scheduled_date
 AND dlp.trip_place_id = ii.trip_place_id
WHERE ii.trip_id = $1::uuid
  AND ii.scheduled_date = $2
ORDER BY ii.rank ASC, ii.id ASC
`

type ListItineraryItemsByTripAndDateParams struct {
	Column1       pgtype.UUID
	ScheduledDate pgtype.Date
}

type ListItineraryItemsByTripAndDateRow struct {
	ID          string
	Version     int32
	ArrivedAt   pgtype.Timestamptz
	IsLodging   interface{}
	TripPlaceID string
	PlaceName   string
	PlaceType   string
	Address     string
}

func (q *Queries) ListItineraryItemsByTripAndDate(ctx context.Context, arg ListItineraryItemsByTripAndDateParams) ([]ListItineraryItemsByTripAndDateRow, error) {
	rows, err := q.db.Query(ctx, listItineraryItemsByTripAndDate, arg.Column1, arg.ScheduledDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItineraryItemsByTripAndDateRow
	for rows.Next() {
		var i ListItineraryItemsByTripAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.ArrivedAt,
			&i.IsLodging,
			&i.TripPlaceID,
			&i.PlaceName,
			&i.PlaceType,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripParticipantPreviewByTripID = `-- name: ListTripParticipantPreviewByTripID :many
SELECT display_name
FROM trip_participants
WHERE trip_id = $1::uuid
ORDER BY
  CASE WHEN role = 'owner' THEN 0 ELSE 1 END,
  joined_at ASC,
  id ASC
LIMIT 3
`

func (q *Queries) ListTripParticipantPreviewByTripID(ctx context.Context, dollar_1 pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listTripParticipantPreviewByTripID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var display_name string
		if err := rows.Scan(&display_name); err != nil {
			return nil, err
		}
		items = append(items, display_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripParticipantsByTripID = `-- name: ListTripParticipantsByTripID :many
SELECT
  id::text,
  display_name,
  role,
  joined_at
FROM trip_participants
WHERE trip_id = $1::uuid
ORDER BY
  CASE WHEN role = 'owner' THEN 0 ELSE 1 END,
  joined_at ASC,
  id ASC
`

type ListTripParticipantsByTripIDRow struct {
	ID          string
	DisplayName string
	Role        string
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) ListTripParticipantsByTripID(ctx context.Context, dollar_1 pgtype.UUID) ([]ListTripParticipantsByTripIDRow, error) {
	rows, err := q.db.Query(ctx, listTripParticipantsByTripID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripParticipantsByTripIDRow
	for rows.Next() {
		var i ListTripParticipantsByTripIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByParticipantUser = `-- name: ListTripsByParticipantUser :many
SELECT
  t.id::text AS id,
  t.name,
  t.start_date,
  t.end_date,
  t.default_currency,
  tp.joined_at,
  t.created_at,
  tp.role AS my_role,
  (
    SELECT count(*)::int
    FROM trip_participants participants
    WHERE participants.trip_id = t.id
  ) AS participant_count
FROM trips t
JOIN trip_participants tp ON tp.trip_id = t.id
WHERE tp.user_id = $1::uuid
ORDER BY tp.joined_at DESC, t.created_at DESC, t.id DESC
`

type ListTripsByParticipantUserRow struct {
	ID               string
	Name             string
	StartDate        pgtype.Date
	EndDate          pgtype.Date
	DefaultCurrency  string
	JoinedAt         pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	MyRole           string
	ParticipantCount int32
}

func (q *Queries) ListTripsByParticipantUser(ctx context.Context, dollar_1 pgtype.UUID) ([]ListTripsByParticipantUserRow, error) {
	rows, err := q.db.Query(ctx, listTripsByParticipantUser, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripsByParticipantUserRow
	for rows.Next() {
		var i ListTripsByParticipantUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.DefaultCurrency,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.MyRole,
			&i.ParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTripForInvite = `-- name: LockTripForInvite :one
SELECT id::text
FROM trips
WHERE id = $1::uuid
FOR UPDATE
`

func (q *Queries) LockTripForInvite(ctx context.Context, tripID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lockTripForInvite, tripID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setDayLodgingPlace = `-- name: SetDayLodgingPlace :one
WITH upserted AS (
  INSERT INTO day_lodging_places (trip_id, lodging_date, trip_place_id)
  VALUES ($1::uuid, $2, $3::uuid)
  ON CONFLICT (trip_id, lodging_date) DO UPDATE
  SET
    trip_place_id = EXCLUDED.trip_place_id,
    updated_at = now()
  RETURNING trip_id, trip_place_id
)
SELECT
  tp.id::text AS id,
  tp.name,
  tp.place_type,
  tp.address
FROM upserted
JOIN trip_places tp
  ON tp.id = upserted.trip_place_id
 AND tp.trip_id = upserted.trip_id
`

type SetDayLodgingPlaceParams struct {
	TripID      pgtype.UUID
	LodgingDate pgtype.Date
	TripPlaceID pgtype.UUID
}

type SetDayLodgingPlaceRow struct {
	ID        string
	Name      string
	PlaceType string
	Address   string
}

func (q *Queries) SetDayLodgingPlace(ctx context.Context, arg SetDayLodgingPlaceParams) (SetDayLodgingPlaceRow, error) {
	row := q.db.QueryRow(ctx, setDayLodgingPlace, arg.TripID, arg.LodgingDate, arg.TripPlaceID)
	var i SetDayLodgingPlaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaceType,
		&i.Address,
	)
	return i, err
}

const updateTripBasicInfo = `-- name: UpdateTripBasicInfo :one
UPDATE trips
SET
  name = $2,
  start_date = $3,
  end_date = $4,
  default_currency = $5,
  updated_at = now()
WHERE id = $1::uuid
RETURNING
  id::text,
  name,
  start_date,
  end_date,
  default_currency,
  created_by::text,
  created_at,
  updated_at
`

type UpdateTripBasicInfoParams struct {
	Column1         pgtype.UUID
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
}

type UpdateTripBasicInfoRow struct {
	ID              string
	Name            string
	StartDate       pgtype.Date
	EndDate         pgtype.Date
	DefaultCurrency string
	CreatedBy       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateTripBasicInfo(ctx context.Context, arg UpdateTripBasicInfoParams) (UpdateTripBasicInfoRow, error) {
	row := q.db.QueryRow(ctx, updateTripBasicInfo,
		arg.Column1,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.DefaultCurrency,
	)
	var i UpdateTripBasicInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.DefaultCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTripPlaceSnapshotByItineraryItem = `-- name: UpdateTripPlaceSnapshotByItineraryItem :one
WITH target AS (
  SELECT
    ii.id,
    ii.item_order,
    ii.version,
    ii.arrived_at,
    ii.trip_place_id
  FROM itinerary_items ii
  WHERE ii.trip_id = $1::uuid
    AND ii.scheduled_date = $2
    AND ii.id = $3::uuid
), updated_place AS (
  UPDATE trip_places tp
  SET
    name = $4,
    address = $5,
    place_type = $6,
    updated_at = now()
  FROM target
  WHERE tp.id = target.trip_place_id
    AND tp.trip_id = $1::uuid
  RETURNING
    tp.id::text AS id,
    tp.name,
    tp.place_type,
    tp.address
)
SELECT
  target.id::text AS id,
  target.item_order,
  target.version,
  target.arrived_at,
  (dlp.trip_place_id IS NOT NULL) AS is_lodging,
  updated_place.id AS trip_place_id,
  updated_place.name AS place_name,
  updated_place.place_type,
  updated_place.address
FROM target
JOIN updated_place ON true
LEFT JOIN day_lodging_places dlp
  ON dlp.trip_id = $1::uuid
 AND dlp.lodging_date = $2
 AND dlp.trip_place_id = target.trip_place_id
`

type UpdateTripPlaceSnapshotByItineraryItemParams struct {
	TripID        pgtype.UUID
	ScheduledDate pgtype.Date
	ItemID        pgtype.UUID
	Name          string
	Address       string
	PlaceType     string
}

type UpdateTripPlaceSnapshotByItineraryItemRow struct {
	ID          string
	ItemOrder   int32
	Version     int32
	ArrivedAt   pgtype.Timestamptz
	IsLodging   interface{}
	TripPlaceID string
	PlaceName   string
	PlaceType   string
	Address     string
}

func (q *Queries) UpdateTripPlaceSnapshotByItineraryItem(ctx context.Context, arg UpdateTripPlaceSnapshotByItineraryItemParams) (UpdateTripPlaceSnapshotByItineraryItemRow, error) {
	row := q.db.QueryRow(ctx, updateTripPlaceSnapshotByItineraryItem,
		arg.TripID,
		arg.ScheduledDate,
		arg.ItemID,
		arg.Name,
		arg.Address,
		arg.PlaceType,
	)
	var i UpdateTripPlaceSnapshotByItineraryItemRow
	err := row.Scan(
		&i.ID,
		&i.ItemOrder,
		&i.Version,
		&i.ArrivedAt,
		&i.IsLodging,
		&i.TripPlaceID,
		&i.PlaceName,
		&i.PlaceType,
		&i.Address,
	)
	return i, err
}

const upsertGoogleTripPlace = `-- name: UpsertGoogleTripPlace :one
INSERT INTO trip_places (
  trip_id,
  name,
  address,
  place_type,
  provider,
  google_place_id,
  latitude,
  longitude,
  google_primary_type,
  google_types
) VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  'google',
  $5,
  $6,
  $7,
  $8,
  $9::text[]
)
ON CONFLICT (trip_id, google_place_id) WHERE provider = 'google' DO UPDATE
SET google_place_id = EXCLUDED.google_place_id
RETURNING
  id::text,
  name,
  place_type,
  address
`

type UpsertGoogleTripPlaceParams struct {
	TripID            pgtype.UUID
	Name              string
	Address           string
	PlaceType         string
	GooglePlaceID     pgtype.Text
	Latitude          pgtype.Float8
	Longitude         pgtype.Float8
	GooglePrimaryType pgtype.Text
	GoogleTypes       []string
}

type UpsertGoogleTripPlaceRow struct {
	ID        string
	Name      string
	PlaceType string
	Address   string
}

func (q *Queries) UpsertGoogleTripPlace(ctx context.Context, arg UpsertGoogleTripPlaceParams) (UpsertGoogleTripPlaceRow, error) {
	row := q.db.QueryRow(ctx, upsertGoogleTripPlace,
		arg.TripID,
		arg.Name,
		arg.Address,
		arg.PlaceType,
		arg.GooglePlaceID,
		arg.Latitude,
		arg.Longitude,
		arg.GooglePrimaryType,
		arg.GoogleTypes,
	)
	var i UpsertGoogleTripPlaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PlaceType,
		&i.Address,
	)
	return i, err
}
