import { StyleSheet } from 'react-native';

import { theme } from '../design';

export const styles = StyleSheet.create({
  actionColumn: {
    gap: theme.space[2],
    minWidth: 88,
  },
  address: {
    color: theme.color.textMuted,
    flexShrink: 1,
    fontFamily: theme.font.family.regular,
    fontSize: theme.font.size.caption,
  },
  optionTitle: {
    color: theme.color.textStrong,
    fontFamily: theme.font.family.bold,
    fontSize: theme.font.size.subhead,
    fontWeight: theme.font.weight.bold,
  },
  placeDetailCard: {
    backgroundColor: theme.color.surfaceSunken,
    borderColor: theme.color.borderSubtle,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    gap: theme.space[3],
    padding: theme.space[4],
  },
  placeType: {
    color: theme.color.primaryTextOnLight,
    fontFamily: theme.font.family.semibold,
    fontSize: theme.font.size.caption,
    fontWeight: theme.font.weight.semibold,
  },
  map: {
    width: '100%',
  },
  mapCollapsed: {
    height: 520,
  },
  mapExpanded: {
    height: 260,
  },
  mapSearch: {
    borderColor: theme.color.borderSubtle,
    borderRadius: theme.radius.xl,
    borderWidth: 1,
    height: 640,
    maxWidth: theme.layout.cardMaxW,
    overflow: 'hidden',
    width: '100%',
  },
  mapFullScreenRoot: {
    backgroundColor: theme.color.bg,
    flex: 1,
  },
  mapSearchFullScreen: {
    flex: 1,
  },
  dayChipsOverlay: {
    left: 0,
    position: 'absolute',
    right: theme.space[4] + 44 + theme.space[2],
    top: theme.space[4],
    zIndex: 4,
  },
  bookmarkLayerChip: {
    alignSelf: 'flex-start',
    backgroundColor: theme.color.surface,
    borderColor: theme.color.borderDefault,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    marginBottom: theme.space[2],
    marginLeft: theme.space[4],
    minHeight: theme.layout.controlHSm,
    paddingHorizontal: theme.space[4],
    paddingVertical: theme.space[2],
    ...theme.shadow.xs,
  },
  bookmarkLayerChipSelected: {
    backgroundColor: theme.color.primary,
    borderColor: theme.color.primary,
  },
  bookmarkLayerChipText: {
    color: theme.color.textBody,
    fontFamily: theme.font.family.bold,
    fontSize: theme.font.size.label,
    fontWeight: theme.font.weight.bold,
  },
  bookmarkLayerChipTextSelected: {
    color: theme.color.onPrimary,
  },
  mapFeedbackOverlay: {
    bottom: theme.space[5],
    left: theme.space[5],
    position: 'absolute',
    right: theme.space[5],
    zIndex: 6,
  },
  routeNoticeOverlay: {
    left: theme.space[5],
    position: 'absolute',
    right: theme.space[5],
    top: theme.space[4] + theme.layout.controlHSm + theme.space[3],
    zIndex: 5,
  },
  scheduleAddTray: {
    gap: theme.space[3],
    width: '100%',
  },
  scheduleAddChipScroller: {
    marginHorizontal: -theme.space[1],
  },
  scheduleAddChipRow: {
    flexDirection: 'row',
    gap: theme.space[2],
    paddingHorizontal: theme.space[1],
  },
  scheduleAddChip: {
    alignItems: 'center',
    backgroundColor: theme.color.surfaceSunken,
    borderColor: theme.color.borderDefault,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.space[2],
    maxWidth: 220,
    minHeight: theme.layout.controlHSm,
    paddingHorizontal: theme.space[3],
  },
  scheduleAddChipDisabled: {
    opacity: 0.48,
  },
  scheduleAddChipText: {
    color: theme.color.textStrong,
    flexShrink: 1,
    fontFamily: theme.font.family.semibold,
    fontSize: theme.font.size.label,
    fontWeight: theme.font.weight.semibold,
  },
  scheduleAddChipRemove: {
    color: theme.color.textMuted,
    fontFamily: theme.font.family.bold,
    fontSize: theme.font.size.label,
    fontWeight: theme.font.weight.bold,
  },
  scheduleAddTargetWrap: {
    gap: theme.space[3],
  },
  scheduleAddFeedback: {
    color: theme.color.danger,
    fontFamily: theme.font.family.semibold,
    fontSize: theme.font.size.caption,
    fontWeight: theme.font.weight.semibold,
  },
  scheduleMarkerDetailCard: {
    backgroundColor: theme.color.surfaceSunken,
    borderColor: theme.color.borderSubtle,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    gap: theme.space[2],
    padding: theme.space[4],
  },
  scheduleMarkerDetailSubtitle: {
    color: theme.color.primaryTextOnLight,
    fontFamily: theme.font.family.semibold,
    fontSize: theme.font.size.caption,
    fontWeight: theme.font.weight.semibold,
  },
  scheduleMarkerDetailTitle: {
    color: theme.color.textStrong,
    fontFamily: theme.font.family.bold,
    fontSize: theme.font.size.subhead,
    fontWeight: theme.font.weight.bold,
  },
  scheduleMarkerDetailMeta: {
    color: theme.color.textMuted,
    fontFamily: theme.font.family.semibold,
    fontSize: theme.font.size.caption,
    fontWeight: theme.font.weight.semibold,
  },
  scheduleMarkerDetailText: {
    color: theme.color.textBody,
    fontFamily: theme.font.family.regular,
    fontSize: theme.font.size.label,
    lineHeight: theme.font.size.label * theme.font.leading.normal,
  },
  mapSheetWrap: {
    borderColor: theme.color.borderSubtle,
    borderRadius: theme.radius.xl,
    borderWidth: 1,
    maxWidth: theme.layout.cardMaxW,
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  routeSheet: {
    backgroundColor: theme.color.surface,
    borderTopLeftRadius: theme.radius.xl,
    borderTopRightRadius: theme.radius.xl,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    ...theme.shadow.md,
  },
  routeSheetCollapsed: {
    maxHeight: 104,
  },
  routeSheetExpanded: {
    maxHeight: '78%',
    position: 'relative',
  },
  rowButton: {
    minHeight: 34,
    paddingHorizontal: theme.space[3],
    paddingVertical: theme.space[2],
  },
  rowSubtitle: {
    gap: theme.space[2],
  },
  searchButton: {
    alignItems: 'center',
    backgroundColor: theme.color.primary,
    borderRadius: theme.radius.md,
    flexDirection: 'row',
    gap: theme.space[2],
    justifyContent: 'center',
    minHeight: theme.layout.controlH,
    paddingHorizontal: theme.space[4],
  },
  searchButtonDisabled: {
    opacity: 0.55,
  },
  searchButtonText: {
    color: theme.color.onPrimary,
    fontFamily: theme.font.family.bold,
    fontWeight: theme.font.weight.bold,
  },
  searchInput: {
    backgroundColor: theme.color.surfaceSunken,
    borderColor: theme.color.borderDefault,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    color: theme.color.textStrong,
    flex: 1,
    fontFamily: theme.font.family.regular,
    minHeight: theme.layout.controlH,
    paddingHorizontal: theme.space[4],
  },
  searchNotice: {
    backgroundColor: theme.color.surfaceSunken,
    borderColor: theme.color.borderSubtle,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    gap: theme.space[2],
    padding: theme.space[4],
  },
  searchNoticeTitle: {
    color: theme.color.textStrong,
    fontFamily: theme.font.family.bold,
    fontSize: theme.font.size.label,
    fontWeight: theme.font.weight.bold,
  },
  searchResultCard: {
    borderColor: theme.color.borderSubtle,
    borderRadius: theme.radius.md,
    borderWidth: 1,
    gap: theme.space[2],
    padding: theme.space[4],
  },
  searchResultCardSelected: {
    backgroundColor: theme.color.primarySoft,
    borderColor: theme.color.primary,
  },
  searchResultList: {
    gap: theme.space[3],
  },
  searchRow: {
    flexDirection: 'row',
    gap: theme.space[3],
  },
  searchSection: {
    gap: theme.space[4],
    paddingBottom: theme.space[4],
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: theme.color.borderDefault,
    borderRadius: theme.radius.pill,
    height: 4,
    width: 42,
  },
  sheetHandleArea: {
    gap: theme.space[2],
    paddingHorizontal: theme.space[5],
    paddingVertical: theme.space[4],
  },
  sheetHelper: {
    color: theme.color.textMuted,
    fontFamily: theme.font.family.regular,
    fontSize: theme.font.size.caption,
    textAlign: 'center',
  },
  sheetTitle: {
    color: theme.color.textStrong,
    fontFamily: theme.font.family.bold,
    fontSize: theme.font.size.subhead,
    fontWeight: theme.font.weight.bold,
    textAlign: 'center',
  },
  summary: {
    gap: theme.space[1],
    paddingHorizontal: theme.space[1],
    paddingVertical: theme.space[4],
  },
  summaryHelper: {
    color: theme.color.textMuted,
    fontFamily: theme.font.family.regular,
    fontSize: theme.font.size.caption,
  },
  summaryTitle: {
    color: theme.color.textStrong,
    fontFamily: theme.font.family.bold,
    fontSize: theme.font.size.subhead,
    fontWeight: theme.font.weight.bold,
  },
});
